"use client";
/* eslint-disable react-hooks/set-state-in-effect -- la carga inicial sincroniza la vista con la API. */
import {AppHeader} from "@/components/app-header";
import {useSecurity} from "@/components/security-context";
import {apiRequest} from "@/lib/api-client";
import {BookOpen,ChartNoAxesColumnIncreasing,CheckCircle2,ClipboardCheck,ClipboardList,GraduationCap,History,LoaderCircle,Users} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {TrainingAudienceManager} from "./training-audience-manager";
import {TrainingCatalogManager} from "./training-catalog-manager";
import {TrainingContentBuilder} from "./training-content-builder";
import {TrainingEvaluationBuilder} from "./training-evaluation-builder";
import {TrainingTrackingManager} from "./training-tracking-manager";
import {TrainingResultsManager} from "./training-results";
import {TrainingVersionManager} from "./training-version-manager";
import {TrainingWorkflowManager} from "./training-workflow-manager";
type Section="catalogo"|"contenido"|"audiencias"|"seguimiento"|"resultados"; type Detail="contenido"|"evaluacion"|"participantes"|"revision";
export type Training={id:string;code:string;name:string;description:string|null;categoryId:string;category:string|null;unitId:string;unit:string|null;responsibleId:string;responsible:string|null;isActive:boolean};
export type Category={id:string;code:string;name:string;description:string|null;color:string|null;icon:string|null;order:number;isActive:boolean};
export type Reference={id:string;code:string;name:string;parentId:string|null;unitId:string|null;level:number};
export type Overview={categories:number;trainings:number;versions:number;categoryItems:Category[];items:Training[];versionItems:TrainingVersion[];units:Reference[];responsibles:Reference[];currentUnitId:string|null};
export type TrainingVersion={id:string;trainingId:string;training:string;number:string;publicTitle:string;summary:string|null;objective:string|null;status:number;availableFrom:string|null;availableUntil:string|null;daysToComplete:number|null;expirationRule:number;dynamicAudience:boolean;sequentialOrder:boolean;minimumPercentage:number|null;requiresApproval:boolean;surveyRequired:boolean;allowExpired:boolean;completionMessage:string|null;isActive:boolean};
const global=[{id:"catalogo",label:"Catálogo",icon:GraduationCap,permission:"CAP.CATALOGO.VER"},{id:"seguimiento",label:"Seguimiento",icon:ClipboardList,permission:"CAP.SEGUIMIENTO.VER"},{id:"resultados",label:"Resultados",icon:ChartNoAxesColumnIncreasing,permission:"CAP.RESULTADOS.VER"}] as const;
const steps=[{id:"contenido",label:"Contenido",help:"Secciones y materiales",icon:BookOpen},{id:"evaluacion",label:"Evaluación",help:"Preguntas y respuestas",icon:ClipboardCheck},{id:"participantes",label:"Participantes",help:"Personas que la realizarán",icon:Users},{id:"revision",label:"Revisión y publicación",help:"Validar y cambiar estado",icon:CheckCircle2}] as const;
export function TrainingAdministration({section}:{section:Section}){
 const security=useSecurity(),[data,setData]=useState<Overview|null>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[active,setActive]=useState<Section>(section),[detail,setDetail]=useState<Detail>(section==="audiencias"?"participantes":"contenido"),[selectedId,setSelectedId]=useState(""),[history,setHistory]=useState(false),[resultAssignmentId,setResultAssignmentId]=useState("");
 async function load(){setError("");try{setData(await apiRequest<Overview>("/api/training/administration/overview"))}catch(v){setError(v instanceof Error?v.message:"No fue posible cargar Capacitaciones.")}}
 useEffect(()=>{void load()},[]); const selected=data?.items.find(x=>x.id===selectedId),versions=data?.versionItems.filter(x=>x.trainingId===selectedId)??[]; const items=useMemo(()=>{const term=query.trim().toLocaleLowerCase("es");return term?data?.items.filter(x=>`${x.name} ${x.category??""}`.toLocaleLowerCase("es").includes(term))??[]:data?.items??[]},[data,query]);
 function open(id:string){setSelectedId(id);setActive("contenido");setDetail("contenido");setHistory(false)}
 return <main className="gaia-app-page min-h-screen"><AppHeader title={`Capacitaciones · ${active==="catalogo"?"Catálogo":active==="seguimiento"?"Seguimiento":active==="resultados"?"Resultados":"Gestión"}`}/><div className="mx-auto max-w-[1450px] px-5 py-8 lg:px-8"><header className="border-b border-[var(--gaia-line)] pb-5"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[var(--brand-primary)]">Gestión del aprendizaje</p><h1 className="mt-1 text-3xl font-semibold">Capacitaciones</h1><p className="mt-1 text-sm text-[var(--gaia-ink-500)]">Administra el catálogo y acompaña el ciclo de aprendizaje desde un solo lugar.</p></header><nav aria-label="Áreas de Capacitaciones" className="mt-4 flex gap-1 border-b">{global.filter(x=>security.can(x.permission)).map(x=>{const Icon=x.icon;return <button className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm ${active===x.id||active==="contenido"&&x.id==="catalogo"?"border-[var(--brand-primary)] font-bold text-[var(--brand-primary)]":"border-transparent text-[var(--gaia-ink-500)]"}`} key={x.id} onClick={()=>{setResultAssignmentId("");setActive(x.id)}}><Icon size={17}/>{x.label}</button>})}</nav>
 {error&&<p className="mt-6 rounded-2xl bg-[#fff0f0] p-4 text-sm text-[#9a384d]">{error}</p>}{!data&&!error&&<div className="mt-10 flex justify-center gap-2 text-sm"><LoaderCircle className="gaia-spin" size={18}/>Cargando…</div>}
 {data&&active==="catalogo"&&<TrainingCatalogManager data={data} items={items} onOpen={open} onQuery={setQuery} onReload={load} query={query}/>} 
 {data&&active==="contenido"&&selected&&<><section className="mt-5 rounded-3xl border bg-[var(--surface-card)] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><button className="text-sm font-semibold text-[var(--brand-primary)]" onClick={()=>setActive("catalogo")}>← Volver al catálogo</button><h2 className="mt-3 text-2xl font-semibold">{selected.name}</h2><p className="mt-1 text-sm text-[var(--gaia-ink-500)]">{selected.description||"Gestiona esta capacitación paso a paso."}</p></div><button className={`flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-semibold ${history?"bg-[var(--brand-primary)] text-white":""}`} onClick={()=>setHistory(!history)}><History size={17}/>Historial y versiones</button></div>{!history&&<ol className="mt-5 grid gap-2 lg:grid-cols-4">{steps.map((x,i)=>{const Icon=x.icon;return <li key={x.id}><button className={`flex w-full items-start gap-3 rounded-2xl border p-4 text-left ${detail===x.id?"border-[var(--brand-primary)] bg-[var(--gaia-accent-pale)]":"hover:border-[var(--brand-primary)]"}`} onClick={()=>setDetail(x.id)}><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[var(--brand-primary)] text-sm font-bold text-white">{i+1}</span><span><strong className="flex items-center gap-1.5 text-sm"><Icon size={15}/>{x.label}</strong><small className="mt-1 block text-[var(--gaia-ink-500)]">{x.help}</small></span></button></li>})}</ol>}</section>{history?<TrainingVersionManager data={data} onReload={load} selectedTrainingId={selectedId}/>:<div className="mt-5">{detail==="contenido"&&<TrainingContentBuilder versions={versions}/>} {detail==="evaluacion"&&<TrainingEvaluationBuilder versions={versions}/>} {detail==="participantes"&&<TrainingAudienceManager data={{...data,versionItems:versions}}/>} {detail==="revision"&&<TrainingWorkflowManager onReload={load} versions={versions}/>}</div>}</>}
 {data&&active==="contenido"&&!selected&&<p className="mt-8 rounded-2xl border border-dashed p-8 text-center">Vuelve al catálogo y selecciona una capacitación para gestionarla.</p>}{data&&active==="seguimiento"&&<TrainingTrackingManager onReview={(id)=>{setResultAssignmentId(id??"");setActive("resultados")}} selectedTrainingId={selectedId} versions={data.versionItems}/>} {data&&active==="resultados"&&<TrainingResultsManager key={resultAssignmentId} selectedAssignmentId={resultAssignmentId} onClearAssignment={()=>setResultAssignmentId("")} selectedTrainingId={selectedId} versions={data.versionItems}/>}</div></main>
}
