"use client";

import {apiRequest} from "@/lib/api-client";
import {AlertTriangle,ExternalLink,Eye,FileText,LoaderCircle,X} from "lucide-react";
import {useEffect,useState} from "react";
import type {TrainingVersion} from "./training-administration";
import {youtubeEmbed} from "./training-content-rules";

type Block={resourceId:string|null;id:string;name:string;type:number;order:number;required:boolean;html:string|null;externalUrl:string|null;actionText:string|null;openNewTab:boolean;active:boolean};
type Section={id:string;name:string;description:string|null;order:number;required:boolean;active:boolean;blocks:Block[]};
type Option={id:string;name:string;order:number};
type Question={id:string;statement:string;type:number;required:boolean;order:number;minimumScale:number|null;maximumScale:number|null;minimumLabel:string|null;maximumLabel:string|null;options:Option[]};
type Evaluation={id:string;name:string;description:string|null;required:boolean;minimumPercentage:number|null;maximumAttempts:number|null;order:number;questions:Question[]};

export function TrainingPreviewDialog({version,onClose}:{version:TrainingVersion|null;onClose:()=>void}){return version?<TrainingPreviewContent key={version.id} version={version} onClose={onClose}/>:null}
function TrainingPreviewContent({version,onClose}:{version:TrainingVersion;onClose:()=>void}){
 const[sections,setSections]=useState<Section[]>([]),[evaluations,setEvaluations]=useState<Evaluation[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{if(!version)return;let active=true;Promise.all([apiRequest<Section[]>(`/api/training/administration/versions/${version.id}/content`),apiRequest<Evaluation[]>(`/api/training/administration/versions/${version.id}/evaluations`)]).then(([content,assessment])=>{if(active){setSections(content);setEvaluations(assessment)}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"No fue posible preparar la vista previa.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[version]);
 useEffect(()=>{if(!version)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";function keydown(event:KeyboardEvent){if(event.key==="Escape")onClose()}document.addEventListener("keydown",keydown);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",keydown)}},[version,onClose]);
 if(!version)return null;
 const visibleSections=sections.filter(item=>item.active).sort(byOrder),visibleEvaluations=[...evaluations].sort(byOrder);
 return <div className="gaia-dialog-backdrop !p-0 sm:!p-5" role="presentation"><section aria-label={`Vista previa de ${version.publicTitle}`} aria-modal="true" className="grid h-full w-full max-w-[1180px] grid-rows-[auto_minmax(0,1fr)] overflow-hidden bg-[#f4f7f5] shadow-2xl sm:max-h-[94vh] sm:rounded-3xl" role="dialog">
  <header className="flex items-start justify-between gap-4 border-b bg-white px-5 py-4 sm:px-7"><div><span className="inline-flex items-center gap-2 rounded-full bg-[var(--gaia-accent-pale)] px-3 py-1 text-xs font-bold uppercase tracking-wide text-[var(--brand-primary)]"><Eye size={14}/>Vista previa del participante</span><h2 className="mt-2 text-xl font-semibold sm:text-2xl">{version.publicTitle}</h2><p className="mt-1 text-xs text-[var(--gaia-ink-500)]">{version.training} · versión {version.number} · No registra progreso ni respuestas.</p></div><button aria-label="Cerrar vista previa" className="gaia-button gaia-button-secondary !min-h-10 !px-3" onClick={onClose} type="button"><X size={18}/></button></header>
  <div className="overflow-y-auto px-4 py-5 sm:px-7 sm:py-7">{loading?<div className="grid min-h-80 place-items-center"><span className="flex items-center gap-2 text-sm"><LoaderCircle className="animate-spin" size={18}/>Preparando la capacitación…</span></div>:error?<p className="rounded-2xl border border-[#e9b8c2] bg-[#fff0f0] p-4 text-sm text-[#9a384d]">{error}</p>:<div className="mx-auto max-w-4xl">
   <section className="rounded-3xl bg-[var(--brand-primary)] p-6 !text-white shadow-lg sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] !text-white/80">Capacitación Gaia</p><h1 className="mt-2 text-2xl font-semibold !text-white sm:text-4xl">{version.publicTitle}</h1><p className="mt-3 max-w-3xl text-sm leading-6 !text-white/85">{version.objective||version.summary||"Esta versión no tiene un objetivo o resumen configurado."}</p></section>
   <div className="mt-5 space-y-5">{visibleSections.map((section,sectionIndex)=><article className="rounded-3xl border border-[var(--gaia-line)] bg-white p-5 sm:p-6" key={section.id}><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[var(--gaia-accent-soft)] text-sm font-bold text-[var(--brand-primary)]">{sectionIndex+1}</span><div><h2 className="text-xl font-semibold">{section.name}{section.required&&<span className="ml-1 text-[#9a384d]">*</span>}</h2>{section.description&&<p className="mt-1 text-sm text-[var(--gaia-ink-500)]">{section.description}</p>}</div></div><div className="mt-5 space-y-3">{section.blocks.filter(item=>item.active).sort(byOrder).map((block,index)=><Content block={block} index={index} key={block.id} versionId={version.id}/>)}{!section.blocks.some(item=>item.active)&&<Warning text="Esta sección está vacía y el participante no verá contenidos aquí."/>}</div></article>)}{!visibleSections.length&&<Warning text="Esta versión todavía no tiene secciones visibles."/>}</div>
   <section className="mt-6 rounded-3xl border border-[var(--gaia-line)] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--gaia-accent-soft)] text-[var(--brand-primary)]"><FileText size={19}/></span><div><h2 className="text-xl font-semibold">Evaluación del aprendizaje</h2><p className="text-xs text-[var(--gaia-ink-500)]">Así se presentarán las preguntas al finalizar el contenido.</p></div></div><div className="mt-5 space-y-5">{visibleEvaluations.map(evaluation=><article className="rounded-2xl border border-[var(--gaia-line)] p-4" key={evaluation.id}><h3 className="font-semibold">{evaluation.name}{evaluation.required&&<span className="ml-1 text-[#9a384d]">*</span>}</h3>{evaluation.description&&<p className="mt-1 text-sm text-[var(--gaia-ink-500)]">{evaluation.description}</p>}<p className="mt-1 text-xs text-[var(--gaia-ink-500)]">{evaluation.maximumAttempts?`${evaluation.maximumAttempts} intento(s)`:"Sin límite de intentos"}{evaluation.minimumPercentage!==null?` · Aprobación desde ${evaluation.minimumPercentage}%`:""}</p><div className="mt-4 space-y-4">{[...evaluation.questions].sort(byOrder).map((question,index)=><QuestionPreview index={index} key={question.id} question={question}/>)}{!evaluation.questions.length&&<Warning text="Esta evaluación todavía no tiene preguntas."/>}</div></article>)}{!visibleEvaluations.length&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-[var(--gaia-ink-500)]">Esta capacitación no tiene evaluación configurada.</p>}</div></section>
  </div>}</div>
 </section></div>
}

function Content({block,index,versionId}:{block:Block;index:number;versionId:string}){const resource=block.resourceId?`${process.env.NEXT_PUBLIC_GAIA_API_URL??"https://localhost:7168"}/api/training/administration/versions/${versionId}/resources/${block.resourceId}`:null;const youtube=block.type===299541074&&block.externalUrl?youtubeEmbed(block.externalUrl):null;return <section className="rounded-2xl border border-[var(--gaia-line)] p-4"><div className="flex items-start gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[var(--gaia-surface-subtle)] text-xs font-bold">{index+1}</span><div className="min-w-0 flex-1"><h3 className="font-semibold">{block.name}{block.required&&<span className="ml-1 text-[#9a384d]">*</span>}</h3>{block.html&&<p className={`mt-3 whitespace-pre-line text-sm leading-7 ${block.type===299541072?"rounded-xl bg-[var(--gaia-accent-pale)] p-4 font-medium":""}`}>{strip(block.html)}</p>}{resource&&block.type===299541074&&<video className="mt-4 w-full rounded-xl" controls preload="metadata" src={resource}/>} {resource&&block.type!==299541074&&<a className="gaia-button gaia-button-secondary mt-4" href={`${resource}?download=true`} target="_blank" rel="noopener noreferrer">Abrir documento</a>}{youtube&&<div className="mt-4 aspect-video overflow-hidden rounded-2xl bg-black"><iframe allowFullScreen className="h-full w-full" src={youtube} title={block.name}/></div>}{block.externalUrl&&!youtube&&!resource&&<a className="gaia-button gaia-button-secondary mt-4 w-fit !text-xs" href={block.externalUrl} rel="noopener noreferrer" target="_blank"><ExternalLink size={14}/>{block.type===299541075?"Abrir documento":block.type===299541074?"Abrir video":block.actionText||"Abrir recurso"}</a>}</div></div></section>}
function QuestionPreview({question,index}:{question:Question;index:number}){const options=[...question.options].sort(byOrder),buttons=[299541060,299541062].includes(question.type),hasChoices=[299541060,299541061,299541062].includes(question.type);return <section className="rounded-2xl bg-[var(--gaia-surface-subtle)] p-4 sm:p-5"><h4 className="text-sm font-semibold leading-6">{index+1}. {question.statement}{question.required&&<span className="ml-1 text-[#9a384d]">*</span>}</h4><div className="mt-3 space-y-2">{question.type===299541061?<select aria-label={question.statement} className="min-h-12 w-full rounded-xl border border-[var(--gaia-line)] bg-white px-3 outline-none transition focus:border-[var(--brand-primary)] focus:ring-2 focus:ring-[var(--gaia-accent-soft)]" defaultValue=""><option disabled value="">Selecciona una opción</option>{options.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select>:buttons?options.map(option=><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-[var(--gaia-line)] bg-white p-3 text-sm transition hover:border-[var(--brand-primary)] hover:bg-[var(--gaia-accent-pale)]" key={option.id}><input className="size-4 accent-[var(--brand-primary)]" name={`preview-${question.id}`} type="radio"/>{option.name}</label>):question.type===299541064?<textarea className="w-full rounded-xl border border-[var(--gaia-line)] bg-white p-3 outline-none transition focus:border-[var(--brand-primary)] focus:ring-2 focus:ring-[var(--gaia-accent-soft)]" placeholder="Escribe tu respuesta" rows={4}/>:question.type===299541065?<Scale question={question}/>:<input className="min-h-11 w-full rounded-xl border border-[var(--gaia-line)] bg-white px-3 outline-none transition focus:border-[var(--brand-primary)] focus:ring-2 focus:ring-[var(--gaia-accent-soft)]" placeholder="Escribe tu respuesta"/>}{hasChoices&&!options.length&&<Warning text="Esta pregunta no tiene opciones configuradas."/>}</div></section>}
function Scale({question}:{question:Question}){const min=question.minimumScale??1,max=question.maximumScale??5,values=max-min<=10?Array.from({length:max-min+1},(_,index)=>min+index):[];return <div><div className="flex justify-between gap-4 text-xs text-[var(--gaia-ink-500)]"><span>{question.minimumLabel||"Mínimo"}</span><span className="text-right">{question.maximumLabel||"Máximo"}</span></div><div className="mt-3 flex flex-wrap gap-2">{values.map(value=><label className="cursor-pointer" key={value}><input className="peer sr-only" name={`preview-${question.id}`} type="radio"/><span className="grid size-11 place-items-center rounded-full border border-[var(--gaia-line)] bg-white text-sm font-semibold transition hover:border-[var(--brand-primary)] peer-checked:border-[var(--brand-primary)] peer-checked:bg-[var(--brand-primary)] peer-checked:text-white">{value}</span></label>)}</div></div>}
function Warning({text}:{text:string}){return <p className="flex gap-2 rounded-xl border border-[#ead39c] bg-[#fff9e9] p-4 text-sm text-[#76551a]"><AlertTriangle className="shrink-0" size={17}/>{text}</p>}
function byOrder<T extends {order:number}>(left:T,right:T){return left.order-right.order}
function strip(value:string){return value.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()}
