"use client";
import {FormDialog} from "@/components/form-dialog";
import {useSecurity} from "@/components/security-context";
import {apiRequest} from "@/lib/api-client";
import {ArrowLeft,ChevronLeft,ChevronRight,Pencil,Plus,Search,SlidersHorizontal,Tags} from "lucide-react";
import {type FormEvent,useMemo,useState} from "react";
import type {Category,Overview,Training} from "./training-administration";
import {TrainingUnitSelect} from "./training-unit-select";

type CategoryForm={id?:string;name:string;description:string;color:string;icon:string;order:number;isActive:boolean};
type TrainingForm={id?:string;name:string;description:string;categoryId:string;unitId:string;responsibleId:string;isActive:boolean};
const emptyCategory:CategoryForm={name:"",description:"",color:"#286B78",icon:"",order:0,isActive:true};
const emptyTraining:TrainingForm={name:"",description:"",categoryId:"",unitId:"",responsibleId:"",isActive:true};

export function TrainingCatalogManager({data:sourceData,items,query,onQuery,onReload,onOpen}:{data:Overview;items:Training[];query:string;onQuery:(value:string)=>void;onReload:()=>Promise<void>;onOpen:(id:string)=>void}){
 const security=useSecurity(),canManage=security.can("CAP.CATALOGO.ADMINISTRAR");
 const[category,setCategory]=useState<CategoryForm|null>(null),[training,setTraining]=useState<TrainingForm|null>(null),[saving,setSaving]=useState(false),[formError,setFormError]=useState(""),[categoryFilter,setCategoryFilter]=useState(""),[unitFilter,setUnitFilter]=useState(""),[statusFilter,setStatusFilter]=useState(""),[page,setPage]=useState(1),[showCategories,setShowCategories]=useState(false);
 const data={...sourceData,units:sourceData.units.map(value=>({...value,name:`${"— ".repeat(Math.max(0,value.level-1))}${value.name}`})),responsibles:training?.unitId?sourceData.responsibles.filter(value=>value.unitId===training.unitId):sourceData.responsibles};
 const pageSize=10;
 const filtered=useMemo(()=>items.filter(item=>(!categoryFilter||item.categoryId===categoryFilter)&&(!unitFilter||item.unitId===unitFilter)&&(!statusFilter||String(item.isActive)===statusFilter)),[items,categoryFilter,unitFilter,statusFilter]);
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),currentPage=Math.min(page,pages),visible=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);
 function editCategory(item?:Category){setFormError("");setCategory(item?{id:item.id,name:item.name,description:item.description??"",color:item.color??"#286B78",icon:item.icon??"",order:item.order,isActive:item.isActive}:{...emptyCategory,order:data.categoryItems.length*10});}
 function editTraining(item?:Training){setFormError("");const defaultUnitId=sourceData.currentUnitId??"",defaultResponsibleId=sourceData.responsibles.find(value=>value.id===security.user?.thirdPartyId&&value.unitId===defaultUnitId)?.id??"";setTraining(item?{id:item.id,name:item.name,description:item.description??"",categoryId:item.categoryId,unitId:item.unitId,responsibleId:item.responsibleId,isActive:item.isActive}:{...emptyTraining,categoryId:sourceData.categoryItems.find(value=>value.isActive)?.id??"",unitId:defaultUnitId,responsibleId:defaultResponsibleId});}
 async function saveCategory(event:FormEvent){event.preventDefault();if(!category)return;setSaving(true);setFormError("");try{await apiRequest(`/api/training/administration/categories${category.id?`/${category.id}`:""}`,{method:category.id?"PUT":"POST",body:JSON.stringify(category)});setCategory(null);await onReload();}catch(reason){setFormError(reason instanceof Error?reason.message:"No fue posible guardar la categoría.")}finally{setSaving(false)}}
 async function saveTraining(event:FormEvent){event.preventDefault();if(!training)return;setSaving(true);setFormError("");try{await apiRequest(`/api/training/administration/trainings${training.id?`/${training.id}`:""}`,{method:training.id?"PUT":"POST",body:JSON.stringify(training)});setTraining(null);await onReload();}catch(reason){setFormError(reason instanceof Error?reason.message:"No fue posible guardar la capacitación.")}finally{setSaving(false)}}
 return <>
 {showCategories?<section className="mt-5 rounded-3xl border border-[var(--gaia-line)] bg-[var(--surface-card)] p-6"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-[var(--gaia-line)] pb-5"><div className="flex items-start gap-3"><button aria-label="Volver al catálogo" className="rounded-xl border border-[var(--gaia-line)] p-2" onClick={()=>setShowCategories(false)} type="button"><ArrowLeft size={18}/></button><div><h2 className="text-xl font-semibold">Categorías de capacitación</h2><p className="mt-1 text-sm text-[var(--gaia-ink-500)]">Administra las temáticas sin reducir el espacio de trabajo del catálogo.</p></div></div>{canManage&&<button className="flex items-center gap-2 rounded-xl bg-[var(--brand-primary)] px-4 py-3 text-sm font-bold text-white" onClick={()=>editCategory()} type="button"><Plus size={17}/>Nueva categoría</button>}</header><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.categoryItems.map(item=><article className="flex min-h-28 items-center gap-4 rounded-2xl border border-[var(--gaia-line)] p-4" key={item.id}><span className="size-4 shrink-0 rounded-full" style={{background:item.color??"var(--brand-primary)"}}/><div className="min-w-0 flex-1"><strong className="block break-words">{item.name}</strong><p className="mt-1 line-clamp-2 text-xs text-[var(--gaia-ink-500)]">{item.description||"Sin descripción"}</p><small className="mt-2 block font-semibold text-[var(--brand-primary)]">{item.isActive?"Activa":"Inactiva"}</small></div>{canManage&&<button aria-label={`Editar ${item.name}`} className="shrink-0 rounded-lg border border-[var(--gaia-line)] p-2" onClick={()=>editCategory(item)} type="button"><Pencil size={14}/></button>}</article>)}{!data.categoryItems.length&&<p className="col-span-full rounded-xl border border-dashed p-8 text-center text-sm text-[var(--gaia-ink-500)]">Crea la primera categoría para organizar el catálogo.</p>}</div></section>:<section className="mt-5"><div className="min-w-0 overflow-hidden rounded-3xl border border-[var(--gaia-line)] bg-[var(--surface-card)]"><header className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="text-xl font-semibold">Catálogo de capacitaciones</h2><p className="mt-1 text-xs text-[var(--gaia-ink-500)]">Selecciona una capacitación para gestionar sus versiones, contenido, evaluación y audiencia.</p></div><div className="flex flex-wrap gap-2"><button className="flex items-center gap-2 rounded-xl border border-[var(--gaia-line)] px-4 py-3 text-sm font-bold text-[var(--brand-primary)]" onClick={()=>setShowCategories(true)} type="button"><Tags size={17}/>Gestionar categorías</button>{canManage&&<button className="flex items-center gap-2 rounded-xl bg-[var(--brand-primary)] px-4 py-3 text-sm font-bold text-white" onClick={()=>editTraining()} type="button"><Plus size={17}/>Nueva capacitación</button>}</div></header>
 <div className="grid gap-2 border-y border-[var(--gaia-line)] bg-[var(--gaia-surface-subtle)] p-4 md:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_180px_210px_145px_auto]"><label className="flex items-center gap-2 rounded-xl border border-[var(--gaia-line)] bg-[var(--surface-card)] px-3"><Search size={16}/><input className="min-h-11 w-full bg-transparent text-sm outline-none" onChange={event=>{onQuery(event.target.value);setPage(1)}} placeholder="Buscar por nombre o categoría" value={query}/></label><Filter value={categoryFilter} set={value=>{setCategoryFilter(value);setPage(1)}} label="Categoría"><option value="">Todas</option>{data.categoryItems.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Filter><Filter value={unitFilter} set={value=>{setUnitFilter(value);setPage(1)}} label="Unidad responsable"><option value="">Todas</option>{[...data.units].sort((a,b)=>a.code.localeCompare(b.code,"es")).map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</Filter><Filter value={statusFilter} set={value=>{setStatusFilter(value);setPage(1)}} label="Estado"><option value="">Todos</option><option value="true">Activas</option><option value="false">Inactivas</option></Filter><button className="rounded-xl px-3 text-xs font-semibold text-[var(--brand-primary)]" onClick={()=>{onQuery("");setCategoryFilter("");setUnitFilter("");setStatusFilter("");setPage(1)}} type="button">Limpiar</button></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left text-sm"><thead className="bg-[var(--gaia-accent-pale)] text-[11px] uppercase tracking-wide text-[var(--gaia-ink-500)]"><tr><th className="px-5 py-3">Capacitación</th><th className="px-4 py-3">Categoría</th><th className="px-4 py-3">Unidad responsable</th><th className="px-4 py-3">Responsable funcional</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3 text-right">Acciones</th></tr></thead><tbody>{visible.map(item=><tr className="border-t border-[var(--gaia-line)] hover:bg-[var(--gaia-surface-subtle)]" key={item.id}><td className="px-5 py-4"><button className="text-left font-semibold text-[var(--brand-primary)] hover:underline" onClick={()=>onOpen(item.id)} type="button">{item.name}</button>{item.description&&<small className="mt-1 block max-w-md truncate text-[var(--gaia-ink-500)]">{item.description}</small>}</td><td className="px-4 py-4">{item.category||"Sin categoría"}</td><td className="px-4 py-4">{item.unit||"Sin unidad"}</td><td className="px-4 py-4">{item.responsible||"Sin responsable"}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.isActive?"bg-[#e7f5eb] text-[#286846]":"bg-[var(--gaia-surface-subtle)] text-[var(--gaia-ink-500)]"}`}>{item.isActive?"Activa":"Inactiva"}</span></td><td className="px-4 py-4 text-right"><div className="flex justify-end gap-2"><button className="rounded-lg border border-[var(--gaia-line)] px-3 py-2 text-xs font-semibold" onClick={()=>onOpen(item.id)} type="button">Gestionar</button>{canManage&&<button aria-label={`Editar ${item.name}`} className="rounded-lg border border-[var(--gaia-line)] p-2" onClick={()=>editTraining(item)} type="button"><Pencil size={14}/></button>}</div></td></tr>)}{!visible.length&&<tr><td className="p-10 text-center text-[var(--gaia-ink-500)]" colSpan={6}>No hay capacitaciones que coincidan con los filtros.</td></tr>}</tbody></table></div>
 <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--gaia-line)] px-5 py-4 text-xs text-[var(--gaia-ink-500)]"><span>{filtered.length?`${(currentPage-1)*pageSize+1}-${Math.min(currentPage*pageSize,filtered.length)} de ${filtered.length}`:"0 resultados"}</span><div className="flex items-center gap-2"><button aria-label="Página anterior" className="rounded-lg border p-2 disabled:opacity-40" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={15}/></button><strong>Página {currentPage} de {pages}</strong><button aria-label="Página siguiente" className="rounded-lg border p-2 disabled:opacity-40" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><ChevronRight size={15}/></button></div></footer></div></section>}
 <FormDialog error={formError} formId="training-category-form" loading={saving} onClose={()=>setCategory(null)} open={Boolean(category)} submitLabel={category?.id?"Guardar categoría":"Crear categoría"} subtitle="El código interno se genera automáticamente." title={category?.id?"Editar categoría":"Nueva categoría"}>{category&&<form className="space-y-4" id="training-category-form" onSubmit={saveCategory}><Field label="Nombre"><input maxLength={150} onChange={event=>setCategory({...category,name:event.target.value})} required value={category.name}/></Field><Field label="Descripción"><textarea maxLength={500} onChange={event=>setCategory({...category,description:event.target.value})} rows={3} value={category.description}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Color"><input onChange={event=>setCategory({...category,color:event.target.value})} pattern="#[0-9a-fA-F]{6}" type="color" value={category.color}/></Field><Field label="Orden"><input min={0} onChange={event=>setCategory({...category,order:Number(event.target.value)})} type="number" value={category.order}/></Field></div><Check checked={category.isActive} label="Categoría activa" onChange={value=>setCategory({...category,isActive:value})}/></form>}</FormDialog>
 <FormDialog error={formError} formId="training-form" loading={saving} onClose={()=>setTraining(null)} open={Boolean(training)} submitLabel={training?.id?"Guardar capacitación":"Crear capacitación"} subtitle="Crea la ficha estable; después podrás preparar contenido, evaluación, audiencia y publicación por versiones." title={training?.id?"Editar capacitación":"Nueva capacitación"}>{training&&<form className="space-y-4" id="training-form" onSubmit={saveTraining}><Field label="Nombre" help="Nombre con el que las personas reconocerán la capacitación."><input maxLength={200} onChange={event=>setTraining({...training,name:event.target.value})} required value={training.name}/></Field><Field label="Descripción general" help="Resume el propósito de la capacitación y el aprendizaje esperado."><textarea maxLength={4000} onChange={event=>setTraining({...training,description:event.target.value})} rows={4} value={training.description}/></Field><Field label="Categoría" help="Agrupa capacitaciones relacionadas y facilita búsquedas, navegación e informes."><select onChange={event=>setTraining({...training,categoryId:event.target.value})} required value={training.categoryId}><option value="">Selecciona una categoría</option>{data.categoryItems.filter(item=>item.isActive||item.id===training.categoryId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Unidad responsable" help="Unidad encargada de administrar la capacitación y responder por sus resultados."><TrainingUnitSelect units={sourceData.units} value={training.unitId} onChange={unitId=>setTraining({...training,unitId,responsibleId:""})}/></Field><Field label="Responsable funcional" help="Persona encargada de mantener el contenido, atender observaciones y coordinar el ciclo de la capacitación."><select onChange={event=>setTraining({...training,responsibleId:event.target.value})} required value={training.responsibleId}><option value="">Selecciona una persona</option>{data.responsibles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Check checked={training.isActive} label="Capacitación activa" onChange={value=>setTraining({...training,isActive:value})}/></form>}</FormDialog>
 </>;
}
function Field({label,help,children}:{label:string;help?:string;children:React.ReactNode}){return <label className="block text-sm font-semibold"><span className="mb-2 block">{label}</span><span className="block [&>input]:min-h-11 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-[var(--gaia-line)] [&>input]:px-3 [&>select]:min-h-11 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:border-[var(--gaia-line)] [&>select]:px-3 [&>textarea]:w-full [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:border-[var(--gaia-line)] [&>textarea]:p-3">{children}</span>{help&&<small className="mt-1.5 block font-normal leading-5 text-[var(--gaia-ink-500)]">{help}</small>}</label>}
function Check({checked,label,onChange}:{checked:boolean;label:string;onChange:(value:boolean)=>void}){return <label className="flex items-center gap-3 rounded-xl bg-[var(--gaia-surface-subtle)] p-3 text-sm font-semibold"><input checked={checked} onChange={event=>onChange(event.target.checked)} type="checkbox"/><span>{label}</span></label>}
function Filter({label,value,set,children}:{label:string;value:string;set:(value:string)=>void;children:React.ReactNode}){return <label className="relative rounded-xl border border-[var(--gaia-line)] bg-[var(--surface-card)] px-3 pb-1 pt-1"><span className="flex items-center gap-1 text-[10px] text-[var(--gaia-ink-500)]"><SlidersHorizontal size={10}/>{label}</span><select className="w-full bg-transparent text-sm font-semibold outline-none" onChange={e=>set(e.target.value)} value={value}>{children}</select></label>}
