"use client";

import {apiRequest} from "@/lib/api-client";
import {BarChart3,CheckCircle2,Clock3,LoaderCircle,RefreshCw,Search,UsersRound} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import type {TrainingVersion} from "./training-administration";

type Assignment={id:string;versionId:string;training:string;version:string;participant:string;unitId:string|null;unit:string|null;status:number;assignedAt:string;dueAt:string|null;startedAt:string|null;lastAccessAt:string|null;completedAt:string|null;progress:number;result:number|null;attempts:number};
type Tracking={total:number;assigned:number;inProgress:number;overdue:number;completed:number;items:Assignment[]};
type Result={assignmentId:string;versionId:string;training:string;version:string;participant:string;unit:string|null;status:number;progress:number;result:number|null;attempts:number;completedAt:string|null;approvedAt:string|null};
type Results={participants:number;completed:number;approved:number;notApproved:number;averageResult:number;items:Result[]};

const statusLabel=(value:number)=>({299541090:"Asignada",299541091:"En curso",299541092:"Pendiente de evaluación",299541093:"Aprobada",299541094:"No aprobada",299541095:"Vencida",299541096:"Exonerada",299541097:"Cancelada"}[value]??"Sin estado");
const date=(value:string|null)=>value?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium"}).format(new Date(value)):"Sin fecha";

export function TrainingTrackingManager({versions,selectedTrainingId}:{versions:TrainingVersion[];selectedTrainingId:string}){
 const[data,setData]=useState<Tracking|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(""),[query,setQuery]=useState(""),[state,setState]=useState(""),[page,setPage]=useState(1);
 async function load(){setError("");try{setData(await apiRequest<Tracking>("/api/training/administration/tracking"))}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible consultar el seguimiento.")}}
 useEffect(()=>{let active=true;apiRequest<Tracking>("/api/training/administration/tracking").then(value=>{if(active)setData(value)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"No fue posible consultar el seguimiento.")});return()=>{active=false}},[]);
 const rows=useMemo(()=>{const term=query.trim().toLocaleLowerCase("es");return(data?.items??[]).filter(x=>(!selectedTrainingId||versions.some(v=>v.id===x.versionId&&v.trainingId===selectedTrainingId))&&(!state||String(x.status)===state)&&(!term||`${x.training} ${x.participant} ${x.unit??""}`.toLocaleLowerCase("es").includes(term)))},[data,query,state,selectedTrainingId,versions]);
 const pages=Math.max(1,Math.ceil(rows.length/10)),visible=rows.slice((Math.min(page,pages)-1)*10,Math.min(page,pages)*10);
 async function synchronize(id:string){setBusy(id);setError("");try{await apiRequest(`/api/training/administration/versions/${id}/assignments/synchronize`,{method:"POST",body:"{}"});await load()}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible sincronizar las asignaciones.")}finally{setBusy("")}}
 return <section className="mt-6 space-y-5">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[var(--brand-primary)]">Operación formativa</p><h2 className="mt-1 text-2xl font-semibold">Seguimiento de participantes</h2><p className="mt-1 text-sm text-[var(--gaia-ink-500)]">Consulta quién fue asignado, su avance, vencimiento e intentos sin salir del contexto de la capacitación.</p></div><button className="flex items-center gap-2 rounded-xl border border-[var(--gaia-line)] bg-white px-4 py-2 text-sm font-semibold" onClick={()=>void load()} type="button"><RefreshCw size={16}/>Actualizar</button></header>
  {error&&<p className="rounded-2xl bg-[#fff0f0] p-4 text-sm text-[#9a384d]">{error}</p>}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Asignaciones" value={data?.total??0}/><Metric label="Sin iniciar" value={data?.assigned??0}/><Metric label="En curso" value={data?.inProgress??0}/><Metric label="Vencidas" value={data?.overdue??0}/><Metric label="Finalizadas" value={data?.completed??0}/></div>
  {!!versions.filter(v=>v.status===299540002&&(!selectedTrainingId||v.trainingId===selectedTrainingId)).length&&<div className="rounded-2xl border border-[var(--gaia-line)] bg-[var(--gaia-accent-pale)] p-4"><strong className="text-sm">Asignaciones de versiones publicadas</strong><p className="mt-1 text-xs text-[var(--gaia-ink-500)]">La publicación genera la audiencia automáticamente. Usa sincronizar si agregaste participantes a una audiencia dinámica o necesitas recuperar una ejecución incompleta.</p><div className="mt-3 flex flex-wrap gap-2">{versions.filter(v=>v.status===299540002&&(!selectedTrainingId||v.trainingId===selectedTrainingId)).map(v=><button className="rounded-xl bg-[var(--brand-primary)] px-4 py-2 text-xs font-bold text-white disabled:opacity-60" disabled={busy===v.id} key={v.id} onClick={()=>void synchronize(v.id)} type="button">{busy===v.id?<LoaderCircle className="inline animate-spin" size={14}/>:<RefreshCw className="inline" size={14}/>} Sincronizar {v.training} · v{v.number}</button>)}</div></div>}
  <div className="overflow-hidden rounded-3xl border border-[var(--gaia-line)] bg-white"><div className="flex flex-wrap gap-3 border-b border-[var(--gaia-line)] p-4"><label className="flex min-w-64 flex-1 items-center gap-2 rounded-xl border border-[var(--gaia-line)] px-3"><Search size={16}/><input className="w-full py-2 outline-none" onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Buscar participante, capacitación o unidad" value={query}/></label><select className="rounded-xl border border-[var(--gaia-line)] px-3" onChange={e=>{setState(e.target.value);setPage(1)}} value={state}><option value="">Todos los estados</option>{[299541090,299541091,299541092,299541093,299541094,299541095,299541096,299541097].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[var(--gaia-accent-pale)] text-[10px] uppercase tracking-wide text-[var(--gaia-ink-500)]"><tr><th className="px-5 py-3">Participante</th><th className="px-4 py-3">Capacitación</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Avance</th><th className="px-4 py-3">Vencimiento</th><th className="px-4 py-3">Intentos</th></tr></thead><tbody>{visible.map(x=><tr className="border-t border-[var(--gaia-line)]" key={x.id}><td className="px-5 py-4"><strong>{x.participant}</strong><small className="block text-[var(--gaia-ink-500)]">{x.unit??"Sin unidad registrada"}</small></td><td className="px-4 py-4">{x.training}<small className="block text-[var(--gaia-ink-500)]">Versión {x.version}</small></td><td className="px-4 py-4"><span className="rounded-full bg-[var(--gaia-accent-soft)] px-2 py-1 text-xs font-bold text-[var(--brand-primary)]">{statusLabel(x.status)}</span></td><td className="px-4 py-4"><div className="h-2 w-28 overflow-hidden rounded-full bg-slate-100"><i className="block h-full bg-[var(--brand-primary)]" style={{width:`${Math.min(100,x.progress)}%`}}/></div><small>{x.progress}%</small></td><td className="px-4 py-4">{date(x.dueAt)}</td><td className="px-4 py-4">{x.attempts}</td></tr>)}{!visible.length&&<tr><td className="p-10 text-center text-[var(--gaia-ink-500)]" colSpan={6}>{data?"No hay asignaciones para estos filtros.":"Cargando seguimiento…"}</td></tr>}</tbody></table></div><Pager page={Math.min(page,pages)} pages={pages} setPage={setPage}/></div>
 </section>
}

export function TrainingResultsManager({versions,selectedTrainingId}:{versions:TrainingVersion[];selectedTrainingId:string}){
 const[data,setData]=useState<Results|null>(null),[error,setError]=useState(""),[query,setQuery]=useState("");
 useEffect(()=>{apiRequest<Results>("/api/training/administration/results").then(setData).catch(reason=>setError(reason instanceof Error?reason.message:"No fue posible consultar resultados."))},[]);
 const rows=useMemo(()=>{const term=query.trim().toLocaleLowerCase("es");return(data?.items??[]).filter(x=>(!selectedTrainingId||versions.some(v=>v.trainingId===selectedTrainingId&&v.id===x.versionId))&&(!term||`${x.training} ${x.participant} ${x.unit??""}`.toLocaleLowerCase("es").includes(term)))},[data,query,selectedTrainingId,versions]);
 return <section className="mt-6 space-y-5"><header><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[var(--brand-primary)]">Analítica de aprendizaje</p><h2 className="mt-1 text-2xl font-semibold">Resultados</h2><p className="mt-1 text-sm text-[var(--gaia-ink-500)]">Consolida finalizaciones, aprobaciones y calificaciones registradas por la API.</p></header>{error&&<p className="rounded-2xl bg-[#fff0f0] p-4 text-sm text-[#9a384d]">{error}</p>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Participantes" value={data?.participants??0} icon="users"/><Metric label="Finalizaciones" value={data?.completed??0}/><Metric label="Aprobadas" value={data?.approved??0}/><Metric label="No aprobadas" value={data?.notApproved??0}/><Metric label="Promedio" value={`${data?.averageResult??0}%`} icon="chart"/></div><div className="overflow-hidden rounded-3xl border border-[var(--gaia-line)] bg-white"><div className="border-b border-[var(--gaia-line)] p-4"><label className="flex max-w-xl items-center gap-2 rounded-xl border border-[var(--gaia-line)] px-3"><Search size={16}/><input className="w-full py-2 outline-none" onChange={e=>setQuery(e.target.value)} placeholder="Buscar en resultados" value={query}/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-[var(--gaia-accent-pale)] text-[10px] uppercase tracking-wide text-[var(--gaia-ink-500)]"><tr><th className="px-5 py-3">Participante</th><th className="px-4 py-3">Capacitación</th><th className="px-4 py-3">Resultado</th><th className="px-4 py-3">Condición</th><th className="px-4 py-3">Intentos</th><th className="px-4 py-3">Finalización</th></tr></thead><tbody>{rows.map(x=><tr className="border-t border-[var(--gaia-line)]" key={x.assignmentId}><td className="px-5 py-4"><strong>{x.participant}</strong><small className="block text-[var(--gaia-ink-500)]">{x.unit??"Sin unidad"}</small></td><td className="px-4 py-4">{x.training}<small className="block text-[var(--gaia-ink-500)]">Versión {x.version}</small></td><td className="px-4 py-4 font-bold">{x.result===null?"Pendiente":`${x.result}%`}</td><td className="px-4 py-4">{statusLabel(x.status)}</td><td className="px-4 py-4">{x.attempts}</td><td className="px-4 py-4">{date(x.completedAt)}</td></tr>)}{!rows.length&&<tr><td className="p-10 text-center text-[var(--gaia-ink-500)]" colSpan={6}>{data?"Todavía no hay resultados consolidados.":"Cargando resultados…"}</td></tr>}</tbody></table></div></div></section>
}

function Metric({label,value,icon}:{label:string;value:number|string;icon?:"users"|"chart"}){const Icon=icon==="users"?UsersRound:icon==="chart"?BarChart3:label==="Finalizadas"||label==="Aprobadas"?CheckCircle2:Clock3;return <article className="rounded-2xl border border-[var(--gaia-line)] bg-white p-4"><Icon className="text-[var(--brand-primary)]" size={18}/><strong className="mt-3 block text-2xl">{value}</strong><small className="text-[var(--gaia-ink-500)]">{label}</small></article>}
function Pager({page,pages,setPage}:{page:number;pages:number;setPage:(value:number)=>void}){return <footer className="flex items-center justify-between border-t border-[var(--gaia-line)] px-5 py-3 text-xs text-[var(--gaia-ink-500)]"><span>Página {page} de {pages}</span><div className="flex gap-2"><button className="rounded-lg border px-3 py-1 disabled:opacity-40" disabled={page<=1} onClick={()=>setPage(page-1)}>Anterior</button><button className="rounded-lg border px-3 py-1 disabled:opacity-40" disabled={page>=pages} onClick={()=>setPage(page+1)}>Siguiente</button></div></footer>}
