"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link2, Pencil, Plus, Search, UserCheck, UserRoundPlus, Users } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { FormDialog } from "@/components/form-dialog";
import { useFeedback } from "@/components/feedback";
import { useSecurity } from "@/components/security-context";
import { Button, IconButton } from "@/components/ui";
import { apiRequest } from "@/lib/api-client";
import { isAssignmentCurrent } from "@/features/organization/organizational-assignment-model";

type Person={id:string;fullName:string;documentNumber:string;isActive:boolean};
type Position={id:string;name:string;isActive:boolean};
type Unit={id:string;code:string;name:string;parentId?:string;level:number;isActive:boolean};
type Assignment={id:string;thirdPartyId:string;thirdPartyName:string;documentNumber:string;positionId:string;positionName:string;organizationalUnitId:string;organizationalUnitCode:string;organizationalUnitName:string;startDate?:string;endDate?:string;isPrimary:boolean;observations?:string;isActive:boolean};
type Form={thirdPartyId:string;positionId:string;organizationalUnitId:string;startDate:string;endDate:string;isPrimary:boolean;observations:string;isActive:boolean};
const emptyForm=():Form=>({thirdPartyId:"",positionId:"",organizationalUnitId:"",startDate:new Date().toISOString().slice(0,10),endDate:"",isPrimary:true,observations:"",isActive:true});

export function TalentOrganizationalAssignments({mode}:{mode:"query"|"manage"}) {
  const [people,setPeople]=useState<Person[]>([]),[positions,setPositions]=useState<Position[]>([]),[units,setUnits]=useState<Unit[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]);
  const [search,setSearch]=useState(""),[showHistory,setShowHistory]=useState(false),[pendingOnly,setPendingOnly]=useState(mode==="manage");
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false),[editor,setEditor]=useState<Assignment|null|undefined>(undefined),[form,setForm]=useState<Form>(emptyForm());
  const {notify}=useFeedback();const {can}=useSecurity();const canCreate=mode==="manage"&&can("TH.VINCULACIONES.CREAR");const canUpdate=mode==="manage"&&can("TH.VINCULACIONES.ACTUALIZAR");
  async function load(){setLoading(true);setError("");try{const [directory,positionRows,unitRows,assignmentRows]=await Promise.all([apiRequest<Person[]>("/api/third-parties?directory=true"),apiRequest<Position[]>("/api/organization/positions"),apiRequest<Unit[]>("/api/organization/units"),apiRequest<Assignment[]>("/api/third-parties/organizational-assignments")]);setPeople(directory);setPositions(positionRows);setUnits(unitRows);setAssignments(assignmentRows);}catch(caught){setError(caught instanceof Error?caught.message:"No fue posible cargar las vinculaciones.");}finally{setLoading(false);}}
  useEffect(()=>{let active=true;Promise.all([apiRequest<Person[]>("/api/third-parties?directory=true"),apiRequest<Position[]>("/api/organization/positions"),apiRequest<Unit[]>("/api/organization/units"),apiRequest<Assignment[]>("/api/third-parties/organizational-assignments")]).then(([directory,positionRows,unitRows,assignmentRows])=>{if(!active)return;setPeople(directory);setPositions(positionRows);setUnits(unitRows);setAssignments(assignmentRows);setLoading(false);}).catch(caught=>{if(!active)return;setError(caught instanceof Error?caught.message:"No fue posible cargar las vinculaciones.");setLoading(false);});return()=>{active=false;};},[]);
  const currentPersonIds=useMemo(()=>new Set(assignments.filter(row=>isAssignmentCurrent(row)).map(row=>row.thirdPartyId)),[assignments]);
  const pending=useMemo(()=>people.filter(person=>person.isActive&&!currentPersonIds.has(person.id)).sort((a,b)=>a.fullName.localeCompare(b.fullName,"es")),[currentPersonIds,people]);
  const visible=useMemo(()=>{const q=normalize(search);return assignments.filter(row=>(showHistory||isAssignmentCurrent(row))&&(!q||matches(`${row.thirdPartyName} ${row.positionName} ${row.organizationalUnitName} ${row.organizationalUnitCode}`,q))).sort((a,b)=>a.thirdPartyName.localeCompare(b.thirdPartyName,"es"));},[assignments,search,showHistory]);
  function openEditor(item?:Assignment,personId=""){setEditor(item??null);setForm(item?{thirdPartyId:item.thirdPartyId,positionId:item.positionId,organizationalUnitId:item.organizationalUnitId,startDate:item.startDate??"",endDate:item.endDate??"",isPrimary:item.isPrimary,observations:item.observations??"",isActive:item.isActive}:{...emptyForm(),thirdPartyId:personId});}
  async function save(event:FormEvent){event.preventDefault();if(saving)return;setSaving(true);setError("");try{await apiRequest(editor?.id?`/api/third-parties/organizational-assignments/${editor.id}`:"/api/third-parties/organizational-assignments",{method:editor?.id?"PUT":"POST",body:JSON.stringify({...form,startDate:form.startDate||null,endDate:form.endDate||null})});setEditor(undefined);await load();notify({tone:"success",title:editor?.id?"Vinculación actualizada":"Vinculación creada"});}catch(caught){setError(caught instanceof Error?caught.message:"No fue posible guardar.");}finally{setSaving(false);}}
  return <main className="gaia-app-page min-h-screen bg-[#f2f5f0] text-[#193522]"><AppHeader title={mode==="manage"?"Talento Humano · Vinculaciones":"Talento Humano · Asignación organizacional"}/><div className="mx-auto max-w-[1450px] px-5 py-8 lg:px-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#66804e]">Talento Humano</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{mode==="manage"?"Vinculaciones":"Asignación organizacional"}</h1><p className="mt-2 max-w-2xl text-sm text-[#65766d]">{mode==="manage"?"Administra la ubicación de cada colaborador dentro de la estructura organizacional.":"Consulta las asignaciones actuales e históricas de los colaboradores."}</p></div>{canCreate&&<Button onClick={()=>openEditor()}><Plus size={16}/>Nueva vinculación</Button>}</header>
    {error&&<p className="mt-5 rounded-xl bg-[#fff0eb] px-4 py-3 text-sm text-[#8a3f25]">{error}</p>}
    {mode==="manage"&&<section className="mt-6 grid gap-3 sm:grid-cols-3"><Metric icon={Users} label="Colaboradores activos" value={people.filter(x=>x.isActive).length}/><Metric icon={UserCheck} label="Con asignación actual" value={currentPersonIds.size}/><Metric icon={UserRoundPlus} label="Pendientes por vincular" value={pending.length}/></section>}
    <section className="mt-6 rounded-3xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="gaia-tabs" role="tablist">{mode==="manage"&&<button aria-selected={pendingOnly} className="gaia-tab" onClick={()=>setPendingOnly(true)} role="tab" type="button">Pendientes ({pending.length})</button>}<button aria-selected={!pendingOnly} className="gaia-tab" onClick={()=>setPendingOnly(false)} role="tab" type="button">{mode==="manage"?"Asignados":"Listado"}</button></div>{!pendingOnly&&<label className="flex items-center gap-2 text-xs font-semibold text-[#52685e]"><input checked={showHistory} onChange={e=>setShowHistory(e.target.checked)} type="checkbox"/>Incluir históricos</label>}</div>
      <div className="relative mt-4 max-w-lg"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#7a887f]" size={16}/><input className="h-11 w-full rounded-xl border border-[#d6dfd3] pl-10 pr-4 text-sm outline-none focus:border-[#66804e]" onChange={e=>setSearch(e.target.value)} placeholder={pendingOnly?"Buscar colaborador pendiente":"Buscar colaborador, cargo o unidad"} value={search}/></div>
      {loading?<Empty text="Cargando información…"/>:pendingOnly?<PendingList canManage={canCreate} onAssign={person=>openEditor(undefined,person.id)} people={pending.filter(person=>!search||matches(`${person.fullName} ${person.documentNumber}`,normalize(search)))}/>:<AssignmentsTable assignments={visible} canManage={canUpdate} onEdit={openEditor}/>}
    </section>
  </div>{editor!==undefined&&<FormDialog error={error} formId="link-form" loading={saving} onClose={()=>setEditor(undefined)} open submitLabel={editor?.id?"Actualizar":"Crear vinculación"} subtitle="Colaborador, cargo y unidad organizacional" title={editor?.id?"Editar vinculación":"Nueva vinculación"}><form className="space-y-4" id="link-form" onSubmit={save}><Field label="Colaborador"><select disabled={Boolean(editor?.id)} required value={form.thirdPartyId} onChange={e=>setForm({...form,thirdPartyId:e.target.value})}><option value="">Seleccionar colaborador</option>{people.filter(x=>x.isActive).sort((a,b)=>a.fullName.localeCompare(b.fullName,"es")).map(x=><option key={x.id} value={x.id}>{x.fullName}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Cargo"><select required value={form.positionId} onChange={e=>setForm({...form,positionId:e.target.value})}><option value="">Seleccionar cargo</option>{positions.filter(x=>x.isActive).sort((a,b)=>a.name.localeCompare(b.name,"es")).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Unidad"><select required value={form.organizationalUnitId} onChange={e=>setForm({...form,organizationalUnitId:e.target.value})}><option value="">Seleccionar unidad</option>{units.filter(x=>x.isActive).sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name,"es")).map(x=><option key={x.id} value={x.id}>{x.name} [{x.code}]</option>)}</select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Desde"><input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></Field><Field label="Hasta"><input min={form.startDate||undefined} type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></Field></div><Field label="Observaciones"><textarea rows={3} value={form.observations} onChange={e=>setForm({...form,observations:e.target.value})}/></Field><label className="flex items-center gap-2 rounded-xl bg-[#f4f7f2] p-3 text-sm font-semibold"><input checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})} type="checkbox"/>Vinculación activa</label></form></FormDialog>}</main>;
}

function PendingList({people,canManage,onAssign}:{people:Person[];canManage:boolean;onAssign:(person:Person)=>void}){return <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{people.map(person=><article className="flex items-center gap-3 rounded-2xl border border-[#e0e8dd] p-4" key={person.id}><span className="grid size-10 place-items-center rounded-full bg-[#edf2e9] text-xs font-bold text-[#315b42]">{initials(person.fullName)}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{person.fullName}</strong><small className="text-[#78867d]">Sin asignación organizacional actual</small></div>{canManage&&<Button onClick={()=>onAssign(person)} variant="secondary"><Link2 size={14}/>Vincular</Button>}</article>)}{!people.length&&<Empty text="No hay colaboradores pendientes por vincular."/>}</div>}
function AssignmentsTable({assignments,canManage,onEdit}:{assignments:Assignment[];canManage:boolean;onEdit:(item:Assignment)=>void}){return <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b border-[#dfe7dc] text-[10px] uppercase tracking-wider text-[#748279]"><tr><th className="px-3 py-3">Colaborador</th><th className="px-3 py-3">Cargo</th><th className="px-3 py-3">Unidad</th><th className="px-3 py-3">Desde</th><th className="px-3 py-3">Hasta</th><th className="px-3 py-3">Estado</th><th/></tr></thead><tbody>{assignments.map(item=><tr className={`border-b border-[#e9eee7] ${item.isActive?"":"bg-[#fafafa] text-[#78867d]"}`} key={item.id}><td className="px-3 py-4 font-semibold">{item.thirdPartyName}</td><td className="px-3 py-4">{item.positionName}</td><td className="px-3 py-4"><strong>{item.organizationalUnitName}</strong><small className="block text-[#7a887f]">{item.organizationalUnitCode}</small></td><td className="px-3 py-4">{date(item.startDate)}</td><td className="px-3 py-4">{date(item.endDate)}</td><td className="px-3 py-4"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${isAssignmentCurrent(item)?"bg-[#e5f1e1] text-[#2f643d]":"bg-[#eef0ee] text-[#69766f]"}`}>{isAssignmentCurrent(item)?"Actual":"Histórica"}</span></td><td className="px-3 py-4">{canManage&&<IconButton label={`Editar vinculación de ${item.thirdPartyName}`} onClick={()=>onEdit(item)}><Pencil size={15}/></IconButton>}</td></tr>)}</tbody></table>{!assignments.length&&<Empty text="No se encontraron asignaciones."/>}</div>}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:number}){return <article className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-sm"><span className="grid size-11 place-items-center rounded-xl bg-[#eaf1e7] text-[#386037]"><Icon size={19}/></span><div><strong className="text-2xl">{value}</strong><p className="text-[10px] uppercase tracking-wide text-[#75837a]">{label}</p></div></article>}
function Field({label,children}:{label:string;children:React.ReactElement}){return <label className="block text-sm font-semibold">{label}<span className="mt-2 block [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-[#d3ddd0] [&>*]:bg-white [&>*]:px-4 [&>*]:py-3 [&>*]:font-normal">{children}</span></label>}
function Empty({text}:{text:string}){return <div className="col-span-full grid min-h-40 place-items-center text-sm text-[#77857b]">{text}</div>}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("es").trim()}function matches(value:string,query:string){const source=normalize(value);return query.split(/\s+/).filter(Boolean).every(token=>source.includes(token))}function initials(value:string){return value.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()}function date(value?:string){return value?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T00:00:00Z`)):"Sin fecha"}
