"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

const apiUrl = process.env.NEXT_PUBLIC_GAIA_API_URL ?? "https://localhost:7168";
type Dashboard = { products: number; items: number; available: number; assigned: number; issues: number };
type Item = { id: string; assetCode: string; product: string; productCode: string; brand?: string; model?: string; serialNumber?: string; condition: string; status: string; costCenter?: string; funder?: string };
type Product = { id: string; code: string; className: string; subcategory: string; name: string; controlLevel: string };
type Assignment = { id: string; assetCode: string; product: string; custodianName: string; thirdPartyDocument?: string; organizationalUnitCode?: string; actNumber?: string };
type Issue = { id: string; sourceRow: number; code: string; message: string };
type Tab = "items" | "products" | "assignments" | "movements" | "issues";

async function api<T>(path: string): Promise<T> { const response = await fetch(`${apiUrl}${path}`, { credentials: "include" }); if (response.status === 401) { window.location.href = "/"; throw new Error("Sesión finalizada"); } if (!response.ok) throw new Error("No fue posible cargar inventarios"); return response.json() as Promise<T>; }

export default function InventoryPage() {
  const [dashboard, setDashboard] = useState<Dashboard>({ products: 0, items: 0, available: 0, assigned: 0, issues: 0 });
  const [items, setItems] = useState<Item[]>([]); const [products, setProducts] = useState<Product[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]); const [issues, setIssues] = useState<Issue[]>([]);
  const [tab, setTab] = useState<Tab>("items"); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Item | null>(null); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api<Dashboard>("/api/inventory/dashboard"), api<Item[]>("/api/inventory/items"), api<Product[]>("/api/inventory/products"), api<Assignment[]>("/api/inventory/assignments"), api<Issue[]>("/api/inventory/import-issues")]).then(([d, i, p, a, e]) => { setDashboard(d); setItems(i); setProducts(p); setAssignments(a); setIssues(e); setSelected(i[0] ?? null); }).catch(e => setError(String(e))); }, []);
  const visible = useMemo(() => { const q = search.toLocaleLowerCase("es").trim(); return q ? items.filter(x => [x.assetCode, x.product, x.brand, x.serialNumber].some(v => v?.toLocaleLowerCase("es").includes(q))) : items; }, [items, search]);
  const tabs: Array<[Tab, string, number]> = [["items", "Elementos", dashboard.items], ["products", "Productos", dashboard.products], ["assignments", "Asignaciones", dashboard.assigned], ["movements", "Movimientos", 0], ["issues", "Incidencias", dashboard.issues]];
  return <main className="min-h-screen bg-[#eef3eb] text-[#193522]">
    <header className="bg-[#173f2b] text-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-3.5"><div className="flex items-center gap-3"><Link className="grid size-10 place-items-center rounded-xl bg-[#dce9d5] text-lg font-black text-[#21472f]" href="/">G</Link><div><p className="text-[10px] font-bold uppercase tracking-[.24em] text-[#aac49e]">Gaia Enterprise</p><h1 className="text-lg font-semibold">Gestión de inventarios</h1></div></div><nav className="flex gap-5 text-sm font-semibold text-[#d7e6d1]"><Link href="/organizacion">Organización</Link><Link href="/terceros">Terceros</Link><Link href="/">Inicio</Link></nav></div><div className="h-1 bg-gradient-to-r from-[#a0384d] via-[#3c838c] to-[#386037]" /></header>
    <div className="mx-auto max-w-[1500px] px-4 py-4"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Elementos", dashboard.items, "#294f35"], ["Disponibles", dashboard.available, "#3c838c"], ["Asignados", dashboard.assigned, "#a0384d"], ["Productos", dashboard.products, "#6f3873"], ["Por revisar", dashboard.issues, "#b76d49"]].map(([label, value, color]) => <article className="rounded-2xl bg-white px-4 py-3 shadow-sm" key={String(label)}><div className="flex items-center gap-3"><span className="h-9 w-1 rounded-full" style={{ background: String(color) }} /><div><p className="text-[10px] font-bold uppercase tracking-widest text-[#78867c]">{label}</p><p className="text-2xl font-semibold">{value}</p></div></div></article>)}</section>
      <section className="mt-4 overflow-hidden rounded-2xl bg-white shadow-sm"><nav className="flex overflow-x-auto border-b border-[#e4ebe1] px-3">{tabs.map(([value, label, count]) => <button className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab === value ? "border-[#386037] text-[#294f35]" : "border-transparent text-[#758179]"}`} key={value} onClick={() => setTab(value)}>{label}<span className="ml-2 rounded-full bg-[#edf2ea] px-2 py-0.5 text-[10px]">{count}</span></button>)}</nav><div className="p-4">
        {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}
        {tab === "items" && <div className="grid gap-4 lg:grid-cols-[1.45fr_.75fr]"><div><div className="mb-3 flex"><input className="w-full max-w-md rounded-xl border border-[#d7e1d4] bg-[#f8faf7] px-3 py-2 text-sm outline-none" onChange={e => setSearch(e.target.value)} placeholder="Buscar código, elemento, marca o serial" value={search} /><button className="ml-3 rounded-xl bg-[#294f35] px-4 py-2 text-sm font-semibold text-white">+ Nuevo</button></div><Table headers={["Código", "Elemento", "Marca / modelo", "Estado"]} rows={visible.map(x => [x.assetCode, x.product, `${x.brand ?? "—"} ${x.model ?? ""}`, x.status])} onRow={i => setSelected(visible[i])} /></div><aside className="rounded-2xl bg-[#f5f8f3] p-4">{selected ? <><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#66804e]">Ficha del elemento</p><h2 className="mt-1 text-xl font-semibold">{selected.product}</h2><p className="mt-1 text-sm text-[#748178]">Activo {selected.assetCode}</p><dl className="mt-5 space-y-3">{[["Marca", selected.brand], ["Modelo", selected.model], ["Serial", selected.serialNumber], ["Estado físico", selected.condition], ["Centro de costos", selected.costCenter], ["Financiador", selected.funder]].map(([k, v]) => <div className="border-b border-[#dfe7dc] pb-2" key={k}><dt className="text-[10px] font-bold uppercase tracking-wider text-[#829087]">{k}</dt><dd className="mt-1 text-sm font-semibold">{v || "Sin información"}</dd></div>)}</dl></> : <p className="text-sm text-[#78857d]">Selecciona un elemento.</p>}</aside></div>}
        {tab === "products" && <Table headers={["Código", "Clase", "Subcategoría", "Producto", "Control"]} rows={products.map(x => [x.code, x.className, x.subcategory, x.name, x.controlLevel])} />}
        {tab === "assignments" && <Table headers={["Elemento", "Producto", "Custodio", "Documento", "Área", "Acta"]} rows={assignments.map(x => [x.assetCode, x.product, x.custodianName, x.thirdPartyDocument, x.organizationalUnitCode, x.actNumber])} />}
        {tab === "movements" && <Empty text="El historial inmutable se alimenta con cada asignación, devolución o traslado." />}
        {tab === "issues" && (issues.length ? <Table headers={["Fila", "Código", "Detalle"]} rows={issues.map(x => [x.sourceRow, x.code, x.message])} /> : <Empty text="No hay incidencias de importación." />)}
      </div></section></div>
  </main>;
}
function Table({ headers, rows, onRow }: { headers: string[]; rows: Array<Array<unknown>>; onRow?: (index: number) => void }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f3f6f1] text-[10px] uppercase tracking-wider text-[#718077]"><tr>{headers.map(h => <th className="px-3 py-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr className="cursor-pointer border-b border-[#edf1eb] hover:bg-[#f7f9f6]" key={i} onClick={() => onRow?.(i)}>{row.map((v, j) => <td className="px-3 py-2.5" key={j}>{String(v ?? "—")}</td>)}</tr>)}</tbody></table></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-[#cfdacb] py-14 text-center text-sm text-[#7b887f]">{text}</div>; }
