"use client";

import { useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, FileSpreadsheet, LoaderCircle, Upload } from "lucide-react";
import { apiRequest } from "@/lib/api-client";
import { useFeedback } from "./feedback";
import { ConfirmDialog } from "./form-dialog";
import { Badge, Button, EmptyState, PageHeader } from "./ui";

type Issue = { row:number; sheet:string; code:string; detail:string; severity:"error"|"warning" };
type Plan = { toCreate:number; existing:number; toUpdate:number; omitted:number; errors:number };
type Validation = { valid:boolean; sheetRows:Record<string,number>; collaborators:number; jobs:number; institutionalEmails:number; personalEmails:number; personalPhones:number; corporatePhones:number; withoutEmail:number; withoutPhone:number; issues:Issue[]; collaboratorPlan?:Plan; jobPlan?:Plan; emailPlan?:Plan; phonePlan?:Plan };
type ImportResult = { collaboratorsCreated:number; collaboratorsExisting:number; collaboratorsUpdated:number; collaboratorsErrors:number; jobsCreated:number; jobsExisting:number; jobsUpdated:number; jobsErrors:number; emailsCreated:number; emailsExisting:number; emailsUpdated:number; emailsOmitted:number; emailsErrors:number; phonesCreated:number; phonesExisting:number; phonesUpdated:number; phonesOmitted:number; phonesErrors:number; skipped:number };

export function PersonnelImportPanel({onClose}:{onClose:()=>void}) {
  const inputRef=useRef<HTMLInputElement>(null), {notify}=useFeedback();
  const [file,setFile]=useState<File|null>(null),[validatedSignature,setValidatedSignature]=useState<string|null>(null),[validation,setValidation]=useState<Validation|null>(null);
  const [validating,setValidating]=useState(false),[confirmOpen,setConfirmOpen]=useState(false),[importing,setImporting]=useState(false);
  const [result,setResult]=useState<ImportResult|null>(null);
  const signature=file?`${file.name}:${file.size}:${file.lastModified}`:null;
  const issues=validation?.issues??[], errors=issues.filter(x=>x.severity==="error"), warnings=issues.filter(x=>x.severity==="warning");
  const canImport=Boolean(file&&validation?.valid&&signature===validatedSignature&&!validating&&!importing);
  const cards=useMemo(()=>validation?[["Colaboradores",validation.collaborators],["Cargos",validation.jobs],["Correos institucionales",validation.institutionalEmails],["Correos personales",validation.personalEmails],["Celulares personales",validation.personalPhones],["Celulares corporativos",validation.corporatePhones],["Sin correo",validation.withoutEmail],["Sin teléfono",validation.withoutPhone]]:[],[validation]);
  function select(next:File|null){setFile(next);setValidation(null);setValidatedSignature(null);setResult(null);}
  async function validate(){if(!file)return;setValidating(true);try{const body=new FormData();body.append("file",file);const result=await apiRequest<Validation>("/api/third-parties/administrative-import/validate",{method:"POST",body});setValidation(result);setValidatedSignature(signature);notify({tone:result.valid?"success":"error",title:result.valid?"Archivo apto para importar":"El archivo tiene errores",description:result.valid?"El dry-run terminó sin errores bloqueantes.":"Revisa las incidencias antes de continuar."});}catch(error){notify({tone:"error",title:"No fue posible validar",description:error instanceof Error?error.message:undefined});}finally{setValidating(false);}}
  async function execute(){if(!file||!canImport)return;setImporting(true);try{const body=new FormData();body.append("file",file);const completed=await apiRequest<ImportResult>("/api/third-parties/administrative-import/execute?confirm=true",{method:"POST",body});setResult(completed);setConfirmOpen(false);setValidation(null);setValidatedSignature(null);notify({tone:"success",title:"Importación finalizada",description:`${completed.collaboratorsCreated} colaboradores, ${completed.jobsCreated} cargos, ${completed.emailsCreated} correos y ${completed.phonesCreated} teléfonos creados.`,persistent:true});}catch(error){notify({tone:"error",title:"La importación no finalizó",description:error instanceof Error?error.message:undefined,persistent:true});}finally{setImporting(false);}}
  return <section className="rounded-2xl bg-white p-5 shadow-sm"><PageHeader eyebrow="Talento Humano · Administración" title="Carga controlada de colaboradores" description="Valida el libro completo antes de autorizar cualquier escritura en Dataverse." actions={<Button onClick={onClose} variant="secondary">Volver a colaboradores</Button>}/>
    <div className="mt-6 rounded-2xl border border-dashed border-[#aebfa9] bg-[#f7faf5] p-5"><div className="flex flex-wrap items-center gap-4"><span className="grid size-12 place-items-center rounded-xl bg-[#e4eee0] text-[#386037]"><FileSpreadsheet size={23}/></span><div className="min-w-0 flex-1"><strong className="block text-sm">Archivo esperado: PERSONAL ACTIVO 2026.xlsx</strong><span className="mt-1 block truncate text-xs text-[#718077]">{file?`${file.name} · ${(file.size/1024).toFixed(1)} KB`:"Selecciónalo desde Descargas. El navegador no permite preseleccionar archivos locales."}</span></div><input accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="sr-only" onChange={event=>select(event.target.files?.[0]??null)} ref={inputRef} type="file"/><Button onClick={()=>inputRef.current?.click()} variant="secondary"><Upload size={16}/>{file?"Cambiar archivo":"Seleccionar Excel"}</Button><Button disabled={!file||validating||importing} onClick={()=>void validate()}>{validating?<LoaderCircle className="gaia-spin" size={16}/>:<CheckCircle2 size={16}/>}Validar archivo</Button></div></div>
    {result&&<ExecutionSummary result={result}/>} {validation?<><div className={`mt-5 flex items-start gap-3 rounded-xl p-4 ${validation.valid?"bg-[#e9f3e5] text-[#294f35]":"bg-[#f9e9e7] text-[#8c302c]"}`}>{validation.valid?<CheckCircle2 size={21}/>:<AlertTriangle size={21}/>}<div><strong>{validation.valid?"Archivo apto para importar":"Archivo no apto para importar"}</strong><p className="mt-1 text-sm">{validation.valid?"No hay errores bloqueantes. Revisa el plan y las advertencias.":`${errors.length} incidencia(s) deben corregirse.`}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><div className="rounded-xl border border-[#e1e9de] p-4" key={label}><span className="text-[10px] font-bold uppercase tracking-wider text-[#7b897f]">{label}</span><strong className="mt-2 block text-2xl text-[#294f35]">{value}</strong></div>)}</div>{validation.collaboratorPlan&&<div className="mt-6 grid gap-4 xl:grid-cols-2"><PlanCard plan={validation.collaboratorPlan} title="Colaboradores"/><PlanCard plan={validation.jobPlan!} title="Cargos"/><PlanCard plan={validation.emailPlan!} title="Correos"/><PlanCard plan={validation.phonePlan!} title="Teléfonos"/></div>}<div className="mt-6 grid gap-5 xl:grid-cols-2"><IssueList empty="No se encontraron errores bloqueantes." issues={errors} title="Incidencias"/><IssueList empty="No se encontraron advertencias." issues={warnings} title="Advertencias"/></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[#e4ebe1] pt-5"><p className="max-w-2xl text-xs leading-5 text-[#718077]">Cambiar el archivo invalida automáticamente la validación. La ejecución requiere una confirmación adicional.</p><Button disabled={!canImport} onClick={()=>setConfirmOpen(true)}>Ejecutar importación</Button></div></>:!result&&<div className="mt-6"><EmptyState title="Aún no hay resultado de validación" description="Selecciona el Excel y ejecuta Validar archivo. Esta acción no modifica Dataverse."/></div>}
    <ConfirmDialog confirmLabel="Sí, ejecutar importación" description="Se crearán en Dataverse los colaboradores, cargos, correos y teléfonos inexistentes. No incluye asignaciones ni dependencias." loading={importing} onCancel={()=>setConfirmOpen(false)} onConfirm={()=>void execute()} open={confirmOpen} title="¿Confirmas la carga administrativa?"/></section>;
}
function IssueList({title,issues,empty}:{title:string;issues:Issue[];empty:string}){return <section><div className="flex items-center justify-between"><h3 className="font-semibold">{title}</h3><Badge tone={issues.length?title==="Incidencias"?"danger":"warning":"success"}>{issues.length}</Badge></div><div className="mt-3 max-h-64 overflow-y-auto rounded-xl border border-[#e1e9de]">{issues.length?issues.map((issue,index)=><article className="border-b border-[#edf1eb] p-3 last:border-0" key={`${issue.sheet}-${issue.row}-${issue.code}-${index}`}><div className="flex flex-wrap gap-2 text-[10px] font-bold uppercase tracking-wider text-[#718077]"><span>{issue.sheet}</span>{issue.row>0&&<span>Fila {issue.row}</span>}<span>{issue.code}</span></div><p className="mt-1 text-sm">{issue.detail}</p></article>):<p className="p-4 text-sm text-[#718077]">{empty}</p>}</div></section>}
function PlanCard({title,plan}:{title:string;plan:Plan}){return <article className="rounded-xl border border-[#dce6d9] p-4"><h3 className="font-semibold">{title}</h3><div className="mt-3 grid grid-cols-5 gap-2 text-center">{[["Crear",plan.toCreate],["Existentes",plan.existing],["Actualizar",plan.toUpdate],["Omitidos",plan.omitted],["Errores",plan.errors]].map(([label,value])=><div key={label}><strong className="block text-lg text-[#294f35]">{value}</strong><span className="text-[9px] uppercase text-[#718077]">{label}</span></div>)}</div></article>}
function ExecutionSummary({result}:{result:ImportResult}){return <section className="mt-5 rounded-xl bg-[#e9f3e5] p-5"><div className="flex items-center gap-2 text-[#294f35]"><CheckCircle2 size={21}/><h3 className="font-semibold">Resultado de la ejecución</h3></div><div className="mt-4 grid gap-3 xl:grid-cols-2"><PlanCard title="Colaboradores" plan={{toCreate:result.collaboratorsCreated,existing:result.collaboratorsExisting,toUpdate:result.collaboratorsUpdated,omitted:result.skipped,errors:result.collaboratorsErrors}}/><PlanCard title="Cargos" plan={{toCreate:result.jobsCreated,existing:result.jobsExisting,toUpdate:result.jobsUpdated,omitted:0,errors:result.jobsErrors}}/><PlanCard title="Correos" plan={{toCreate:result.emailsCreated,existing:result.emailsExisting,toUpdate:result.emailsUpdated,omitted:result.emailsOmitted,errors:result.emailsErrors}}/><PlanCard title="Teléfonos" plan={{toCreate:result.phonesCreated,existing:result.phonesExisting,toUpdate:result.phonesUpdated,omitted:result.phonesOmitted,errors:result.phonesErrors}}/></div></section>}
