using Gaia.Modules.Security;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Builder;
namespace Gaia.Modules.Communications;
public static class CommunicationsModule
{
 private static readonly System.Text.Json.JsonSerializerOptions WebJson = new(System.Text.Json.JsonSerializerDefaults.Web);
 public static IEndpointRouteBuilder MapCommunicationsEndpoints(this IEndpointRouteBuilder endpoints){
  var admin=endpoints.MapGroup("/api/communications").WithTags("Communications").RequireAuthorization();
  admin.MapGet("/event-types",(bool includeInactive,ICommunicationsStore s,CancellationToken ct)=>s.ListEventTypesAsync(includeInactive,ct)).RequireAuthorization(AdminCorePermissions.ComEventTypesRead);
  admin.MapPost("/event-types",(EventTypeWriteRequest r,ICommunicationsStore s,CancellationToken ct)=>Safe(()=>s.SaveEventTypeAsync(null,r,ct))).RequireAuthorization(AdminCorePermissions.ComEventTypesManage);
  admin.MapPut("/event-types/{id:guid}",(Guid id,EventTypeWriteRequest r,ICommunicationsStore s,CancellationToken ct)=>Safe(()=>s.SaveEventTypeAsync(id,r,ct))).RequireAuthorization(AdminCorePermissions.ComEventTypesManage);
  admin.MapGet("/events",(bool includeInactive,ICommunicationsStore s,CancellationToken ct)=>s.ListEventsAsync(includeInactive,ct)).RequireAuthorization(AdminCorePermissions.ComEventsRead);
  admin.MapPost("/events",(EventWriteRequest r,ICommunicationsStore s,CancellationToken ct)=>Safe(()=>s.SaveEventAsync(null,r,ct))).RequireAuthorization(AdminCorePermissions.ComEventsCreate);
  admin.MapPut("/events/{id:guid}",(Guid id,EventWriteRequest r,ICommunicationsStore s,CancellationToken ct)=>Safe(()=>s.SaveEventAsync(id,r,ct))).RequireAuthorization(AdminCorePermissions.ComEventsEdit);
  foreach(var action in new[]{"publish","cancel","finish","deactivate","restore"}){var captured=action;admin.MapPost($"/events/{{id:guid}}/{action}",(Guid id,ICommunicationsStore s,CancellationToken ct)=>Safe(()=>s.ChangeEventStateAsync(id,captured,ct))).RequireAuthorization(AdminCorePermissions.ComEventsState);}
  admin.MapGet("/highlights",(bool includeInactive,Guid? eventId,ICommunicationsStore s,CancellationToken ct)=>s.ListBannersAsync(includeInactive,eventId,ct)).RequireAuthorization(AdminCorePermissions.ComBannersRead);
  admin.MapPost("/highlights",(BannerWriteRequest r,ICommunicationsStore s,CancellationToken ct)=>Safe(()=>s.SaveBannerAsync(null,r,ct))).RequireAuthorization(AdminCorePermissions.ComBannersCreate);
  admin.MapPut("/highlights/{id:guid}",(Guid id,BannerWriteRequest r,ICommunicationsStore s,CancellationToken ct)=>Safe(()=>s.SaveBannerAsync(id,r,ct))).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  foreach(var action in new[]{"design","publish","close","reject","deactivate","restore"}){var captured=action;admin.MapPost($"/highlights/{{id:guid}}/{action}",(Guid id,BannerStateRequest? r,ICommunicationsStore s,CancellationToken ct)=>Safe(()=>s.ChangeBannerStateAsync(id,captured,r?.Reason,ct))).RequireAuthorization(AdminCorePermissions.ComBannersState);}
  admin.MapPut("/highlights/{id:guid}/images/{variant}",UploadImage).DisableAntiforgery().RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapDelete("/highlights/{id:guid}/images/{variant}",async(Guid id,string variant,ICommunicationsStore s,CancellationToken ct)=>{if(variant is not("desktop" or "mobile"))return Results.ValidationProblem(new Dictionary<string,string[]>{{"image",["La variante debe ser desktop o mobile."]}});await s.DeleteBannerImageAsync(id,variant,ct);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapDelete("/highlights/{id:guid}",async(Guid id,ICommunicationsStore s,CancellationToken ct)=>{await s.DeleteBannerAsync(id,ct);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.ComBannersDelete);
  admin.MapGet("/login-configurations",(ILoginConfigurationStore s,CancellationToken ct)=>s.ListAsync(ct)).RequireAuthorization(AdminCorePermissions.ComBannersRead);
  admin.MapPost("/login-configurations",CreateLoginConfiguration).DisableAntiforgery().RequireAuthorization(AdminCorePermissions.ComBannersCreate);
  admin.MapPut("/login-configurations/{id:guid}",(Guid id,LoginConfigurationWriteRequest r,ILoginConfigurationStore s,CancellationToken ct)=>Safe(()=>s.SaveAsync(id,r,ct))).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapPost("/login-configurations/{id:guid}/publish",(Guid id,ILoginConfigurationStore s,CancellationToken ct)=>Safe(()=>s.PublishAsync(id,ct))).RequireAuthorization(AdminCorePermissions.ComBannersState);
  admin.MapPost("/login-configurations/{id:guid}/retire",(Guid id,ILoginConfigurationStore s,CancellationToken ct)=>Safe(()=>s.RetireAsync(id,ct))).RequireAuthorization(AdminCorePermissions.ComBannersState);
  admin.MapPut("/login-configurations/{id:guid}/images/{variant}",UploadLoginImage).DisableAntiforgery().RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapGet("/login-configurations/{id:guid}/images/{variant}",GetLoginImage).RequireAuthorization(AdminCorePermissions.ComBannersRead);
  admin.MapDelete("/login-configurations/{id:guid}/images/{variant}",async(Guid id,string variant,ILoginConfigurationStore s,CancellationToken ct)=>{if(variant is not("tablet" or "mobile"))return Results.ValidationProblem(new Dictionary<string,string[]>{{"image",["La imagen de escritorio es obligatoria y sólo puede reemplazarse."]}});await s.DeleteImageAsync(id,variant,ct);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapPost("/login-configurations/{configurationId:guid}/socials",(Guid configurationId,LoginSocialWriteRequest r,ILoginConfigurationStore s,CancellationToken ct)=>Safe(()=>s.SaveSocialAsync(configurationId,null,r,ct))).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapPut("/login-configurations/{configurationId:guid}/socials/{id:guid}",(Guid configurationId,Guid id,LoginSocialWriteRequest r,ILoginConfigurationStore s,CancellationToken ct)=>Safe(()=>s.SaveSocialAsync(configurationId,id,r,ct))).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapDelete("/login-configurations/{configurationId:guid}/socials/{id:guid}",async(Guid configurationId,Guid id,ILoginConfigurationStore s,CancellationToken ct)=>{await s.DeleteSocialAsync(configurationId,id,ct);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapGet("/visual-ambiences",(IVisualAmbienceStore s,CancellationToken ct)=>s.ListAsync(ct)).RequireAuthorization(AdminCorePermissions.ComBannersRead);
  admin.MapPost("/visual-ambiences",(VisualAmbienceWriteRequest r,IVisualAmbienceStore s,CancellationToken ct)=>Safe(()=>s.SaveAsync(null,r,ct))).RequireAuthorization(AdminCorePermissions.ComBannersCreate);
  admin.MapPut("/visual-ambiences/{id:guid}",(Guid id,VisualAmbienceWriteRequest r,IVisualAmbienceStore s,CancellationToken ct)=>Safe(()=>s.SaveAsync(id,r,ct))).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapPost("/visual-ambiences/{id:guid}/publish",(Guid id,IVisualAmbienceStore s,CancellationToken ct)=>Safe(()=>s.PublishAsync(id,ct))).RequireAuthorization(AdminCorePermissions.ComBannersState);
  admin.MapPost("/visual-ambiences/{id:guid}/retire",(Guid id,IVisualAmbienceStore s,CancellationToken ct)=>Safe(()=>s.RetireAsync(id,ct))).RequireAuthorization(AdminCorePermissions.ComBannersState);
  admin.MapPut("/visual-ambiences/{id:guid}/images/{variant}",UploadVisualAmbienceImage).DisableAntiforgery().RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapGet("/visual-ambiences/{id:guid}/images/{variant}",GetVisualAmbienceImage).RequireAuthorization();
  admin.MapDelete("/visual-ambiences/{id:guid}/images/{variant}",async(Guid id,string variant,IVisualAmbienceStore s,CancellationToken ct)=>{if(variant is not("desktop" or "mobile"))return Results.ValidationProblem(new Dictionary<string,string[]>{{"image",["La variante debe ser desktop o mobile."]}});await s.DeleteImageAsync(id,variant,ct);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.ComBannersEdit);
  admin.MapGet("/active-visual-ambience",(string surface,IVisualAmbienceStore s,CancellationToken ct)=>Safe(()=>s.ReadActiveAsync(surface,DateTimeOffset.UtcNow,ct))).RequireAuthorization();
  var pub=endpoints.MapGroup("/api/intranet").WithTags("Intranet").RequireAuthorization(AdminCorePermissions.IntranetVer);
  pub.MapGet("/events",(DateTimeOffset? from,DateTimeOffset? to,ICommunicationsStore s,CancellationToken ct)=>s.ListPublicEventsAsync(from??DateTimeOffset.UtcNow.AddMonths(-1),to??DateTimeOffset.UtcNow.AddMonths(6),ct)).RequireAuthorization(AdminCorePermissions.IntranetCalendarioVer);
  pub.MapGet("/events/{id:guid}",GetPublicEvent).RequireAuthorization(AdminCorePermissions.IntranetCalendarioVer);
  pub.MapGet("/banners",(ICommunicationsStore s,CancellationToken ct)=>s.ListPublicBannersAsync(DateTimeOffset.UtcNow,ct)).RequireAuthorization(AdminCorePermissions.IntranetInicioVer);
  pub.MapGet("/banners/{id:guid}/images/{variant}",GetImage).RequireAuthorization(AdminCorePermissions.IntranetVer);
  endpoints.MapGet("/api/public/login-configuration",PublicLogin).AllowAnonymous().WithTags("Public");
  endpoints.MapGet("/api/public/login-configuration/{id:guid}/images/{variant}",PublicLoginImage).AllowAnonymous().WithTags("Public");
  return endpoints;
 }
 private static async Task<IResult> UploadImage(Guid id,string variant,IFormFile file,ICommunicationsStore store,CancellationToken token){var allowedContentType=file.ContentType is "image/jpeg" or "image/png" or "image/webp";if(variant is not("desktop" or "mobile")||file.Length==0||file.Length>2*1024*1024||!allowedContentType)return Results.ValidationProblem(new Dictionary<string,string[]>{{"image",["Carga una imagen JPG, PNG o WebP de máximo 2 MB."]}});await using var stream=file.OpenReadStream();await store.UploadBannerImageAsync(id,variant,stream,file.ContentType,file.FileName,file.Length,token);return Results.NoContent();}
 private static async Task<IResult> UploadLoginImage(Guid id,string variant,IFormFile file,ILoginConfigurationStore store,CancellationToken token){var allowed=file.ContentType is "image/jpeg" or "image/png" or "image/webp";if(variant is not("desktop" or "tablet" or "mobile")||file.Length==0||file.Length>8*1024*1024||!allowed)return Results.ValidationProblem(new Dictionary<string,string[]>{{"image",["Carga una imagen JPG, PNG o WebP de máximo 8 MB."]}});await using var stream=file.OpenReadStream();await store.UploadImageAsync(id,variant,stream,file.ContentType,file.FileName,file.Length,token);return Results.NoContent();}
 private static async Task<IResult> UploadVisualAmbienceImage(Guid id,string variant,IFormFile file,IVisualAmbienceStore store,CancellationToken token){var allowed=file.ContentType is "image/jpeg" or "image/png" or "image/webp";if(variant is not("desktop" or "mobile")||file.Length==0||file.Length>8*1024*1024||!allowed)return Results.ValidationProblem(new Dictionary<string,string[]>{{"image",["Carga una imagen JPG, PNG o WebP de máximo 8 MB."]}});await using var stream=file.OpenReadStream();await store.UploadImageAsync(id,variant,stream,file.ContentType,file.FileName,file.Length,token);return Results.NoContent();}
 private static async Task<IResult> GetVisualAmbienceImage(Guid id,string variant,HttpContext context,IVisualAmbienceStore store,CancellationToken token){if(variant is not("desktop" or "mobile"))return Results.NotFound();var item=await store.ReadImageAsync(id,variant,token);if(item is null)return Results.NotFound();context.Response.GetTypedHeaders().CacheControl=new Microsoft.Net.Http.Headers.CacheControlHeaderValue{Private=true,MaxAge=TimeSpan.FromMinutes(10)};return Results.File(item.Bytes,item.ContentType);}
 private static async Task<IResult> GetLoginImage(Guid id,string variant,HttpContext context,ILoginConfigurationStore store,CancellationToken token){var item=await store.ReadImageAsync(id,variant,token);if(item is null)return Results.NotFound();context.Response.GetTypedHeaders().CacheControl=new Microsoft.Net.Http.Headers.CacheControlHeaderValue{Private=true,NoCache=true};return Results.File(item.Bytes,item.ContentType);}
 private static async Task<IResult> CreateLoginConfiguration(HttpRequest request,ILoginConfigurationStore store,CancellationToken token){if(!request.HasFormContentType)return Results.BadRequest(new{detail="La creación requiere multipart/form-data."});var form=await request.ReadFormAsync(token);var file=form.Files.GetFile("desktopImage");if(file is null||file.Length==0||file.Length>8*1024*1024||file.ContentType is not("image/jpeg" or "image/png" or "image/webp"))return Results.ValidationProblem(new Dictionary<string,string[]>{{"desktopImage",["Selecciona una imagen de escritorio JPG, PNG o WebP de máximo 8 MB."]}});LoginConfigurationWriteRequest? model;try{model=System.Text.Json.JsonSerializer.Deserialize<LoginConfigurationWriteRequest>(form["configuration"].ToString(),WebJson);}catch(System.Text.Json.JsonException){model=null;}if(model is null)return Results.ValidationProblem(new Dictionary<string,string[]>{{"configuration",["La configuración no es válida."]}});await using var stream=file.OpenReadStream();return await Safe(()=>store.CreateAsync(model,stream,file.ContentType,file.FileName,file.Length,token));}
 private static async Task<IResult> PublicLogin(ILoginConfigurationStore store,CancellationToken token){try{var item=await store.ReadPublicAsync(token);return item is null?Results.NoContent():Results.Ok(item);}catch{return Results.NoContent();}}
 private static async Task<IResult> PublicLoginImage(Guid id,string variant,HttpContext context,ILoginConfigurationStore store,CancellationToken token){try{var item=await store.ReadPublicImageAsync(id,variant,token);if(item is null)return Results.NotFound();context.Response.GetTypedHeaders().CacheControl=new Microsoft.Net.Http.Headers.CacheControlHeaderValue{Public=true,MaxAge=TimeSpan.FromMinutes(20)};return Results.File(item.Bytes,item.ContentType);}catch{return Results.NotFound();}}
 private static async Task<IResult> GetPublicEvent(Guid id,ICommunicationsStore store,CancellationToken token){var item=await store.GetPublicEventAsync(id,token);return item is null?Results.NotFound():Results.Ok(item);}
 private static async Task<IResult> GetImage(Guid id,string variant,HttpContext context,ICommunicationsStore store,CancellationToken token){var item=await store.ReadBannerImageAsync(id,variant,token);if(item is null)return Results.NotFound();context.Response.GetTypedHeaders().CacheControl=new Microsoft.Net.Http.Headers.CacheControlHeaderValue{Private=true,MaxAge=TimeSpan.FromMinutes(20)};return Results.File(item.Bytes,item.ContentType,enableRangeProcessing:false);}
 private static async Task<IResult> Safe<T>(Func<Task<T>> operation){try{return Results.Ok(await operation());}catch(ArgumentException e){return Results.ValidationProblem(new Dictionary<string,string[]>{{"request",[e.Message]}});}catch(KeyNotFoundException e){return Results.NotFound(new{detail=e.Message});}catch(InvalidOperationException e){return Results.Problem(statusCode:422,title:"No fue posible completar la operación",detail:e.Message);}}
}
public sealed record BannerStateRequest(string? Reason);
