using System.Globalization;
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using Gaia.Modules.Communications;
using Microsoft.Extensions.Caching.Memory;

namespace Gaia.Api.Infrastructure.Dataverse.Communications;

internal sealed class DataverseCommunicationsStore(IDataverseDelegatedClientFactory clients, IMemoryCache cache) : ICommunicationsStore
{
 const string Types="gaia_tipoevento",Events="gaia_evento",Banners="gaia_promocionbanner";
 public async Task<IReadOnlyList<EventTypeDto>> ListEventTypesAsync(bool inactive,CancellationToken ct){var(c,m,f)=await TypeContext(ct);var filter=inactive?"":"&$filter=statecode eq 0";var rows=await DataverseJson.ReadAllAsync(c,$"{m.EntitySetName}?$select={f.Select}&$orderby={f.Order} asc,{f.Name} asc{filter}",ct);return rows.Select(x=>MapType(x,f)).ToArray();}
 public async Task<EventTypeDto> SaveEventTypeAsync(Guid? id,EventTypeWriteRequest r,CancellationToken ct){CommunicationsRules.Validate(r);var(c,m,f)=await TypeContext(ct);var code=r.Code.Trim().ToUpperInvariant();var own=id.HasValue?$" and {m.PrimaryIdAttribute} ne {id:D}":"";if((await DataverseJson.ReadAllAsync(c,$"{m.EntitySetName}?$select={m.PrimaryIdAttribute}&$filter={f.Code} eq '{Esc(code)}'{own}&$top=1",ct)).Count>0)throw new ArgumentException("Ya existe un tipo con ese código.");var p=new Dictionary<string,object?>{{f.Name,r.Name.Trim()},{f.Code,code},{f.Color,r.Color.ToUpperInvariant()},{f.Description,r.Description},{f.Order,m.EncodedIntegerValue("gaia_Orden",r.Order)},{"statecode",r.IsActive?0:1}};var saved=await Write(c,m,id,p,ct);return MapType(await One(c,$"{m.EntitySetName}({saved:D})?$select={f.Select}",ct),f);}
 public async Task<IReadOnlyList<EventDto>> ListEventsAsync(bool inactive,CancellationToken ct){var(c,m,f)=await EventContext(ct);var filter=inactive?"":"&$filter=statecode eq 0";var rows=await DataverseJson.ReadAllAsync(c,$"{m.EntitySetName}?$select={f.Select}&$orderby={f.Start} desc{filter}",ct);return rows.Select(x=>MapEvent(x,f)).ToArray();}
 public async Task<EventDto> SaveEventAsync(Guid? id,EventWriteRequest r,CancellationToken ct){CommunicationsRules.Validate(r);var c=await clients.CreateAsync();var m=await DataverseMetadataResolver.TableAsync(c,Events,ct);var f=EventFields.From(m);await RequireActive(c,Types,r.EventTypeId,ct,"El tipo de evento no existe o está inactivo.");await RequireActive(c,"gaia_terceros",r.RequesterId,ct,"El solicitante no existe o está inactivo.");var typeM=await DataverseMetadataResolver.TableAsync(c,Types,ct);var thirdM=await DataverseMetadataResolver.TableAsync(c,"gaia_terceros",ct);var p=new Dictionary<string,object?>{{f.Name,r.Name.Trim()},{f.Summary,r.Summary},{f.Description,r.Description},{f.Start,r.StartsAt},{f.End,r.EndsAt},{f.AllDay,r.AllDay},{f.Modality,r.Modality.HasValue?m.EncodedIntegerValue("gaia_Modalidad",r.Modality.Value):null},{f.Location,r.Location},{f.Url,r.EventUrl},{f.Status,m.EncodedIntegerValue("gaia_Estado",1)},{f.TypeNav+"@odata.bind",$"/{typeM.EntitySetName}({r.EventTypeId:D})"},{f.RequesterNav+"@odata.bind",$"/{thirdM.EntitySetName}({r.RequesterId:D})"},{"statecode",0}};if(id.HasValue)p.Remove(f.Status);var saved=await Write(c,m,id,p,ct);return MapEvent(await One(c,$"{m.EntitySetName}({saved:D})?$select={f.Select}",ct),f);}
 public async Task<EventDto> ChangeEventStateAsync(Guid id,string action,CancellationToken ct){var(c,m,f)=await EventContext(ct);var item=await One(c,$"{m.EntitySetName}({id:D})?$select={f.Select}",ct);var current=Int(item,f.Status)??1;if(!CommunicationsRules.EventTransition(current,action))throw new InvalidOperationException("La transición solicitada no está permitida para el estado actual.");var p=new Dictionary<string,object?>();if(action=="publish")p[f.Status]=m.EncodedIntegerValue("gaia_Estado",2);if(action=="cancel")p[f.Status]=m.EncodedIntegerValue("gaia_Estado",3);if(action=="finish")p[f.Status]=m.EncodedIntegerValue("gaia_Estado",4);if(action=="deactivate")p["statecode"]=1;if(action=="restore")p["statecode"]=0;await Write(c,m,id,p,ct);return MapEvent(await One(c,$"{m.EntitySetName}({id:D})?$select={f.Select}",ct),f);}
 public async Task<IReadOnlyList<BannerDto>> ListBannersAsync(bool inactive,Guid? eventId,CancellationToken ct){var(c,m,f)=await BannerContext(ct);var clauses=new List<string>();if(!inactive)clauses.Add("statecode eq 0");if(eventId.HasValue)clauses.Add($"_{f.EventLookup}_value eq {eventId:D}");var filter=clauses.Count>0?$"&$filter={string.Join(" and ",clauses)}":"";var rows=await DataverseJson.ReadAllAsync(c,$"{m.EntitySetName}?$select={f.Select}&$orderby={f.Order} asc,{f.Start} desc{filter}",ct);return rows.Select(x=>MapBanner(x,f)).ToArray();}
 public async Task<BannerDto> SaveBannerAsync(Guid? id,BannerWriteRequest r,CancellationToken ct){CommunicationsRules.Validate(r);var c=await clients.CreateAsync();var m=await DataverseMetadataResolver.TableAsync(c,Banners,ct);var f=BannerFields.From(m);await RequireActive(c,"gaia_terceros",r.RequesterId,ct,"El solicitante no existe o está inactivo.");var thirdM=await DataverseMetadataResolver.TableAsync(c,"gaia_terceros",ct);var p=new Dictionary<string,object?>{{f.Name,r.Name.Trim()},{f.Eyebrow,r.Eyebrow},{f.Title,r.Title.Trim()},{f.Description,r.Description},{f.Start,r.StartsAt},{f.End,r.EndsAt},{f.Order,m.EncodedIntegerValue("gaia_Orden",r.Order)},{f.Destination,m.EncodedIntegerValue("gaia_TipoDestino",r.DestinationType)},{f.ActionUrl,r.DestinationType==2?r.ActionUrl:null},{f.RequesterNav+"@odata.bind",$"/{thirdM.EntitySetName}({r.RequesterId:D})"},{"statecode",0}};if(!id.HasValue)p[f.Status]=m.EncodedIntegerValue("gaia_Estado",1);if(r.EventId.HasValue){await RequireActive(c,Events,r.EventId.Value,ct,"El evento relacionado no existe o está inactivo.");var em=await DataverseMetadataResolver.TableAsync(c,Events,ct);p[f.EventNav+"@odata.bind"]=$"/{em.EntitySetName}({r.EventId:D})";}else if(id.HasValue)p[f.EventNav+"@odata.bind"]=null;var saved=await Write(c,m,id,p,ct);return MapBanner(await One(c,$"{m.EntitySetName}({saved:D})?$select={f.Select}",ct),f);}
 public async Task<BannerDto> ChangeBannerStateAsync(Guid id,string action,string? reason,CancellationToken ct){var(c,m,f)=await BannerContext(ct);var item=await One(c,$"{m.EntitySetName}({id:D})?$select={f.Select}",ct);var current=Int(item,f.Status)??1;if(!CommunicationsRules.BannerTransition(current,action))throw new InvalidOperationException("La transición solicitada no está permitida para el estado actual.");var p=new Dictionary<string,object?>();if(action=="design")p[f.Status]=m.EncodedIntegerValue("gaia_Estado",2);if(action=="publish"){if(!Present(item,f.DesktopImage))throw new InvalidOperationException("Carga la imagen de escritorio antes de publicar.");p[f.Status]=m.EncodedIntegerValue("gaia_Estado",3);}if(action=="close"){p[f.Status]=m.EncodedIntegerValue("gaia_Estado",4);p[f.Closed]=DateTimeOffset.UtcNow;}if(action=="reject"){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("El motivo de rechazo es obligatorio.");p[f.Status]=m.EncodedIntegerValue("gaia_Estado",5);p[f.Rejection]=reason;}if(action=="deactivate")p["statecode"]=1;if(action=="restore")p["statecode"]=0;await Write(c,m,id,p,ct);return MapBanner(await One(c,$"{m.EntitySetName}({id:D})?$select={f.Select}",ct),f);}
 public async Task UploadBannerImageAsync(Guid id,string variant,Stream content,string contentType,CancellationToken ct){_ = contentType;var c=await clients.CreateAsync();var m=await DataverseMetadataResolver.TableAsync(c,Banners,ct);var f=BannerFields.From(m);var field=variant=="mobile"?f.MobileImage:f.DesktopImage;using var body=new StreamContent(content);body.Headers.ContentType=MediaTypeHeaderValue.Parse("application/octet-stream");using var req=new HttpRequestMessage(HttpMethod.Patch,$"{m.EntitySetName}({id:D})/{field}"){Content=body};using var res=await c.SendAsync(req,ct);await Ensure(res,ct);cache.Remove(BannerImageCacheKey(id,variant));}
 public async Task<MediaContent?> ReadBannerImageAsync(Guid id,string variant,CancellationToken ct){var key=BannerImageCacheKey(id,variant);if(cache.TryGetValue(key,out MediaContent? cached))return cached;var c=await clients.CreateAsync();var m=await DataverseMetadataResolver.TableAsync(c,Banners,ct);var f=BannerFields.From(m);var field=variant=="mobile"?f.MobileImage:f.DesktopImage;using var res=await c.GetAsync($"{m.EntitySetName}({id:D})/{field}/$value",ct);if(res.StatusCode==HttpStatusCode.NotFound)return null;await Ensure(res,ct);var item=new MediaContent(await res.Content.ReadAsByteArrayAsync(ct),res.Content.Headers.ContentType?.MediaType??"image/jpeg");cache.Set(key,item,new MemoryCacheEntryOptions{SlidingExpiration=TimeSpan.FromMinutes(20),AbsoluteExpirationRelativeToNow=TimeSpan.FromHours(2),Size=null});return item;}
 static string BannerImageCacheKey(Guid id,string variant)=>$"communications:banner-image:{id:D}:{variant}";
 public async Task<IReadOnlyList<PublicEventDto>> ListPublicEventsAsync(DateTimeOffset from,DateTimeOffset until,CancellationToken ct){var rows=await ListEventsAsync(false,ct);var types=(await ListEventTypesAsync(true,ct)).ToDictionary(x=>x.Id);return rows.Where(x=>x.Status is 2 or 4&&x.StartsAt>=from&&x.StartsAt<until).OrderBy(x=>x.StartsAt).Select(x=>Public(x,types.GetValueOrDefault(x.EventTypeId))).ToArray();}
 public async Task<PublicEventDto?> GetPublicEventAsync(Guid id,CancellationToken ct){var item=(await ListEventsAsync(false,ct)).FirstOrDefault(x=>x.Id==id&&x.Status is 2 or 4);if(item is null)return null;var type=(await ListEventTypesAsync(true,ct)).FirstOrDefault(x=>x.Id==item.EventTypeId);return Public(item,type);}
 public async Task<IReadOnlyList<PublicBannerDto>> ListPublicBannersAsync(DateTimeOffset now,CancellationToken ct){var rowsTask=ListBannersAsync(false,null,ct);var eventsTask=ListEventsAsync(false,ct);await Task.WhenAll(rowsTask,eventsTask);var rows=await rowsTask;var events=await eventsTask;return rows.Where(x=>x.Status==3&&x.HasDesktopImage&&x.StartsAt<=now&&(x.EndsAt is null||x.EndsAt>now)&&(x.EventId is null||events.Any(e=>e.Id==x.EventId&&e.Status is 2 or 4))).OrderBy(x=>x.Order).ThenByDescending(x=>x.StartsAt).Select(x=>{var version=x.ModifiedAt.UtcTicks;return new PublicBannerDto(x.Id,x.Eyebrow,x.Title,x.Description,x.StartsAt,x.EndsAt,x.DestinationType,x.ActionUrl,x.EventId,$"/api/intranet/banners/{x.Id:D}/images/desktop?v={version}",x.HasMobileImage?$"/api/intranet/banners/{x.Id:D}/images/mobile?v={version}":$"/api/intranet/banners/{x.Id:D}/images/desktop?v={version}");}).ToArray();}
 static PublicEventDto Public(EventDto x,EventTypeDto? type)=>new(x.Id,x.Name,type?.Name??x.EventTypeName,type?.Color??x.EventTypeColor,x.Summary,x.Description,x.StartsAt,x.EndsAt,x.AllDay,x.Modality,x.Location,x.EventUrl);
 async Task<(HttpClient,DataverseTableMetadata,TypeFields)> TypeContext(CancellationToken ct){var c=await clients.CreateAsync();var m=await DataverseMetadataResolver.TableAsync(c,Types,ct);return(c,m,TypeFields.From(m));}
 async Task<(HttpClient,DataverseTableMetadata,EventFields)> EventContext(CancellationToken ct){var c=await clients.CreateAsync();var m=await DataverseMetadataResolver.TableAsync(c,Events,ct);return(c,m,EventFields.From(m));}
 async Task<(HttpClient,DataverseTableMetadata,BannerFields)> BannerContext(CancellationToken ct){var c=await clients.CreateAsync();var m=await DataverseMetadataResolver.TableAsync(c,Banners,ct);return(c,m,BannerFields.From(m));}
 static EventTypeDto MapType(JsonElement x,TypeFields f)=>new(Guid.Parse(Str(x,f.Id)!),Str(x,f.Name)??"",Str(x,f.Code)??"",Str(x,f.Color)??"#386037",Str(x,f.Description),Int(x,f.Order)??0,(Int(x,"statecode")??0)==0);
 static EventDto MapEvent(JsonElement x,EventFields f)=>new(Guid.Parse(Str(x,f.Id)!),Str(x,f.Name)??"",GuidVal(x,f.TypeLookup),Formatted(x,f.TypeLookup)??"Tipo",FormattedColor(x)??"#386037",Str(x,f.Summary),Str(x,f.Description),Date(x,f.Start)!.Value,Date(x,f.End),Bool(x,f.AllDay)??false,Int(x,f.Modality),Str(x,f.Location),Str(x,f.Url),Int(x,f.Status)??1,GuidVal(x,f.RequesterLookup),Formatted(x,f.RequesterLookup),(Int(x,"statecode")??0)==0);
 static BannerDto MapBanner(JsonElement x,BannerFields f)=>new(Guid.Parse(Str(x,f.Id)!),Str(x,f.Name)??"",GuidValNullable(x,f.EventLookup),Formatted(x,f.EventLookup),Str(x,f.Eyebrow),Str(x,f.Title)??"",Str(x,f.Description),Date(x,f.Start)!.Value,Date(x,f.End),Int(x,f.Order)??0,Int(x,f.Destination)??3,Str(x,f.ActionUrl),Int(x,f.Status)??1,GuidVal(x,f.RequesterLookup),Formatted(x,f.RequesterLookup),Str(x,f.Rejection),Date(x,f.Closed),Present(x,f.DesktopImage),Present(x,f.MobileImage),Date(x,"modifiedon")??DateTimeOffset.UnixEpoch,(Int(x,"statecode")??0)==0);
 static string? FormattedColor(JsonElement x)=>x.TryGetProperty("gaia_typecolor",out var v)?v.GetString():null;
 static async Task<Guid> Write(HttpClient c,DataverseTableMetadata m,Guid? id,Dictionary<string,object?> p,CancellationToken ct){if(!id.HasValue){using var res=await c.PostAsJsonAsync(m.EntitySetName,p,ct);await Ensure(res,ct);return CreatedId(res);}using var req=new HttpRequestMessage(HttpMethod.Patch,$"{m.EntitySetName}({id:D})"){Content=JsonContent.Create(p)};req.Headers.TryAddWithoutValidation("If-Match","*");using var updated=await c.SendAsync(req,ct);if(updated.StatusCode==HttpStatusCode.NotFound)throw new KeyNotFoundException("El registro no existe.");await Ensure(updated,ct);return id.Value;}
#pragma warning disable CA1068 // Internal helper keeps the explanatory message adjacent to the identifier at call sites.
 static async Task RequireActive(HttpClient c,string logical,Guid id,CancellationToken ct,string message){var m=await DataverseMetadataResolver.TableAsync(c,logical,ct);if(await DataverseMetadataResolver.ReadOneAsync(c,$"{m.EntitySetName}({id:D})?$select={m.PrimaryIdAttribute},statecode",ct) is not{} x||(Int(x,"statecode")??0)!=0)throw new ArgumentException(message);}
#pragma warning restore CA1068
 static async Task<JsonElement> One(HttpClient c,string path,CancellationToken ct)=>await DataverseMetadataResolver.ReadOneAsync(c,path,ct)??throw new KeyNotFoundException("El registro no existe.");
 static async Task Ensure(HttpResponseMessage r,CancellationToken ct){if(r.IsSuccessStatusCode)return;var content=await r.Content.ReadAsStringAsync(ct);throw new InvalidOperationException($"Dataverse rechazó la operación ({(int)r.StatusCode}): {ErrorMessage(content)}");}
 static string ErrorMessage(string content){try{using var document=JsonDocument.Parse(content);return document.RootElement.GetProperty("error").GetProperty("message").GetString()??"Error sin descripción.";}catch(JsonException){return"Respuesta no válida de Dataverse.";}}
 static Guid CreatedId(HttpResponseMessage r){var uri=r.Headers.TryGetValues("OData-EntityId",out var values)?values.SingleOrDefault():null;var match=System.Text.RegularExpressions.Regex.Match(uri??"",@"\(([0-9a-f-]{36})\)$");return match.Success?Guid.Parse(match.Groups[1].Value):throw new InvalidOperationException("Dataverse no devolvió el identificador creado.");}
 static string Esc(string x)=>x.Replace("'","''",StringComparison.Ordinal);static string? Str(JsonElement x,string p)=>x.TryGetProperty(p,out var v)&&v.ValueKind==JsonValueKind.String?v.GetString():null;static int? Int(JsonElement x,string p)=>DataverseJson.OptionalEncodedInt32(x,p);static bool? Bool(JsonElement x,string p)=>x.TryGetProperty(p,out var v)&&v.ValueKind is JsonValueKind.True or JsonValueKind.False?v.GetBoolean():null;static bool Present(JsonElement x,string p)=>x.TryGetProperty(p,out var v)&&v.ValueKind is not(JsonValueKind.Null or JsonValueKind.Undefined)&&(!(v.ValueKind==JsonValueKind.String)||!string.IsNullOrWhiteSpace(v.GetString()));static DateTimeOffset? Date(JsonElement x,string p)=>DateTimeOffset.TryParse(Str(x,p),CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out var d)?d:null;static Guid GuidVal(JsonElement x,string p)=>GuidValNullable(x,p)??Guid.Empty;static Guid? GuidValNullable(JsonElement x,string p)=>Guid.TryParse(Str(x,$"_{p}_value"),out var g)?g:null;static string? Formatted(JsonElement x,string p)=>Str(x,$"_{p}_value@OData.Community.Display.V1.FormattedValue");
 sealed record TypeFields(string Id,string Name,string Code,string Color,string Description,string Order){public string Select=>string.Join(',',Id,Name,Code,Color,Description,Order,"statecode");public static TypeFields From(DataverseTableMetadata m)=>new(m.PrimaryIdAttribute,m.Attribute("gaia_Nombre"),m.Attribute("gaia_Codigo"),m.Attribute("gaia_Color"),m.Attribute("gaia_Descripcion"),m.Attribute("gaia_Orden"));}
 sealed record EventFields(string Id,string Name,string TypeLookup,string TypeNav,string Summary,string Description,string Start,string End,string AllDay,string Modality,string Location,string Url,string Status,string RequesterLookup,string RequesterNav){public string Select=>string.Join(',',Id,Name,$"_{TypeLookup}_value",Summary,Description,Start,End,AllDay,Modality,Location,Url,Status,$"_{RequesterLookup}_value","statecode");public static EventFields From(DataverseTableMetadata m){var t=m.Relationship("gaia_TipoEvento",Types);var r=m.Relationship("gaia_Solicitante","gaia_terceros");return new(m.PrimaryIdAttribute,m.Attribute("gaia_Nombre"),t.ReferencingAttribute,t.NavigationProperty,m.Attribute("gaia_Resumen"),m.Attribute("gaia_Descripcion"),m.Attribute("gaia_FechaInicio"),m.Attribute("gaia_FechaFin"),m.Attribute("gaia_TodoDia"),m.Attribute("gaia_Modalidad"),m.Attribute("gaia_Ubicacion"),m.Attribute("gaia_EnlaceEvento"),m.Attribute("gaia_Estado"),r.ReferencingAttribute,r.NavigationProperty);}}
 sealed record BannerFields(string Id,string Name,string EventLookup,string EventNav,string Eyebrow,string Title,string Description,string DesktopImage,string MobileImage,string Start,string End,string Order,string Destination,string ActionUrl,string Status,string RequesterLookup,string RequesterNav,string Rejection,string Closed){public string Select=>string.Join(',',Id,Name,$"_{EventLookup}_value",Eyebrow,Title,Description,DesktopImage,MobileImage,Start,End,Order,Destination,ActionUrl,Status,$"_{RequesterLookup}_value",Rejection,Closed,"modifiedon","statecode");public static BannerFields From(DataverseTableMetadata m){var e=m.Relationship("gaia_Evento",Events);var r=m.Relationship("gaia_Solicitante","gaia_terceros");return new(m.PrimaryIdAttribute,m.Attribute("gaia_Nombre"),e.ReferencingAttribute,e.NavigationProperty,m.Attribute("gaia_Antetitulo"),m.Attribute("gaia_Titulo"),m.Attribute("gaia_Descripcion"),m.Attribute("gaia_ImagenEscritorio"),m.Attribute("gaia_ImagenMovil"),m.Attribute("gaia_InicioPublicacion"),m.Attribute("gaia_FinPublicacion"),m.Attribute("gaia_Orden"),m.Attribute("gaia_TipoDestino"),m.Attribute("gaia_EnlaceAccion"),m.Attribute("gaia_Estado"),r.ReferencingAttribute,r.NavigationProperty,m.Attribute("gaia_MotivoRechazo"),m.Attribute("gaia_FechaCierre"));}}
}
