"use client";
import {useEffect,useState,type FormEvent} from "react";
import {LoaderCircle,X} from "lucide-react";
import {apiRequest} from "@/lib/api-client";
import {DynamicFormRenderer,type DynamicValues,type StageForm} from "./helpdesk-dynamic-form";

type ManagementForm={managementId:string;requestId:string;form:StageForm|null;answers:{responseId:string;fieldId:string;value:string|null;optionIds:string[]}[]};

export function HelpdeskManagementFormDialog({managementId,requestId,result,requiresObservation,finalStep,onCancel,onCompleted}:{managementId:string;requestId:string;result:number;requiresObservation:boolean;finalStep:boolean;onCancel:()=>void;onCompleted:(observation:string|null)=>Promise<void>}){
 const[data,setData]=useState<ManagementForm|null>(null),[values,setValues]=useState<DynamicValues>({}),[observation,setObservation]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let live=true;apiRequest<ManagementForm>(`/api/helpdesk/management/workflows/${managementId}/form`,{cache:"no-store"}).then(value=>{if(!live)return;setData(value);const initial:DynamicValues={};for(const answer of value.answers)initial[answer.fieldId]=answer.optionIds.length?answer.optionIds:answer.value??"";setValues(initial)}).catch(e=>live&&setError(message(e)));return()=>{live=false}},[managementId]);
 const requiresComment=requiresObservation||finalStep||result===299540173;
 async function submit(event:FormEvent){event.preventDefault();if(!data)return;setBusy(true);setError("");try{if(data.form){const answers=data.form.fields.filter(x=>x.visible).map(field=>{const value=values[field.id];return{fieldId:field.id,value:field.dataType===299540046||field.dataType===299540047?null:typeof value==="string"?value:null,optionIds:field.dataType===299540046?(Array.isArray(value)?value:typeof value==="string"&&value?[value]:[]):[]}});const saved=await apiRequest<{fieldId:string;responseId:string}[]>(`/api/helpdesk/management/workflows/${managementId}/form/responses`,{method:"PUT",body:JSON.stringify({answers})});const responseIds=new Map(saved.map(x=>[x.fieldId,x.responseId]));for(const field of data.form.fields.filter(x=>x.visible&&x.dataType===299540047)){const files=values[field.id];if(!Array.isArray(files))continue;for(const file of files as File[]){const body=new FormData();body.append("file",file);body.append("visibility","internal");body.append("managementId",managementId);body.append("managementFieldResponseId",responseIds.get(field.id)??"");await apiRequest(`/api/helpdesk/requests/${requestId}/attachments`,{method:"POST",body})}}}await onCompleted(observation.trim()||null)}catch(e){setError(message(e));setBusy(false)}}
 const title=result===299540171?"Aprobar etapa":result===299540172?"Rechazar etapa":result===299540173?"Solicitar información":"Completar etapa";
 return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/45 p-3"><form className="max-h-[94vh] w-[min(96vw,64rem)] overflow-auto rounded-3xl bg-[var(--surface-card)] p-6 shadow-2xl" onSubmit={submit}><header className="flex items-start justify-between gap-4"><div><small className="font-bold uppercase tracking-widest text-[var(--brand-primary)]">Gestión de solicitud</small><h2 className="mt-1 text-2xl font-semibold">{title}</h2><p className="mt-1 text-sm text-[var(--gaia-ink-500)]">Completa la información de esta etapa antes de registrar el resultado.</p></div><button aria-label="Cerrar" className="rounded-full border p-2" disabled={busy} onClick={onCancel} type="button"><X size={18}/></button></header>{error&&<p className="mt-4 rounded-xl bg-[#fff0f0] p-3 text-sm text-[#9a384d]">{error}</p>}{!data?<p className="mt-8 flex items-center justify-center gap-2 text-sm"><LoaderCircle className="animate-spin" size={17}/>Cargando formulario de la etapa…</p>:<><div className="mt-6">{data.form?<DynamicFormRenderer form={data.form} onChange={(id,value)=>setValues(current=>({...current,[id]:value}))} values={values}/>:<p className="rounded-xl border border-dashed p-5 text-center text-sm text-[var(--gaia-ink-500)]">Esta etapa no requiere un formulario adicional.</p>}</div><label className="mt-5 block text-sm font-semibold">{result===299540173?"Información que debe aportar el solicitante":finalStep?"Resumen de la solución":"Observación de la gestión"}<textarea className="mt-2 w-full rounded-xl border border-[var(--gaia-line)] p-3" maxLength={4000} onChange={e=>setObservation(e.target.value)} required={requiresComment} rows={4} value={observation}/></label><div className="sticky bottom-0 -mx-6 -mb-6 mt-6 flex justify-end gap-2 border-t bg-[var(--surface-card)] px-6 py-4"><button className="rounded-xl border px-4 py-2" disabled={busy} onClick={onCancel} type="button">Cancelar</button><button className="rounded-xl bg-[var(--brand-primary)] px-5 py-2 font-semibold text-white disabled:opacity-60" disabled={busy}>{busy?"Guardando…":title}</button></div></>}</form></div>
}
const message=(error:unknown)=>error instanceof Error?error.message:"No fue posible completar la gestión.";
