using Gaia.Modules.Security;
using Gaia.BuildingBlocks.Files;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using System.Security.Claims;

namespace Gaia.Modules.Training;

public static class TrainingEndpoints
{
    public static IEndpointRouteBuilder MapTrainingEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var group=endpoints.MapGroup("/api/training/administration").WithTags("Training");
        group.MapGet("/overview",async (ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,CancellationToken token) => Results.Ok(await reader.ReadAsync((await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId,token))).RequireAuthorization(AdminCorePermissions.TrainingCatalogRead);
        group.MapPost("/categories",async (SaveTrainingCategory value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Created("/api/training/administration/overview",new{id=await reader.SaveCategoryAsync(null,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingCatalogManage);
        group.MapPut("/categories/{id:guid}",async (Guid id,SaveTrainingCategory value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(new{id=await reader.SaveCategoryAsync(id,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingCatalogManage);
        group.MapPost("/trainings",async (SaveTraining value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Created("/api/training/administration/overview",new{id=await reader.SaveTrainingAsync(null,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingCatalogManage);
        group.MapPut("/trainings/{id:guid}",async (Guid id,SaveTraining value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(new{id=await reader.SaveTrainingAsync(id,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingCatalogManage);
        group.MapPost("/versions",async (SaveTrainingVersion value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Created("/api/training/administration/overview",new{id=await reader.SaveVersionAsync(null,value,(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero."),token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPut("/versions/{id:guid}",async (Guid id,SaveTrainingVersion value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(new{id=await reader.SaveVersionAsync(id,value,(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero."),token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapGet("/versions/{id:guid}/content",async (Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(await reader.ReadContentAsync(id,token))).RequireAuthorization(AdminCorePermissions.TrainingContentRead);
        group.MapPost("/versions/{id:guid}/resources",UploadResource).DisableAntiforgery().WithMetadata(new DisableRequestSizeLimitAttribute()).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPost("/versions/{id:guid}/sections",async (Guid id,SaveTrainingSection value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Created(".",new{id=await reader.SaveSectionAsync(id,null,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPut("/versions/{versionId:guid}/sections/{id:guid}",async (Guid versionId,Guid id,SaveTrainingSection value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(new{id=await reader.SaveSectionAsync(versionId,id,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapDelete("/versions/{versionId:guid}/sections/{id:guid}",async (Guid versionId,Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.RemoveSectionAsync(versionId,id,token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPost("/sections/{id:guid}/blocks",async (Guid id,SaveTrainingBlock value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Created(".",new{id=await reader.SaveBlockAsync(id,null,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPut("/sections/{sectionId:guid}/blocks/{id:guid}",async (Guid sectionId,Guid id,SaveTrainingBlock value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(new{id=await reader.SaveBlockAsync(sectionId,id,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapDelete("/sections/{sectionId:guid}/blocks/{id:guid}",async (Guid sectionId,Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.RemoveBlockAsync(sectionId,id,token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapGet("/versions/{id:guid}/evaluations",async (Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(await reader.ReadEvaluationsAsync(id,token))).RequireAuthorization(AdminCorePermissions.TrainingContentRead);
        group.MapPost("/versions/{id:guid}/evaluations",SaveEvaluation).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPut("/versions/{versionId:guid}/evaluations/{id:guid}",async (Guid versionId,Guid id,SaveTrainingEvaluation value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(new{id=await reader.SaveEvaluationAsync(versionId,id,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapDelete("/versions/{versionId:guid}/evaluations/{id:guid}",async (Guid versionId,Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.RemoveEvaluationAsync(versionId,id,token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPost("/evaluations/{id:guid}/questions",async (Guid id,SaveTrainingQuestion value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Created(".",new{id=await reader.SaveQuestionAsync(id,null,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPut("/evaluations/{evaluationId:guid}/questions/{id:guid}",async (Guid evaluationId,Guid id,SaveTrainingQuestion value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(new{id=await reader.SaveQuestionAsync(evaluationId,id,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapDelete("/evaluations/{evaluationId:guid}/questions/{id:guid}",async (Guid evaluationId,Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.RemoveQuestionAsync(evaluationId,id,token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPost("/questions/{id:guid}/options",async (Guid id,SaveTrainingOption value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Created(".",new{id=await reader.SaveOptionAsync(id,null,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPut("/questions/{questionId:guid}/options/{id:guid}",async (Guid questionId,Guid id,SaveTrainingOption value,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(new{id=await reader.SaveOptionAsync(questionId,id,value,token)})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapDelete("/questions/{questionId:guid}/options/{id:guid}",async (Guid questionId,Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.RemoveOptionAsync(questionId,id,token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapGet("/versions/{id:guid}/audience",async (Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Ok(await reader.ReadAudienceAsync(id,token))).RequireAuthorization(AdminCorePermissions.TrainingAudiencesRead);
        group.MapPost("/versions/{id:guid}/audience",async (Guid id,SaveTrainingAudienceRule value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,CancellationToken token)=>Results.Created(".",new{id=await reader.SaveAudienceRuleAsync(id,value,(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero."),token)})).RequireAuthorization(AdminCorePermissions.TrainingAudiencesManage);
        group.MapDelete("/versions/{versionId:guid}/audience/{id:guid}",async (Guid versionId,Guid id,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.RemoveAudienceRuleAsync(versionId,id,token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingAudiencesManage);
        group.MapPost("/versions/{id:guid}/submit-review",async (Guid id,TrainingVersionTransition value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.TransitionVersionAsync(id,299540001,value.Reason,value.CorrelationId,(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero."),token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPost("/versions/{id:guid}/return",async (Guid id,TrainingVersionTransition value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.TransitionVersionAsync(id,299540000,value.Reason,value.CorrelationId,(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero."),token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingReview);
        group.MapPost("/versions/{id:guid}/publish",async (Guid id,TrainingVersionTransition value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,ITrainingOperations operations,CancellationToken token)=>{var actor=(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero.");await reader.TransitionVersionAsync(id,299540002,value.Reason,value.CorrelationId,actor,token);return Results.Ok(await operations.GenerateAssignmentsAsync(id,actor,token));}).RequireAuthorization(AdminCorePermissions.TrainingPublish);
        group.MapPost("/versions/{id:guid}/publish-direct",async (Guid id,TrainingVersionTransition value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,ITrainingOperations operations,CancellationToken token)=>await TrainingParticipantEndpoints.Safe(async()=>{var actor=(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero.");await reader.TransitionVersionAsync(id,299540002,value.Reason,value.CorrelationId,actor,token,true);return Results.Ok(await operations.GenerateAssignmentsAsync(id,actor,token));})).RequireAuthorization(AdminCorePermissions.TrainingContentManage);
        group.MapPost("/versions/{id:guid}/assignments/synchronize",async (Guid id,ClaimsPrincipal principal,ISecurityStore security,ITrainingOperations operations,CancellationToken token)=>Results.Ok(await operations.GenerateAssignmentsAsync(id,(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero."),token))).RequireAuthorization(AdminCorePermissions.TrainingAssignmentsManage);
        group.MapGet("/tracking",async (ITrainingOperations operations,CancellationToken token)=>Results.Ok(await operations.ReadTrackingAsync(token))).RequireAuthorization(AdminCorePermissions.TrainingTrackingRead);
        group.MapGet("/results",async (ITrainingOperations operations,CancellationToken token)=>Results.Ok(await operations.ReadResultsAsync(token))).RequireAuthorization(AdminCorePermissions.TrainingResultsRead);
        group.MapPost("/versions/{id:guid}/close",async (Guid id,TrainingVersionTransition value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.TransitionVersionAsync(id,299540003,value.Reason,value.CorrelationId,(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero."),token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingArchive);
        group.MapPost("/versions/{id:guid}/archive",async (Guid id,TrainingVersionTransition value,ClaimsPrincipal principal,ISecurityStore security,ITrainingAdministrationReader reader,CancellationToken token)=>{await reader.TransitionVersionAsync(id,299540004,value.Reason,value.CorrelationId,(await security.GetOrProvisionAsync(principal,token)).User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero."),token);return Results.NoContent();}).RequireAuthorization(AdminCorePermissions.TrainingArchive);
        var participant=endpoints.MapGroup("/api/training/my").WithTags("Training").AddEndpointFilter(async(context,next)=>{context.HttpContext.Response.Headers.CacheControl="private, no-store";return await next(context);});
        participant.MapGet("/assignments",async (ClaimsPrincipal principal,ISecurityStore security,ITrainingOperations operations,CancellationToken token)=>Results.Ok(await operations.ReadMyAssignmentsAsync(RequireActor(await security.GetOrProvisionAsync(principal,token)),token))).RequireAuthorization(AdminCorePermissions.IntranetTrainingVer);
        participant.MapGet("/assignments/{id:guid}",async (Guid id,ClaimsPrincipal principal,ISecurityStore security,ITrainingOperations operations,CancellationToken token)=>await TrainingParticipantEndpoints.Safe(async()=>Results.Ok(await operations.ReadMyAssignmentAsync(id,RequireActor(await security.GetOrProvisionAsync(principal,token)),token)))).RequireAuthorization(AdminCorePermissions.IntranetTrainingVer);
        participant.MapPost("/assignments/{id:guid}/blocks/{blockId:guid}/complete",async (Guid id,Guid blockId,CompleteTrainingBlock value,ClaimsPrincipal principal,ISecurityStore security,ITrainingOperations operations,CancellationToken token)=>await TrainingParticipantEndpoints.Safe(async()=>Results.Ok(await operations.CompleteBlockAsync(id,blockId,RequireActor(await security.GetOrProvisionAsync(principal,token)),token,value)))).RequireAuthorization(AdminCorePermissions.IntranetTrainingVer);
        endpoints.MapTrainingParticipantEndpoints();
        return endpoints;
    }

    static Guid RequireActor(SecurityContextResponse context)=>context.User.ThirdPartyId??throw new InvalidOperationException("El usuario no está vinculado a un tercero.");

    static async Task<IResult> SaveEvaluation(Guid id,SaveTrainingEvaluation value,ITrainingAdministrationReader reader,CancellationToken token)
    {
        try{return Results.Created(".",new{id=await reader.SaveEvaluationAsync(id,null,value,token)});}catch(ArgumentException error){return Results.ValidationProblem(new Dictionary<string,string[]>{{"evaluation",[error.Message]}});}catch(KeyNotFoundException error){return Results.Problem(statusCode:404,title:"Evaluación no disponible",detail:error.Message);}catch(InvalidOperationException error){return Results.Problem(statusCode:422,title:"No fue posible crear la evaluación",detail:SafeDataverseDetail(error.Message));}
    }

    static string SafeDataverseDetail(string message)
    {
        if(!message.StartsWith("Dataverse rechazó la operación",StringComparison.Ordinal))return message;var marker="\"message\":\"";var start=message.IndexOf(marker,StringComparison.OrdinalIgnoreCase);if(start<0)return "Dataverse rechazó la creación. Verifica que las columnas del modelo de Capacitaciones estén publicadas.";start+=marker.Length;var end=message.IndexOf('"',start);return end>start?message[start..end].Replace("\\u0027","'",StringComparison.Ordinal):"Dataverse rechazó la creación. Verifica que las columnas del modelo de Capacitaciones estén publicadas.";
    }

    static async Task<IResult> UploadResource(Guid id,HttpRequest request,ClaimsPrincipal principal,ISecurityStore security,IFileStorage storage,IFileStorageMaintenance maintenance,ITrainingAdministrationReader reader,CancellationToken token)
    {
        if(request.ContentLength is >262_144_000)return Results.Problem(statusCode:413,title:"El archivo es demasiado grande",detail:"El archivo supera el límite permitido de 250 MB.");
        if(!request.HasFormContentType)return Results.BadRequest(new{detail="La carga debe usar multipart/form-data."});var form=await request.ReadFormAsync(token);var file=form.Files.GetFile("file");if(file is null||file.Length<=0)return Results.BadRequest(new{detail="Selecciona un archivo válido."});var kind=string.Equals(form["kind"],"video",StringComparison.OrdinalIgnoreCase)?299541021:299541022;var extension=Path.GetExtension(file.FileName).ToLowerInvariant();var normalizedContentType=kind==299541021&&extension==".mp4"?"video/mp4":file.ContentType;var allowed=kind==299541021?(normalizedContentType.StartsWith("video/",StringComparison.OrdinalIgnoreCase)&&extension is ".mp4" or ".webm" or ".mov"):file.ContentType is "application/pdf" or "application/vnd.openxmlformats-officedocument.wordprocessingml.document" or "application/vnd.openxmlformats-officedocument.presentationml.presentation" or "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";if(!allowed)return Results.BadRequest(new{detail=kind==299541021?"Selecciona un video MP4, WebM o MOV válido.":"El documento debe ser PDF, Word, Excel o PowerPoint."});var actor=RequireActor(await security.GetOrProvisionAsync(principal,token));var uploadedAt=DateTimeOffset.UtcNow;var fileId=Guid.NewGuid();StoredFile? stored=null;try{await using var stream=file.OpenReadStream();stored=await storage.UploadAsync(new(new("Capacitaciones",id.ToString("D")),file.FileName,normalizedContentType,file.Length,fileId,uploadedAt),stream,token);var saved=await reader.SaveResourceAsync(new(id,actor,kind,file.FileName,stored.StoredName,stored.Id.Provider,stored.Id.RepositoryId,stored.Id.ContainerId,stored.Id.FileId,stored.LogicalPath,stored.WebUrl?.ToString(),stored.ContentType,stored.Length,stored.Sha256,stored.ETag,stored.UploadedAt??uploadedAt),token);return Results.Created(".",saved);}catch{if(stored is not null)try{await maintenance.DeletePhysicallyAsync(new(stored.Id,stored.ETag,"Cleanup of uncommitted training resource"),CancellationToken.None);}catch(FileStorageException){}throw;}
    }
}
