"use client";

import { type FormEvent, useEffect, useRef, useState } from "react";
import { ArrowDownUp, ArrowLeft, ArrowRight, CheckCircle2, Eye, FileDown, Inbox, Laptop, LoaderCircle, MessageSquareText, Paperclip, Plus, Search, ShieldCheck, SlidersHorizontal, X } from "lucide-react";
import styles from "./intranet-solicitudes.module.css";
import { apiRequest } from "@/lib/api-client";
import { downloadClosurePdf } from "@/features/solicitudes/solicitudes-closure-pdf";
import { WorkflowRouteMap } from "@/features/solicitudes/solicitudes-workflow-route-map";
import { orderCompletedManagements } from "@/features/solicitudes/solicitudes-workflow-order";

type Area={id:string;name:string;shortName:string;order:number};
type Service={id:string;areaId:string;code:string;name:string;description:string|null;instructions:string|null;allowsAttachments:boolean;maximumAttachments:number;maximumFileMb:number;order:number};
type Request={id:string;number:string;subject:string;service:string;status:string;statusColor:string|null;isFinal:boolean;submittedAt:string|null;dueDate:string|null};
type Portal={open:number;inProgress:number;resolvedRecently:number;areas:Area[];services:Service[];requests:Request[]};
type Catalog={areas:Area[];services:Service[]};
type Comment={id:string;content:string;publishedAt:string;isInternal:boolean;isMine:boolean;authorRole:string};
type Detail={id:string;number:string;subject:string;description:string;service:string;status:string;statusColor:string|null;submittedAt:string|null;dueDate:string|null;comments:Comment[]};
type Attachment={id:string;managementId:string|null;file:{originalName:string|null;storedName:string;length:number};uploadedAt:string};
type WorkflowItem={id:string;stepId:string;stepCode:string;execution:number;status:number;result:number|null;observation:string|null;unitName:string|null;responsibleName:string|null;formTitle:string|null;availableAt:string|null;completedAt:string|null};
type WorkflowStep={id:string;code:string;order:number;initial:boolean;final:boolean;active:boolean;positionX:number|null;positionY:number|null};
type WorkflowRoute={id:string;sourceStepId:string;targetStepId:string;active:boolean};
type Workflow={version:number;status:number;managements:WorkflowItem[];steps:WorkflowStep[]|null;routes:WorkflowRoute[]|null};
type FormOption={id:string;code:string;label:string;isDefault:boolean;order:number};type FormField={id:string;code:string;label:string;dataType:number;controlType:number;helpText:string|null;placeholder:string|null;required:boolean;order:number;width:number;minimumLength:number|null;maximumLength:number|null;allowsMultiple:boolean;maximumFiles:number|null;allowedFileTypes:string|null;options:FormOption[]};type ServiceForm={id:string;version:number;title:string;instructions:string|null;fields:FormField[]};
type RequestFilter="all"|"open"|"tracking"|"resolved"|"closed";
const REQUEST_PAGE_SIZE=10;
function requestFilter(item:Request):Exclude<RequestFilter,"all">{const status=item.status.toLocaleLowerCase("es");if(/cerrad|cancelad/.test(status))return "closed";if(item.isFinal||/resuelt|solucionad/.test(status))return "resolved";if(/seguimiento|progreso|espera|asignad|gestión/.test(status))return "tracking";return "open";}
function formatRequestDate(value:string|null){return value?new Intl.DateTimeFormat("es-CO",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"Sin fecha";}
function formatDueDate(value:string|null){if(!value)return "Por definir";const[year,month,day]=value.split("-").map(Number);return new Intl.DateTimeFormat("es-CO",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(year,month-1,day)))}
function friendlyStep(value:string){return value.toLocaleLowerCase("es").replaceAll("_"," ").replace(/(^|\s)\p{L}/gu,letter=>letter.toLocaleUpperCase("es"))}
function workflowDecision(value:number|null){return value===299540171?"Aprobada":value===299540172?"Rechazada":value===299540173?"Información solicitada":value===299540174?"Requiere aprobación":value===299540175?"No aplica":"Completada"}
function workflowDate(value:string|null){return value?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Sin fecha registrada"}
function StageDecisionHistory({managements}:{managements:WorkflowItem[]}){const completed=orderCompletedManagements(managements.filter(item=>item.status===299540194||Boolean(item.completedAt)));if(!completed.length)return <section className="mt-4 rounded-2xl border border-dashed border-[var(--gaia-line)] bg-[var(--surface-muted)] p-5 text-center text-sm text-[var(--gaia-ink-500)]"><strong className="block text-[var(--gaia-ink-900)]">Aún no hay decisiones registradas</strong><span className="mt-1 block">Aquí aparecerá el resultado de cada etapa cuando sea gestionada.</span></section>;return <section className="mt-4" aria-labelledby="request-stage-decisions"><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><h3 className="!m-0 text-sm font-semibold" id="request-stage-decisions">Gestión realizada en cada etapa</h3><p className="mt-1 text-xs text-[var(--gaia-ink-500)]">Decisiones registradas en orden cronológico.</p></div><span className="rounded-full bg-[var(--gaia-accent-soft)] px-2.5 py-1 text-xs font-semibold text-[var(--brand-primary)]">{completed.length} {completed.length===1?"etapa gestionada":"etapas gestionadas"}</span></div><ol className="grid gap-3 md:grid-cols-2">{completed.map((item,index)=><li className="relative rounded-2xl border border-[var(--gaia-line)] bg-white p-4 pl-14 shadow-[0_3px_14px_rgba(23,75,64,.06)]" key={item.id}><span className="absolute left-4 top-4 grid size-7 place-items-center rounded-full bg-[var(--brand-primary)] text-xs font-bold text-white">{index+1}</span><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="text-sm">{item.formTitle||friendlyStep(item.stepCode)}</strong><small className="mt-1 block text-[var(--gaia-ink-500)]">{workflowDate(item.completedAt)}</small></div><span className="rounded-full bg-[#e7f5ef] px-2.5 py-1 text-[10px] font-bold text-[#17695b]">{workflowDecision(item.result)}</span></div>{(item.unitName||item.responsibleName)&&<p className="mt-3 text-xs text-[var(--gaia-ink-500)]">{item.unitName||"Área sin identificar"}{item.responsibleName?` · ${item.responsibleName}`:""}</p>}{item.observation&&<div className="mt-3 rounded-xl bg-[var(--surface-muted)] px-3 py-2.5"><small className="font-bold uppercase tracking-wide text-[var(--gaia-ink-500)]">Observación</small><p className="mt-1 whitespace-pre-wrap text-sm text-[var(--gaia-ink-900)]">{item.observation}</p></div>}</li>)}</ol></section>}
function AttachmentList({attachments}:{attachments:Attachment[]}){if(!attachments.length)return <div className="rounded-xl bg-[var(--surface-muted)] p-5 text-center text-sm text-[var(--gaia-ink-500)]">Esta solicitud no tiene archivos adjuntos.</div>;return <div className="grid gap-3 sm:grid-cols-2">{attachments.map(item=><a className="flex items-center gap-3 rounded-xl border border-[var(--gaia-line)] bg-white p-4 transition hover:bg-[var(--gaia-accent-pale)]" href={`${process.env.NEXT_PUBLIC_GAIA_API_URL??"https://localhost:7168"}/api/solicitudes/attachments/${item.id}/content`} key={item.id}><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--gaia-accent-soft)] text-[var(--brand-primary)]"><Paperclip size={17}/></span><span className="min-w-0"><strong className="block truncate text-sm text-[var(--brand-primary)]">{item.file.originalName||item.file.storedName}</strong><small className="text-[var(--gaia-ink-500)]">{Math.ceil(item.file.length/1024)} KB · {item.managementId?"Gestión":"Solicitud"}</small></span></a>)}</div>}
function DynamicField({field,value,change}:{field:FormField;value:string|string[]|undefined;change:(value:string|string[])=>void}){return <label>{field.label}{field.options.length?(field.allowsMultiple?<select aria-label={`Selecciona ${field.label}`} multiple onChange={event=>change(Array.from(event.target.selectedOptions).map(option=>option.value))} required={field.required} value={Array.isArray(value)?value:[]} >{field.options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select>:<select aria-label={`Selecciona ${field.label}`} onChange={event=>change(event.target.value)} required={field.required} value={typeof value==="string"?value:""}><option value="">Selecciona {field.label.toLocaleLowerCase("es")}…</option>{field.options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select>):field.dataType===299540045?<input checked={value==="true"} onChange={event=>change(String(event.target.checked))} type="checkbox"/>:field.controlType===299540051?<textarea maxLength={field.maximumLength??undefined} minLength={field.minimumLength??undefined} onChange={event=>change(event.target.value)} placeholder={field.placeholder??undefined} required={field.required} rows={4} value={typeof value==="string"?value:""}/>:<input maxLength={field.maximumLength??undefined} minLength={field.minimumLength??undefined} onChange={event=>change(event.target.value)} placeholder={field.placeholder??undefined} required={field.required} type={field.controlType===299540052?"number":field.controlType===299540053?"email":field.controlType===299540056?"date":field.controlType===299540057?"datetime-local":"text"} value={typeof value==="string"?value:""}/>} {field.helpText&&<small>{field.helpText}</small>}</label>}
function isAttachmentField(field:FormField){return field.code.toUpperCase()==="ADJUNTOS"}
export function IntranetSolicitudes(){
 const requestPanel=useRef<HTMLDetailsElement>(null);
 const detailLoadVersion=useRef(0);
 function startRequest(id?:string){if(requestOpening)return;if(portalError&&!portalLoading)void load();const panel=requestPanel.current;if(panel)panel.open=true;setRequestOpening(true);window.requestAnimationFrame(()=>{window.requestAnimationFrame(()=>{setRequestOpening(false);panel?.querySelector<HTMLSelectElement>("select")?.focus({preventScroll:true});});});if(id){const service=portal?.services.find(item=>item.id===id);if(service)setAreaId(service.areaId);void chooseService(id);}}
 const[portal,setPortal]=useState<Portal|null>(null),[portalLoading,setPortalLoading]=useState(true),[portalError,setPortalError]=useState(""),[error,setError]=useState(""),[search,setSearch]=useState("");
 const[requestOpening,setRequestOpening]=useState(false),[requestState,setRequestState]=useState<RequestFilter>("all"),[requestService,setRequestService]=useState(""),[requestSort,setRequestSort]=useState<"recent"|"oldest">("recent"),[requestPage,setRequestPage]=useState(1);
 const[areaId,setAreaId]=useState(""),[serviceId,setServiceId]=useState(""),[loadingForm,setLoadingForm]=useState(false),[files,setFiles]=useState<File[]>([]),[saving,setSaving]=useState(false),[result,setResult]=useState(""),[confirming,setConfirming]=useState(false);
 const[detail,setDetail]=useState<Detail|null>(null),[detailLoading,setDetailLoading]=useState<Request|null>(null),[workflow,setWorkflow]=useState<Workflow|null>(null),[attachments,setAttachments]=useState<Attachment[]>([]),[comment,setComment]=useState(""),[responseFiles,setResponseFiles]=useState<File[]>([]),[posting,setPosting]=useState(false),[confirmingResponse,setConfirmingResponse]=useState(false),[responseError,setResponseError]=useState(""),[responseSuccess,setResponseSuccess]=useState(""),[pdfRequestId,setPdfRequestId]=useState<string|null>(null);
 const[serviceForm,setServiceForm]=useState<ServiceForm|null>(null),[answers,setAnswers]=useState<Record<string,string|string[]>>({});
 async function load(){
  setPortalLoading(true);setPortalError("");
  let catalog:Catalog;
  try{
   catalog=await apiRequest<Catalog>("/api/solicitudes/portal/catalog",{cache:"no-store"});
   setPortal(current=>({...current??{open:0,inProgress:0,resolvedRecently:0,requests:[]},areas:catalog.areas,services:catalog.services}));
  }catch(reason){
   setPortal(current=>({...current??{open:0,inProgress:0,resolvedRecently:0,requests:[]},areas:[],services:[]}));
   setPortalError(reason instanceof Error?reason.message:"No fue posible cargar las áreas y servicios.");
   setPortalLoading(false);return;
  }
  setPortalLoading(false);
  try{
   const snapshot=await apiRequest<Portal>("/api/solicitudes/portal",{cache:"no-store"});
   setPortal({...snapshot,areas:catalog.areas,services:catalog.services});
  }catch(reason){setError(reason instanceof Error?`Las áreas y servicios están disponibles, pero no fue posible consultar tus solicitudes: ${reason.message}`:"No fue posible consultar tus solicitudes.")}
 }
 useEffect(()=>{void load()},[]);
 function chooseArea(id:string){setAreaId(id);setServiceId("");setServiceForm(null);setAnswers({});setFiles([]);setResult("");setError("");}
 async function chooseService(id:string){setServiceId(id);setServiceForm(null);setAnswers({});setFiles([]);setError("");if(!id){setResult("");setLoadingForm(false);return;}setLoadingForm(true);try{setServiceForm(await apiRequest<ServiceForm|undefined>(`/api/solicitudes/services/${id}/form`,{cache:"no-store"})??null)}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible cargar el formulario.")}finally{setLoadingForm(false)}}
 function submit(event:FormEvent){event.preventDefault();setConfirming(true);}
async function confirmRequest(){
 setSaving(true);setError("");setResult("");
 try{
  const selectedService=portal?.services.find(item=>item.id===serviceId),attachmentField=serviceForm?.fields.find(isAttachmentField),subjectField=serviceForm?.fields.find(item=>item.code.toLocaleUpperCase("es")==="ASUNTO"),descriptionField=serviceForm?.fields.find(item=>item.code.toLocaleUpperCase("es")==="DESCRIPCION"),submittedSubject=subjectField&&typeof answers[subjectField.id]==="string"?String(answers[subjectField.id]):selectedService?.name??"Solicitud",description=descriptionField&&typeof answers[descriptionField.id]==="string"?String(answers[descriptionField.id]):submittedSubject,submittedFiles=[...files],dynamicAnswers=Object.entries(answers).map(([fieldId,value])=>({fieldId,value:Array.isArray(value)?null:value,optionIds:Array.isArray(value)?value:[]}));
  if(attachmentField?.required&&!submittedFiles.length)throw new Error("Debes adjuntar al menos un archivo para radicar esta solicitud.");
  const created=await apiRequest<{id:string;number:string;dueDate:string}>("/api/solicitudes/requests",{method:"POST",body:JSON.stringify({serviceId,subject:submittedSubject,description,answers:dynamicAnswers,hasAttachments:submittedFiles.length>0})});
  const optimistic:Request={id:created.id,number:created.number,subject:submittedSubject,service:selectedService?.name??"Servicio",status:"Radicada",statusColor:null,isFinal:false,submittedAt:new Date().toISOString(),dueDate:created.dueDate};
  const uploadResults:PromiseSettledResult<unknown>[]=[];
  for(const file of submittedFiles){const body=new FormData();body.append("file",file);body.append("visibility","requester");try{uploadResults.push({status:"fulfilled",value:await apiRequest(`/api/solicitudes/requests/${created.id}/attachments`,{method:"POST",body})})}catch(reason){uploadResults.push({status:"rejected",reason})}}
  setPortal(current=>current?{...current,open:current.open+1,requests:[optimistic,...current.requests.filter(item=>item.id!==created.id)]}:current);
  setAreaId("");setServiceId("");setFiles([]);setServiceForm(null);setAnswers({});setConfirming(false);if(requestPanel.current)requestPanel.current.open=false;
  const failedUploads=uploadResults.filter((item):item is PromiseRejectedResult=>item.status==="rejected");
  if(failedUploads.length){const details=[...new Set(failedUploads.map(item=>item.reason instanceof Error?item.reason.message:"No fue posible almacenar el archivo."))].join(" ");setResult("");setError(`La solicitud ${created.number} quedó radicada, pero no se cargaron todos los adjuntos. ${details}`)}else setResult(`Solicitud ${created.number} radicada correctamente${submittedFiles.length?" con sus adjuntos":""}.`);
  try{const refreshed=await apiRequest<Portal>("/api/solicitudes/portal",{cache:"no-store"});setPortal({...refreshed,requests:refreshed.requests.some(item=>item.id===created.id)?refreshed.requests:[optimistic,...refreshed.requests]})}catch{/* La fila optimista permanece visible si Dataverse tarda en reflejarla. */}
 }catch(reason){setError(reason instanceof Error?reason.message:"No fue posible radicar la solicitud.")}finally{setSaving(false)}
}
 function closeDetail(){detailLoadVersion.current+=1;setDetailLoading(null);setDetail(null);setWorkflow(null);setAttachments([])}
 async function openRequest(id:string,summary?:Request){const version=++detailLoadVersion.current;setError("");setDetail(null);setWorkflow(null);setAttachments([]);setDetailLoading(summary??portal?.requests.find(item=>item.id===id)??null);try{const[data,fileRows,workflowData]=await Promise.all([apiRequest<Detail>(`/api/solicitudes/requests/${id}`,{cache:"no-store"}),apiRequest<Attachment[]>(`/api/solicitudes/requests/${id}/attachments`,{cache:"no-store"}),apiRequest<Workflow>(`/api/solicitudes/requests/${id}/workflow`,{cache:"no-store"}).catch(()=>null)]);if(version!==detailLoadVersion.current)return;setDetail(data);setAttachments(fileRows);setWorkflow(workflowData);setComment("");setResponseFiles([]);setResponseError("");setResponseSuccess("");setConfirmingResponse(false)}catch(reason){if(version!==detailLoadVersion.current)return;setError(reason instanceof Error?reason.message:"No fue posible abrir la solicitud.")}finally{if(version===detailLoadVersion.current)setDetailLoading(null)}}
 async function downloadRequestPdf(item:Request){if(pdfRequestId)return;setPdfRequestId(item.id);setError("");try{const[data,workflowData]=await Promise.all([apiRequest<Detail>(`/api/solicitudes/requests/${item.id}`,{cache:"no-store"}),apiRequest<Workflow>(`/api/solicitudes/requests/${item.id}/workflow`,{cache:"no-store"})]);await downloadClosurePdf({...data,managements:workflowData.managements})}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible descargar la constancia PDF.")}finally{setPdfRequestId(null)}}
  function postComment(event:FormEvent){event.preventDefault();if(!detail||!comment.trim())return;if(responseFiles.length>1){setResponseError("Puedes adjuntar máximo un documento.");return}setResponseError("");setConfirmingResponse(true)} async function attendObservation(){if(!detail)return;const waiting=workflow?.managements.find(item=>item.status===299540193);setPosting(true);setError("");try{if(!waiting)throw new Error("La gestión ya no está esperando tu respuesta. Actualiza la solicitud para consultar su estado actual.");let attachment:Attachment|null=null;if(responseFiles[0]){const body=new FormData();body.append("file",responseFiles[0]);body.append("visibility","requester");body.append("managementId",waiting.id);attachment=await apiRequest<Attachment>(`/api/solicitudes/requests/${detail.id}/attachments`,{method:"POST",body})}await apiRequest(`/api/solicitudes/workflows/${waiting.id}/requester-response`,{method:"POST",body:JSON.stringify({comment:comment.trim(),hasFile:Boolean(attachment)})});setComment("");setResponseFiles([]);setConfirmingResponse(false);await Promise.all([openRequest(detail.id),load()]);setWorkflow(current=>current?{...current,managements:current.managements.map(item=>item.id===waiting.id?{...item,status:299540191}:item)}:current);setResponseSuccess(`Tu respuesta fue enviada correctamente${attachment?" con su archivo":""}. La gestión volvió a quedar disponible para el equipo.`)}catch(reason){setResponseError(reason instanceof Error?reason.message:"No fue posible atender la observación.")}finally{setPosting(false)}}
 const requestItems=portal?.requests??[],requestCounts={all:requestItems.length,open:requestItems.filter(item=>requestFilter(item)==="open").length,tracking:requestItems.filter(item=>requestFilter(item)==="tracking").length,resolved:requestItems.filter(item=>requestFilter(item)==="resolved").length,closed:requestItems.filter(item=>requestFilter(item)==="closed").length};
 const term=search.trim().toLocaleLowerCase("es"),filteredRequests=[...requestItems].filter(item=>(requestState==="all"||requestFilter(item)===requestState)&&(!requestService||item.service===requestService)&&(!term||`${item.number} ${item.service} ${item.status}`.toLocaleLowerCase("es").includes(term))).sort((left,right)=>(new Date(right.submittedAt??0).getTime()-new Date(left.submittedAt??0).getTime())*(requestSort==="recent"?1:-1));
 const requestPages=Math.max(1,Math.ceil(filteredRequests.length/REQUEST_PAGE_SIZE)),visibleRequests=filteredRequests.slice((requestPage-1)*REQUEST_PAGE_SIZE,requestPage*REQUEST_PAGE_SIZE),configuredAttachment=serviceForm?.fields.find(isAttachmentField);
 function resetRequests(){setRequestPage(1);}
 return <section className={`intranet-solicitudes ${styles.page}`}>
  <header className={styles.header}>
   <div className={styles.heroCopy}><p className={styles.eyebrow}>Solicitudes Gaia</p><h1>Soporte cuando lo necesitas</h1><p>Crea una solicitud, haz seguimiento y recibe respuestas del equipo de servicios.</p><label className={styles.heroSearch}><Search size={19}/><input aria-label="Buscar en mis solicitudes" onChange={event=>{setSearch(event.target.value);resetRequests();}} placeholder="Buscar por número, servicio o estado…" type="search" value={search}/></label></div>
   <blockquote>“Soluciones hoy<br/>para un mejor mañana”<small>Gaia Amazonas</small></blockquote>
  </header>
  <div className={styles.newRequest}>
   <details ref={requestPanel} id="solicitudes-new-request"><summary>Nueva solicitud</summary><form className="solicitudes-temporary-form" onSubmit={submit}>
    <header className="solicitudes-form-header"><span><ShieldCheck size={16}/> Radicación segura en Gaia</span><button aria-label="Cerrar nueva solicitud" disabled={saving} onClick={()=>{if(requestPanel.current)requestPanel.current.open=false}} type="button"><X size={18}/></button></header>
    {portalLoading&&<p className="solicitudes-form-loading" role="status"><LoaderCircle className="animate-spin" size={18}/> Estamos cargando las áreas y servicios…</p>}
    {portalError&&!portalLoading&&<div className="solicitudes-form-loading" role="alert"><span>{portalError}</span><button onClick={()=>void load()} type="button">Reintentar</button></div>}
    <label>Área<select disabled={portalLoading} onChange={event=>chooseArea(event.target.value)} required value={areaId}><option value="">{portalError?"No se pudieron cargar las áreas":"Selecciona un área"}</option>{(portal?.areas??[]).map(item=><option key={item.id} value={item.id}>{item.shortName}</option>)}</select></label>
    {areaId&&<label>Servicio<select onChange={event=>void chooseService(event.target.value)} required value={serviceId}><option value="">Selecciona un servicio</option>{(portal?.services??[]).filter(item=>item.areaId===areaId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
    {serviceId&&<>{loadingForm&&<p className="solicitudes-form-loading" role="status"><LoaderCircle className="animate-spin" size={18}/> Estamos cargando el formulario del servicio…</p>}{serviceForm?<fieldset className="solicitudes-dynamic-fields"><legend>{serviceForm.title}</legend>{serviceForm.instructions&&<p>{serviceForm.instructions}</p>}{serviceForm.fields.filter(field=>!isAttachmentField(field)).map(field=><DynamicField change={value=>setAnswers(current=>({...current,[field.id]:value}))} field={field} key={field.id} value={answers[field.id]}/>)}</fieldset>:!loadingForm&&<p className="solicitudes-form-loading" role="alert">Este servicio todavía no tiene un formulario publicado.</p>}{serviceForm&&<>{configuredAttachment&&<label>{configuredAttachment.label}{configuredAttachment.required?" *":" (opcional)"}<input accept={configuredAttachment.allowedFileTypes??".pdf,.png,.jpg,.jpeg,.docx,.xlsx"} key={serviceId} multiple={configuredAttachment.allowsMultiple} onChange={event=>setFiles(Array.from(event.target.files??[]))} required={configuredAttachment.required} type="file"/>{configuredAttachment.helpText&&<small>{configuredAttachment.helpText}</small>}</label>}<button disabled={saving} type="submit">Radicar solicitud</button></>}</>}
   </form></details>
  </div>
  {error&&<p className="solicitudes-load-message" role="alert">{error}</p>}{result&&<p className="solicitudes-success-message" role="status">{result}</p>}
  <section className={styles.requestsPanel} id="solicitudes-my-requests" tabIndex={-1}>
   <header className={styles.panelHeader}><div><p className={styles.eyebrow}>Seguimiento personal</p><h2>Mis solicitudes</h2><p>Consulta, da seguimiento y gestiona tus solicitudes en un solo lugar.</p></div><button aria-busy={requestOpening} className={styles.primary} disabled={requestOpening} onClick={()=>startRequest()} type="button">{requestOpening?<LoaderCircle className="animate-spin" size={17}/>:<Plus size={17}/>} {requestOpening?"Abriendo…":"Nueva solicitud"}</button></header>
   <nav aria-label="Filtrar solicitudes por estado" className={styles.tabs}>{([{key:"all",label:"Todas"},{key:"open",label:"Abiertas"},{key:"tracking",label:"En seguimiento"},{key:"resolved",label:"Resueltas"},{key:"closed",label:"Cerradas"}] as const).map(tab=><button aria-pressed={requestState===tab.key} className={requestState===tab.key?styles.activeTab:""} key={tab.key} onClick={()=>{setRequestState(tab.key);resetRequests();}} type="button">{tab.label}<span>{requestCounts[tab.key]}</span></button>)}</nav>
   <div className={styles.filters}><span><SlidersHorizontal size={16}/>Filtrar resultados</span><select aria-label="Filtrar por servicio" onChange={event=>{setRequestService(event.target.value);resetRequests();}} value={requestService}><option value="">Todos los servicios</option>{[...new Set((portal?.requests??[]).map(item=>item.service))].sort().map(service=><option key={service}>{service}</option>)}</select><label><ArrowDownUp size={15}/><select aria-label="Ordenar solicitudes" onChange={event=>{setRequestSort(event.target.value as "recent"|"oldest");resetRequests();}} value={requestSort}><option value="recent">Más recientes</option><option value="oldest">Más antiguas</option></select></label></div>
   {visibleRequests.length?<><div className={styles.tableWrap}><table><thead><tr><th>Solicitud</th><th>Fecha límite de atención</th><th>Servicio</th><th>Estado</th><th>Radicada</th><th>Acciones</th></tr></thead><tbody>{visibleRequests.map(item=>{const filter=requestFilter(item),canDownloadPdf=/cerrad|resuelt|solucionad/.test(item.status.toLocaleLowerCase("es"));return <tr key={item.id}><td><strong>{item.number}</strong></td><td>{formatDueDate(item.dueDate)}</td><td><span className={styles.serviceCell}><Laptop size={16}/>{item.service}</span></td><td><span className={`${styles.status} ${styles[filter]}`}><i/>{item.status}</span></td><td>{formatRequestDate(item.submittedAt)}</td><td><button aria-label={`Ver ${item.number}`} onClick={()=>void openRequest(item.id)} type="button"><Eye size={15}/>Ver</button>{canDownloadPdf&&<button aria-label={`Descargar constancia PDF de ${item.number}`} className={styles.pdfAction} disabled={Boolean(pdfRequestId)} onClick={()=>void downloadRequestPdf(item)} title="Descargar constancia PDF" type="button">{pdfRequestId===item.id?<LoaderCircle className="animate-spin" size={15}/>:<FileDown size={15}/>}</button>}</td></tr>})}</tbody></table></div><footer className={styles.pagination}><span>Mostrando {(requestPage-1)*REQUEST_PAGE_SIZE+1}–{Math.min(requestPage*REQUEST_PAGE_SIZE,filteredRequests.length)} de {filteredRequests.length}</span><nav aria-label="Páginas de solicitudes"><button aria-label="Página anterior" disabled={requestPage===1} onClick={()=>setRequestPage(page=>page-1)} type="button"><ArrowLeft size={16}/></button><strong aria-current="page">{requestPage}</strong><button aria-label="Página siguiente" disabled={requestPage===requestPages} onClick={()=>setRequestPage(page=>page+1)} type="button"><ArrowRight size={16}/></button></nav></footer></>:<div className={styles.empty}><Inbox size={27}/><strong>{portal?"No hay solicitudes para estos filtros":error?"No pudimos consultar tus solicitudes":"Consultando tus solicitudes…"}</strong><p>{portal?requestCounts.all?"Prueba con otro estado, servicio o término de búsqueda.":"Aquí aparecerán tus solicitudes con su estado y las respuestas del equipo.":error?"Intenta cargar la página nuevamente.":"En un momento podrás revisar tu actividad."}</p>{portal&&!requestCounts.all&&<button onClick={()=>startRequest()} type="button"><Plus size={16}/>Crear mi primera solicitud</button>}</div>}
  </section>
        {detailLoading&&!detail&&<div className="solicitudes-detail-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)closeDetail()}}><section className="solicitudes-detail solicitudes-observation-detail" role="dialog" aria-modal="true" aria-label={`Cargando solicitud ${detailLoading.number}`}><header><span><small>{detailLoading.number} · {detailLoading.service}</small><h2>{detailLoading.subject}</h2></span><button aria-label="Cerrar detalle" onClick={closeDetail} type="button">×</button></header><div className="solicitudes-detail-loading" role="status"><LoaderCircle className="animate-spin" size={30}/><strong>Cargando gestión de la solicitud</strong><p>Estamos consultando el recorrido, las decisiones y los archivos asociados.</p></div></section></div>}
        {detail&&<div className="solicitudes-detail-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)closeDetail()}}><section className="solicitudes-detail solicitudes-observation-detail" role="dialog" aria-modal="true" aria-label={`Solicitud ${detail.number}`}><header><span><small>{detail.number} · {detail.service}</small><h2>{detail.subject}</h2></span><button aria-label="Cerrar detalle" onClick={closeDetail} type="button">×</button></header><p>{detail.description}</p><div className="solicitudes-detail-meta"><span>Estado <strong>{detail.status}</strong></span><span>Fecha límite <strong>{detail.dueDate||"Por definir"}</strong></span></div>{workflow?.status===299540182&&<button className="solicitudes-closure-download" onClick={()=>downloadClosurePdf({...detail,managements:workflow.managements})} type="button"><FileDown size={17}/>Descargar constancia de atención PDF</button>}{workflow&&<div className="solicitudes-route-map"><WorkflowRouteMap workflow={workflow}/><StageDecisionHistory managements={workflow.managements}/></div>}<h3>Conversación</h3><div className="solicitudes-comments">{detail.comments.length?detail.comments.map(item=><article className={item.isMine||item.authorRole?.trim().toLocaleLowerCase("es")==="solicitante"?"requester":"team"} key={item.id}><small>{item.authorRole}{item.isInternal?" · Nota interna":""} · {new Date(item.publishedAt).toLocaleString("es-CO")}</small><p>{item.content}</p></article>):<p>Aún no hay comentarios.</p>}</div>{workflow?.managements.some(item=>item.status===299540193)&&<form onSubmit={postComment}><textarea maxLength={4000} minLength={2} onChange={event=>setComment(event.target.value)} placeholder="Escribe la información solicitada" required rows={3} value={comment}/><label className="solicitudes-response-files">Adjuntar documento <small>(opcional)</small><input accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx" onChange={event=>setResponseFiles(Array.from(event.target.files??[]))} type="file"/>{responseFiles.length>0?<small>{responseFiles.length} archivo seleccionado</small>:<small>Haz clic aquí si necesitas anexar un soporte.</small>}</label>{responseError&&!confirmingResponse&&<p className="solicitudes-response-error" role="alert">{responseError}</p>}<button disabled={posting} type="submit">{posting?"Atendiendo observación…":"Enviar respuesta"}</button></form>}<h3>Archivos</h3><AttachmentList attachments={attachments}/></section></div>}
  {responseSuccess&&<div className="solicitudes-confirm-overlay"><section className="solicitudes-confirm-dialog solicitudes-success-dialog" role="dialog" aria-modal="true" aria-labelledby="solicitudes-response-success-title"><CheckCircle2 size={38}/><h2 id="solicitudes-response-success-title">Respuesta enviada</h2><p>{responseSuccess}</p><div><button onClick={()=>{setResponseSuccess("");setDetail(null)}} type="button">Entendido</button></div></section></div>}{confirmingResponse&&<div className="solicitudes-confirm-overlay"><section className="solicitudes-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="solicitudes-response-confirm-title"><MessageSquareText size={30}/><h2 id="solicitudes-response-confirm-title">¿Atender esta observación?</h2><p>Tu respuesta{responseFiles.length?` y ${responseFiles.length} archivo${responseFiles.length===1?"":"s"}`:""} se enviará al equipo gestor y la solicitud regresará al estado anterior para que el equipo pueda continuar gestionándola.</p>{posting&&<div className="solicitudes-saving"><LoaderCircle className="animate-spin" size={18}/>Estamos enviando tu respuesta…</div>}{responseError&&<p className="solicitudes-response-error" role="alert">{responseError}</p>}<div><button disabled={posting} onClick={()=>setConfirmingResponse(false)} type="button">Volver y revisar</button><button disabled={posting} onClick={()=>void attendObservation()} type="button">{posting?"Enviando…":"Sí, atender observación"}</button></div></section></div>}{confirming&&<div className="solicitudes-confirm-overlay"><section className="solicitudes-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="solicitudes-confirm-title"><ShieldCheck size={30}/><h2 id="solicitudes-confirm-title">¿Radicar esta solicitud?</h2><p>Verifica que el servicio, el asunto y todas las respuestas sean correctos. Al confirmar, la solicitud quedará radicada y será enviada al equipo responsable.</p>{saving&&<div className="solicitudes-saving"><LoaderCircle className="animate-spin" size={18}/>Estamos guardando y radicando tu solicitud…</div>}<div><button disabled={saving} onClick={()=>setConfirming(false)} type="button">Volver y revisar</button><button disabled={saving} onClick={()=>void confirmRequest()} type="button">{saving?"Radicando…":"Sí, radicar solicitud"}</button></div></section></div>}
 </section>;
}
