"use client";
import Link from "@/components/document-link";
import {ArrowRight,Cake,CalendarDays,ChevronLeft,ChevronRight,Grid2X2,LifeBuoy,PartyPopper,RotateCcw,Search} from "lucide-react";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {useSecurity} from "@/components/security-context";
import {apiRequest} from "@/lib/api-client";
import {applicationsFromModules} from "./intranet-applications";
const temporaryBannerImages=[
{desktop:"/banners/temporary/Img2.jpg",mobile:"/banners/temporary/Img2Mobile.jpg"},
{desktop:"/banners/temporary/Img3.jpg",mobile:"/banners/temporary/Img3Mobile.jpg"},
{desktop:"/banners/temporary/Img4.jpg",mobile:"/banners/temporary/Img4Mobile.jpg"},
] as const;
type Banner={id:string;eyebrow?:string;title:string;description?:string;destinationType:number;actionUrl?:string;eventId?:string;desktopImageUrl:string;mobileImageUrl:string};
type Event={id:string;name:string;type:string;color:string;startsAt:string;allDay:boolean};type Birthday={id:string;fullName:string;day:number;month:number};type Home={banners:Banner[];upcomingEvents:Event[];birthdays:Birthday[]};
const actions=[{href:"/intranet/helpdesk",label:"Nueva solicitud",detail:"Solicita ayuda",icon:LifeBuoy,permission:"INT.HELPDESK.VER"},{href:"/intranet/helpdesk",label:"Mis solicitudes",detail:"Consulta su estado",icon:LifeBuoy,permission:"INT.HELPDESK.VER"},{href:"/intranet/personas",label:"Buscar persona",detail:"Directorio interno",icon:Search,permission:"INT.PERSONAS.VER"},{href:"/intranet/calendario",label:"Consultar agenda",detail:"Eventos de Gaia",icon:CalendarDays,permission:"INT.CALENDARIO.VER"},{href:"/intranet/aplicaciones",label:"Explorar aplicaciones",detail:"Tus herramientas",icon:Grid2X2,permission:"INT.APLICACIONES.VER"}] as const;
export function IntranetHome(){const{can,user,modules}=useSecurity();const[data,setData]=useState<Home>({banners:[],upcomingEvents:[],birthdays:[]}),[loading,setLoading]=useState(true),[slide,setSlide]=useState(0),[ready,setReady]=useState(false),[celebrationReplay,setCelebrationReplay]=useState(0);const apps=useMemo(()=>applicationsFromModules(modules).slice(0,4),[modules]),today=new Date(),todayKey=`${today.getMonth()+1}-${today.getDate()}`,birthdaysToday=data.birthdays.filter(x=>`${x.month}-${x.day}`===todayKey).slice(0,4),future=useMemo(()=>groupBirthdays(data.birthdays,today).slice(0,4),[data.birthdays]),banner=data.banners.length?data.banners[slide%data.banners.length]:null,bannerImage=temporaryBannerImages[slide%temporaryBannerImages.length];useEffect(()=>{let active=true;apiRequest<Home>("/api/intranet/home",{cache:"no-store"}).catch(()=>loadHomeFallback(today)).then(value=>{if(active)setData(value)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);useEffect(()=>{setReady(false);if(!banner)return;const image=new window.Image();image.src=bannerImage.desktop;image.onload=()=>setReady(true);image.onerror=()=>setReady(true);return()=>{image.onload=null;image.onerror=null}},[banner,bannerImage.desktop]);useEffect(()=>{if(data.banners.length<2)return;const timer=window.setInterval(()=>setSlide(x=>(x+1)%data.banners.length),7000);return()=>window.clearInterval(timer)},[data.banners.length]);const date=new Intl.DateTimeFormat("es-CO",{weekday:"long",day:"numeric",month:"long"}).format(today),firstName=user?.name.split(" ").filter(Boolean)[0]??"equipo Gaia";return <div className="intranet-home intranet-home-redesign">
<section className="intranet-personal-welcome"><p>{date}</p><div><h1>Hola, {firstName}.</h1><h2>Esto es lo próximo en Gaia.</h2><span>Información útil para conectar con nuestro equipo y avanzar en el trabajo de hoy.</span></div></section>
{banner?<section className={`intranet-event-spotlight${ready?" is-ready":" is-loading"}`}><div className="intranet-event-background" style={ready?{"--banner-desktop":`url('${bannerImage.desktop}')`,"--banner-mobile":`url('${bannerImage.mobile}')`} as CSSProperties:undefined}/><div className="intranet-event-shade"/><div className="intranet-event-copy"><p>{banner.eyebrow||"Destacado Gaia"}</p><h2>{banner.title}</h2>{banner.description&&<span>{banner.description}</span>}<div><Link href={banner.destinationType===1&&banner.eventId?`/intranet/calendario?evento=${banner.eventId}`:banner.actionUrl||"/intranet"}>Ver detalle <ArrowRight size={15}/></Link></div></div>{data.banners.length>1&&<div className="intranet-event-controls"><button aria-label="Anterior" onClick={()=>setSlide(x=>(x-1+data.banners.length)%data.banners.length)}><ChevronLeft size={18}/></button><span>{slide+1} / {data.banners.length}</span><button aria-label="Siguiente" onClick={()=>setSlide(x=>(x+1)%data.banners.length)}><ChevronRight size={18}/></button></div>}</section>:<section className="intranet-event-spotlight intranet-event-spotlight-empty"><div><p>Destacados Gaia</p><h2>{loading?"Preparando la portada…":"No hay publicaciones vigentes"}</h2><span>{loading?"Estamos cargando la información institucional.":"Cuando Comunicaciones publique un destacado aparecerá aquí."}</span></div></section>}
<nav aria-label="Acciones rápidas" className="intranet-home-actions">{actions.filter(x=>can(x.permission)).map(x=>{const Icon=x.icon;return <Link href={x.href} key={x.label}><Icon size={18}/><span><strong>{x.label}</strong><small>{x.detail}</small></span><ArrowRight size={14}/></Link>})}</nav>
<section className="intranet-home-columns"><div className="intranet-home-news"><header className="intranet-section-title"><span><p>Actualidad</p><h2>Lo que está pasando</h2></span></header><div className="intranet-home-empty"><span className="intranet-home-empty-mark" aria-hidden="true"><i/><i/><i/></span><strong>Aún no hay comunicaciones para mostrar</strong><p>Este espacio reunirá las historias, novedades y anuncios que conectan a nuestro equipo.</p><div className="intranet-home-empty-topics" aria-label="Contenido que aparecerá aquí"><span>Noticias institucionales</span><span>Historias del equipo</span><span>Novedades Gaia</span></div></div></div><aside className="intranet-agenda"><header className="intranet-section-title"><span><p>Agenda</p><h2>Próximamente</h2></span><Link href="/intranet/calendario">Calendario <ArrowRight size={14}/></Link></header><div className="intranet-agenda-list">{data.upcomingEvents.slice(0,3).map(x=><article key={x.id}><time><strong>{new Date(x.startsAt).getDate()}</strong><small>{new Intl.DateTimeFormat("es-CO",{month:"short"}).format(new Date(x.startsAt))}</small></time><span><small style={{color:x.color}}>{x.type}</small><strong>{x.name}</strong><em>{x.allDay?"Todo el día":new Intl.DateTimeFormat("es-CO",{hour:"numeric",minute:"2-digit"}).format(new Date(x.startsAt))}</em></span></article>)}{!loading&&!data.upcomingEvents.length&&<p className="intranet-agenda-empty">No hay eventos próximos publicados.</p>}</div></aside></section>
<section className="intranet-home-lower"><article className={`intranet-home-birthdays${birthdaysToday.length?" has-celebrations":""}`} key={celebrationReplay}>{birthdaysToday.length>0&&<div aria-hidden="true" className="intranet-home-confetti">{Array.from({length:18},(_,index)=><i key={index}/>)}</div>}<span className="intranet-home-celebration-icon">{birthdaysToday.length?<PartyPopper size={22}/>:<Cake size={20}/>}</span><div><header><span><small>Celebraciones</small><h2>{birthdaysToday.length?"Hoy celebramos personas que hacen parte de Gaia":"Cada persona merece ser celebrada"}</h2></span><span className="intranet-home-birthday-actions">{birthdaysToday.length>0&&<button aria-label="Repetir celebración" onClick={()=>setCelebrationReplay(x=>x+1)} type="button"><RotateCcw size={12}/> Repetir</button>}<Link href="/intranet/calendario">Ver próximos</Link></span></header>{birthdaysToday.length?<><p className="intranet-home-birthday-message">¡Feliz cumpleaños! Gracias por compartir su talento, energía y camino con nuestro equipo. Que este nuevo año llegue lleno de bienestar y motivos para celebrar.</p><div className="intranet-home-birthday-names">{birthdaysToday.map(x=><span key={x.id}>{properName(x.fullName)}<small>Hoy es su día</small></span>)}</div></>:future.length?<p>Muy pronto tendremos un nuevo motivo para encontrarnos y celebrar: el {birthdayLabel(future[0][0])}. Aquí reconoceremos a quienes hacen especial nuestro equipo.</p>:<p>Hoy no tenemos cumpleaños registrados, pero este espacio estará listo para celebrar a cada persona cuando llegue su día.</p>}</div></article><article className="intranet-home-apps"><header><span><small>Herramientas</small><h2>Aplicaciones disponibles para ti</h2></span><Link href="/intranet/aplicaciones">Ver aplicaciones <ArrowRight size={14}/></Link></header>{apps.length?<div>{apps.map(app=><a href={app.href} key={app.code} rel="noopener noreferrer" target="_blank"><i>{app.initials}</i><span><strong>{app.name}</strong><small>{app.description}</small></span></a>)}</div>:<p>No tienes aplicaciones institucionales adicionales asignadas.</p>}</article></section></div>}
function properName(value:string){return value.toLocaleLowerCase("es").replace(/(^|\s)\p{L}/gu,x=>x.toLocaleUpperCase("es"))}function nextBirthday(x:Birthday,today:Date){const date=new Date(today.getFullYear(),x.month-1,x.day);if(date<new Date(today.getFullYear(),today.getMonth(),today.getDate()))date.setFullYear(date.getFullYear()+1);return date}function groupBirthdays(items:Birthday[],today:Date){const groups=new Map<string,Birthday[]>();for(const x of [...items].sort((a,b)=>nextBirthday(a,today).getTime()-nextBirthday(b,today).getTime())){const key=`${x.month}-${x.day}`;groups.set(key,[...(groups.get(key)??[]),x])}return [...groups.values()]}function birthdayLabel(x:Birthday){return new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"long"}).format(new Date(2024,x.month-1,x.day))}
async function loadHomeFallback(today:Date):Promise<Home>{const from=new Date(today);from.setHours(0,0,0,0);const until=new Date(from);until.setMonth(until.getMonth()+6);const month=today.getMonth()+1,nextMonth=month===12?1:month+1;const[banners,events,currentBirthdays,nextBirthdays]=await Promise.allSettled([apiRequest<Banner[]>("/api/intranet/banners",{cache:"no-store"}),apiRequest<Event[]>(`/api/intranet/events?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(until.toISOString())}`),apiRequest<Birthday[]>(`/api/intranet/birthdays?month=${month}`),apiRequest<Birthday[]>(`/api/intranet/birthdays?month=${nextMonth}`)]);return{banners:banners.status==="fulfilled"?banners.value:[],upcomingEvents:events.status==="fulfilled"?events.value.slice(0,3):[],birthdays:[...(currentBirthdays.status==="fulfilled"?currentBirthdays.value:[]),...(nextBirthdays.status==="fulfilled"?nextBirthdays.value:[])]}}
