"use client";
import Image from "next/image";
import Link from "@/components/document-link";
import {ArrowRight,Cake,CalendarDays,ChevronLeft,ChevronRight,GraduationCap,LifeBuoy,PartyPopper,RotateCcw,Search} from "lucide-react";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {useSecurity} from "@/components/security-context";
import {PersonAvatar} from "@/components/person-avatar";
import {apiRequest} from "@/lib/api-client";
import {applicationsFromModules,intranetApplications} from "./intranet-applications";
import {activeTrainingStatuses,trainingDueLabel,type TrainingAssignment} from "./training-assignment";
type Banner={id:string;eyebrow?:string;title:string;description?:string;destinationType:number;actionUrl?:string;eventId?:string;desktopImageUrl:string;mobileImageUrl:string};
type Event={id:string;name:string;type:string;color:string;startsAt:string;allDay:boolean};
type Birthday={id:string;fullName:string;day:number;month:number;photoUrl?:string|null};
type Home={banners:Banner[];upcomingEvents:Event[];birthdays:Birthday[]};
const temporaryBanners=[{desktop:"/banners/temporary/Img2.jpg",mobile:"/banners/temporary/Img2Mobile.jpg"},{desktop:"/banners/temporary/Img3.jpg",mobile:"/banners/temporary/Img3Mobile.jpg"},{desktop:"/banners/temporary/Img4.jpg",mobile:"/banners/temporary/Img4Mobile.jpg"}] as const;
const actions=[{href:"/intranet/capacitaciones",label:"Mis capacitaciones",detail:"Continúa tu aprendizaje",icon:GraduationCap,permission:"INT.CAPACITACIONES.VER"},{href:"/intranet/helpdesk",label:"Mis solicitudes",detail:"Consulta su estado",icon:LifeBuoy,permission:"INT.HELPDESK.VER"},{href:"/intranet/personas",label:"Buscar persona",detail:"Directorio interno",icon:Search,permission:"INT.PERSONAS.VER"},{href:"/intranet/calendario",label:"Consultar agenda",detail:"Eventos de Gaia",icon:CalendarDays,permission:"INT.CALENDARIO.VER"}] as const;

export function IntranetHome(){
 const{can,user,modules}=useSecurity();
 const[data,setData]=useState<Home>({banners:[],upcomingEvents:[],birthdays:[]}),[training,setTraining]=useState<TrainingAssignment[]>([]),[trainingError,setTrainingError]=useState(""),[trainingReady,setTrainingReady]=useState(false),[loading,setLoading]=useState(true),[slide,setSlide]=useState(0),[ready,setReady]=useState(false),[celebrationReplay,setCelebrationReplay]=useState(0),[birthdayPage,setBirthdayPage]=useState(0),[actionPage,setActionPage]=useState(0),[eventPage,setEventPage]=useState(0),[appPage,setAppPage]=useState(0),[trainingPage,setTrainingPage]=useState(0),[actionSize,setActionSize]=useState(4);
 const[today]=useState(()=>new Date()),todayKey=`${today.getMonth()+1}-${today.getDate()}`,birthdaysToday=data.birthdays.filter(item=>`${item.month}-${item.day}`===todayKey).slice(0,5);
 const upcomingBirthdays=useMemo(()=>data.birthdays.filter(item=>`${item.month}-${item.day}`!==todayKey).sort((left,right)=>nextBirthday(left,today).getTime()-nextBirthday(right,today).getTime()),[data.birthdays,today,todayKey]);
 const birthdayPages=Math.max(1,Math.ceil(upcomingBirthdays.length/3)),visibleBirthdays=upcomingBirthdays.slice((birthdayPage%birthdayPages)*3,(birthdayPage%birthdayPages)*3+3);
 const apps=useMemo(()=>[...new Map([...applicationsFromModules(modules),...intranetApplications].map(item=>[item.code,item])).values()],[modules]);
 const banner=data.banners.length?data.banners[slide%data.banners.length]:null,localBanner=temporaryBanners[slide%temporaryBanners.length];
 useEffect(()=>{const media=window.matchMedia("(max-width: 768px)");const resize=()=>{setActionSize(media.matches?1:4);setActionPage(0)};resize();media.addEventListener("change",resize);return()=>media.removeEventListener("change",resize)},[]);
 useEffect(()=>{let active=true;apiRequest<Home>("/api/intranet/home",{cache:"no-store"}).catch(()=>loadHomeFallback(today)).then(value=>{if(active)setData(value)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[today]);
 useEffect(()=>{if(!can("INT.CAPACITACIONES.VER"))return;let active=true;apiRequest<TrainingAssignment[]>("/api/training/my/assignments",{cache:"no-store"}).then(value=>{if(active){setTraining(value);setTrainingReady(true);setTrainingError("")}}).catch(()=>{if(active){setTrainingError("No fue posible actualizar tus capacitaciones. Abre Mis capacitaciones para reintentar.");setTrainingReady(true)}});return()=>{active=false}},[can]);
 useEffect(()=>{if(!banner)return;const image=new window.Image();image.src=localBanner.desktop;image.onload=()=>setReady(true);image.onerror=()=>setReady(true);return()=>{image.onload=null;image.onerror=null}},[banner,localBanner.desktop]);
 useEffect(()=>{if(data.banners.length<2)return;const timer=window.setInterval(()=>setSlide(value=>(value+1)%data.banners.length),7000);return()=>window.clearInterval(timer)},[data.banners.length]);
 const firstName=user?.name.split(" ").filter(Boolean)[0]??"equipo Gaia",eventPages=Math.max(1,Math.ceil(data.upcomingEvents.length/2)),visibleActions=actions.filter(item=>can(item.permission)),activeTraining=training.filter(item=>activeTrainingStatuses.has(item.status)),nextTraining=activeTraining.sort((left,right)=>(left.dueAt??"9999").localeCompare(right.dueAt??"9999"))[trainingPage%Math.max(1,activeTraining.length)];
 return <div className="intranet-home intranet-home-redesign">
 {banner?<section className={`intranet-event-spotlight${ready?" is-ready":" is-loading"}`}><div className="intranet-event-background" style={ready?{"--banner-desktop":`url('${localBanner.desktop}')`,"--banner-mobile":`url('${localBanner.mobile}')`} as CSSProperties:undefined}/><div className="intranet-event-shade"/><div className="intranet-event-copy"><div className="intranet-event-user"><PersonAvatar currentUser name={user?.name??"Usuario Gaia"} size={42}/><span className="intranet-event-greeting">Hola, {firstName}</span></div><p>{banner.eyebrow||"Próximo en Gaia"}</p><h2>{banner.title}</h2>{banner.description&&<span>{banner.description}</span>}<div><Link href={banner.destinationType===1&&banner.eventId?`/intranet/calendario?evento=${banner.eventId}`:banner.actionUrl||"/intranet"}>Ver detalle <ArrowRight size={15}/></Link></div></div>{data.banners.length>1&&<div className="intranet-event-controls"><button aria-label="Anterior" onClick={()=>setSlide(value=>(value-1+data.banners.length)%data.banners.length)}><ChevronLeft size={18}/></button><span>{slide+1} / {data.banners.length}</span><button aria-label="Siguiente" onClick={()=>setSlide(value=>(value+1)%data.banners.length)}><ChevronRight size={18}/></button></div>}</section>:<section className="intranet-event-spotlight intranet-event-spotlight-empty"><div><p>Destacados Gaia</p><h2>{loading?"Preparando la portada…":"No hay publicaciones vigentes"}</h2><span>{loading?"Estamos cargando la información institucional.":"Cuando Comunicaciones publique un destacado aparecerá aquí."}</span></div></section>}
 <nav aria-label="Acciones rápidas" className="intranet-home-actions">{visibleActions.slice(actionPage*actionSize,actionPage*actionSize+actionSize).map(item=>{const Icon=item.icon;return <Link href={item.href} key={item.label}><Icon size={18}/><span><strong>{item.label}</strong><small>{item.detail}</small></span><ArrowRight size={14}/></Link>})}{visibleActions.length>actionSize&&<HomePager label="Accesos rápidos" page={actionPage} pages={Math.ceil(visibleActions.length/actionSize)} change={setActionPage}/>}</nav>
 <section className="intranet-home-primary"><article className={`intranet-home-birthdays${birthdaysToday.length?" has-celebrations":""}`} key={celebrationReplay}><div aria-hidden="true" className="intranet-home-confetti">{Array.from({length:18},(_,index)=><i key={index}/>)}</div><span className="intranet-home-celebration-icon">{birthdaysToday.length?<PartyPopper size={22}/>:<Cake size={20}/>}</span><div className="intranet-home-birthday-copy"><header><span><small>Celebraciones</small><h2>{birthdaysToday.length?"Hoy celebramos personas que hacen parte de Gaia":"Cada persona merece ser celebrada"}</h2></span><span className="intranet-home-birthday-actions">{birthdaysToday.length>0&&<button aria-label="Repetir celebración" onClick={()=>setCelebrationReplay(value=>value+1)} type="button"><RotateCcw size={12}/> Repetir</button>}<Link href="/intranet/calendario">Ver próximos</Link></span></header>{birthdaysToday.length?<><p className="intranet-home-birthday-message">¡Feliz cumpleaños! Gracias por compartir su talento, energía y camino con nuestro equipo. Que este nuevo año llegue lleno de bienestar y motivos para celebrar.</p><div className="intranet-home-birthday-names">{birthdaysToday.map(item=><span key={item.id}>{properName(item.fullName)}<small>Hoy es su día</small></span>)}</div></>:upcomingBirthdays.length?<p>Muy pronto tendremos un nuevo motivo para celebrar: el {birthdayLabel(upcomingBirthdays[0])}.</p>:<p>Hoy no tenemos cumpleaños registrados, pero este espacio estará listo para celebrar a cada persona cuando llegue su día.</p>}</div>{birthdaysToday.length>0&&<div aria-label="Fotografías institucionales de celebración" className="intranet-home-birthday-portraits">{birthdaysToday.map(item=><PersonAvatar className="intranet-home-birthday-photo" key={item.id} name={item.fullName} personId={item.id} size={192}/>)}</div>}</article>
 <aside className="intranet-agenda"><header className="intranet-section-title"><span><p>Agenda</p><h2>Próximamente</h2></span><Link href="/intranet/calendario">Calendario <ArrowRight size={14}/></Link></header><div className="intranet-agenda-list">{data.upcomingEvents.slice((eventPage%eventPages)*2,(eventPage%eventPages)*2+2).map(item=><article key={item.id}><time><strong>{new Date(item.startsAt).getDate()}</strong><small>{new Intl.DateTimeFormat("es-CO",{month:"short"}).format(new Date(item.startsAt))}</small></time><span><small style={{color:item.color}}>{item.type}</small><strong>{item.name}</strong><em>{item.allDay?"Todo el día":new Intl.DateTimeFormat("es-CO",{hour:"numeric",minute:"2-digit"}).format(new Date(item.startsAt))}</em></span></article>)}{eventPages>1&&<HomePager label="Agenda" page={eventPage%eventPages} pages={eventPages} change={setEventPage}/>}{!loading&&!data.upcomingEvents.length&&<p className="intranet-agenda-empty">No hay eventos próximos publicados.</p>}</div></aside></section>
 <section className="intranet-home-support"><article className="intranet-home-week"><header><span><small>Cumpleaños próximos</small><h2>Personas que celebraremos</h2></span><Link href="/intranet/calendario">Ver agenda <ArrowRight size={14}/></Link></header>{visibleBirthdays.length?<div>{visibleBirthdays.map(item=><span key={`${item.id}-${item.month}-${item.day}`}><PersonAvatar className="intranet-home-week-photo" name={item.fullName} personId={item.id} size={52}/><strong>{shortName(item.fullName)}</strong><small>{birthdayLabel(item)}</small></span>)}{birthdayPages>1&&<HomePager label="Cumpleaños próximos" page={birthdayPage%birthdayPages} pages={birthdayPages} change={setBirthdayPage}/>}</div>:<p>No hay próximos cumpleaños registrados.</p>}</article>{can("INT.CAPACITACIONES.VER")&&<article className="intranet-home-training"><header><span><small>Aprendizaje</small><h2>Mis capacitaciones</h2></span><Link href="/intranet/capacitaciones">Ver todas <ArrowRight size={14}/></Link></header>{trainingError?<div className="intranet-home-training-empty" role="status"><p>{trainingError}</p></div>:!trainingReady?<div className="intranet-home-training-empty"><p>Cargando tus capacitaciones…</p></div>:nextTraining?<><div className="intranet-home-training-icon"><GraduationCap size={21}/><b>{activeTraining.length}</b></div><strong>{nextTraining.training}</strong><p>{nextTraining.progress}% completado · {trainingDueLabel(nextTraining.dueAt)}</p><Link className="intranet-home-training-action" href={`/intranet/capacitaciones?asignacion=${encodeURIComponent(nextTraining.assignmentId)}`}>{nextTraining.progress?"Continuar capacitación":"Comenzar ahora"} <ArrowRight size={14}/></Link>{activeTraining.length>1&&<HomePager label="Capacitaciones pendientes" page={trainingPage%activeTraining.length} pages={activeTraining.length} change={setTrainingPage}/>}</>:<div className="intranet-home-training-empty"><GraduationCap size={22}/><p>No tienes capacitaciones pendientes. Las próximas asignaciones aparecerán aquí.</p></div>}</article>}
 <article className="intranet-home-apps"><header><span><small>Aplicaciones destacadas</small><h2>Tus herramientas</h2></span><Link href="/intranet/aplicaciones">Ver todas <ArrowRight size={14}/></Link></header>{apps.length?<div>{apps.slice(appPage*3,appPage*3+3).map(app=><a href={app.href} key={app.code} rel="noopener noreferrer" target="_blank">{app.logoUrl?<Image alt="" height={42} src={app.logoUrl} width={42}/>:<i>{app.initials}</i>}<span><strong>{app.name}</strong><small>{app.description}</small></span></a>)}</div>:<p>No tienes aplicaciones institucionales adicionales asignadas.</p>}{apps.length>3&&<HomePager label="Herramientas" page={appPage} pages={Math.ceil(apps.length/3)} change={setAppPage}/>}</article>
 </section></div>;
}
function properName(value:string){return value.toLocaleLowerCase("es").replace(/(^|\s)\p{L}/gu,letter=>letter.toLocaleUpperCase("es"))}
function shortName(value:string){return properName(value).split(/\s+/).slice(0,2).join(" ")}
function nextBirthday(item:Birthday,today:Date){const date=new Date(today.getFullYear(),item.month-1,item.day);if(date<new Date(today.getFullYear(),today.getMonth(),today.getDate()))date.setFullYear(date.getFullYear()+1);return date}
function birthdayLabel(item:Birthday){return new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"short"}).format(new Date(2024,item.month-1,item.day))}
async function loadHomeFallback(today:Date):Promise<Home>{const from=new Date(today);from.setHours(0,0,0,0);const until=new Date(from);until.setMonth(until.getMonth()+6);const month=today.getMonth()+1,nextMonth=month===12?1:month+1;const[banners,events,currentBirthdays,nextBirthdays]=await Promise.allSettled([apiRequest<Banner[]>("/api/intranet/banners",{cache:"no-store"}),apiRequest<Event[]>(`/api/intranet/events?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(until.toISOString())}`),apiRequest<Birthday[]>(`/api/intranet/birthdays?month=${month}`),apiRequest<Birthday[]>(`/api/intranet/birthdays?month=${nextMonth}`)]);return{banners:banners.status==="fulfilled"?banners.value:[],upcomingEvents:events.status==="fulfilled"?events.value.slice(0,12):[],birthdays:[...(currentBirthdays.status==="fulfilled"?currentBirthdays.value:[]),...(nextBirthdays.status==="fulfilled"?nextBirthdays.value:[])]}}
function HomePager({label,page,pages,change}:{label:string;page:number;pages:number;change:(value:number)=>void}){return <div className="intranet-home-pager" aria-label={label}><button type="button" aria-label={"Anterior: "+label} disabled={page<=0} onClick={()=>change(page-1)}><ChevronLeft size={16}/></button><span aria-live="polite">{page+1} / {pages}</span><button type="button" aria-label={"Siguiente: "+label} disabled={page>=pages-1} onClick={()=>change(page+1)}><ChevronRight size={16}/></button></div>}
