"use client";
import Image from "next/image";
import Link from "@/components/document-link";
import {ArrowRight,Cake,CalendarDays,ChevronLeft,ChevronRight,Grid2X2,LifeBuoy,PartyPopper,RotateCcw,Search} from "lucide-react";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {useSecurity} from "@/components/security-context";
import {apiRequest} from "@/lib/api-client";
import {applicationsFromModules,intranetApplications} from "./intranet-applications";
type Banner={id:string;eyebrow?:string;title:string;description?:string;destinationType:number;actionUrl?:string;eventId?:string;desktopImageUrl:string;mobileImageUrl:string};
type Event={id:string;name:string;type:string;color:string;startsAt:string;allDay:boolean};
type Birthday={id:string;fullName:string;day:number;month:number;photoUrl?:string|null};
type Home={banners:Banner[];upcomingEvents:Event[];birthdays:Birthday[]};
const temporaryBanners=[{desktop:"/banners/temporary/Img2.jpg",mobile:"/banners/temporary/Img2Mobile.jpg"},{desktop:"/banners/temporary/Img3.jpg",mobile:"/banners/temporary/Img3Mobile.jpg"},{desktop:"/banners/temporary/Img4.jpg",mobile:"/banners/temporary/Img4Mobile.jpg"}] as const;
const portraits=Array.from({length:5},(_,index)=>`/people/temporary-avatar-${index+1}.svg`);
const actions=[{href:"/intranet/helpdesk",label:"Nueva solicitud",detail:"Solicita ayuda",icon:LifeBuoy,permission:"INT.HELPDESK.VER"},{href:"/intranet/helpdesk",label:"Mis solicitudes",detail:"Consulta su estado",icon:LifeBuoy,permission:"INT.HELPDESK.VER"},{href:"/intranet/personas",label:"Buscar persona",detail:"Directorio interno",icon:Search,permission:"INT.PERSONAS.VER"},{href:"/intranet/calendario",label:"Consultar agenda",detail:"Eventos de Gaia",icon:CalendarDays,permission:"INT.CALENDARIO.VER"},{href:"/intranet/aplicaciones",label:"Explorar aplicaciones",detail:"Tus herramientas",icon:Grid2X2,permission:"INT.APLICACIONES.VER"}] as const;

export function IntranetHome(){
 const{can,user,modules}=useSecurity();
 const[data,setData]=useState<Home>({banners:[],upcomingEvents:[],birthdays:[]}),[loading,setLoading]=useState(true),[slide,setSlide]=useState(0),[ready,setReady]=useState(false),[celebrationReplay,setCelebrationReplay]=useState(0),[birthdayPage,setBirthdayPage]=useState(0);
 const today=useMemo(()=>new Date(),[]),todayKey=`${today.getMonth()+1}-${today.getDate()}`,birthdaysToday=data.birthdays.filter(item=>`${item.month}-${item.day}`===todayKey).slice(0,5);
 const upcomingBirthdays=useMemo(()=>data.birthdays.filter(item=>`${item.month}-${item.day}`!==todayKey).sort((left,right)=>nextBirthday(left,today).getTime()-nextBirthday(right,today).getTime()),[data.birthdays,today,todayKey]);
 const birthdayPages=Math.max(1,Math.ceil(upcomingBirthdays.length/5)),visibleBirthdays=upcomingBirthdays.slice((birthdayPage%birthdayPages)*5,(birthdayPage%birthdayPages)*5+5);
 const configured=useMemo(()=>applicationsFromModules(modules),[modules]),apps=useMemo(()=>[...new Map([...configured,...intranetApplications].map(item=>[item.code,item])).values()].slice(0,5),[configured]);
 const banner=data.banners.length?data.banners[slide%data.banners.length]:null,localBanner=temporaryBanners[slide%temporaryBanners.length];
 useEffect(()=>{let active=true;apiRequest<Home>("/api/intranet/home",{cache:"no-store"}).catch(()=>loadHomeFallback(today)).then(value=>{if(active)setData(value)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[today]);
 useEffect(()=>{if(!banner)return;const image=new window.Image();image.src=localBanner.desktop;image.onload=()=>setReady(true);image.onerror=()=>setReady(true);return()=>{image.onload=null;image.onerror=null}},[banner,localBanner.desktop]);
 useEffect(()=>{if(data.banners.length<2)return;const timer=window.setInterval(()=>setSlide(value=>(value+1)%data.banners.length),7000);return()=>window.clearInterval(timer)},[data.banners.length]);
 const firstName=user?.name.split(" ").filter(Boolean)[0]??"equipo Gaia",additionalEvents=Math.max(0,data.upcomingEvents.length-3);
 return <div className="intranet-home intranet-home-redesign">
 {banner?<section className={`intranet-event-spotlight${ready?" is-ready":" is-loading"}`}><div className="intranet-event-background" style={ready?{"--banner-desktop":`url('${localBanner.desktop}')`,"--banner-mobile":`url('${localBanner.mobile}')`} as CSSProperties:undefined}/><div className="intranet-event-shade"/><div className="intranet-event-copy"><span className="intranet-event-greeting">Hola, {firstName}</span><p>{banner.eyebrow||"Próximo en Gaia"}</p><h2>{banner.title}</h2>{banner.description&&<span>{banner.description}</span>}<div><Link href={banner.destinationType===1&&banner.eventId?`/intranet/calendario?evento=${banner.eventId}`:banner.actionUrl||"/intranet"}>Ver detalle <ArrowRight size={15}/></Link></div></div>{data.banners.length>1&&<div className="intranet-event-controls"><button aria-label="Anterior" onClick={()=>setSlide(value=>(value-1+data.banners.length)%data.banners.length)}><ChevronLeft size={18}/></button><span>{slide+1} / {data.banners.length}</span><button aria-label="Siguiente" onClick={()=>setSlide(value=>(value+1)%data.banners.length)}><ChevronRight size={18}/></button></div>}</section>:<section className="intranet-event-spotlight intranet-event-spotlight-empty"><div><p>Destacados Gaia</p><h2>{loading?"Preparando la portada…":"No hay publicaciones vigentes"}</h2><span>{loading?"Estamos cargando la información institucional.":"Cuando Comunicaciones publique un destacado aparecerá aquí."}</span></div></section>}
 <nav aria-label="Acciones rápidas" className="intranet-home-actions">{actions.filter(item=>can(item.permission)).map(item=>{const Icon=item.icon;return <Link href={item.href} key={item.label}><Icon size={18}/><span><strong>{item.label}</strong><small>{item.detail}</small></span><ArrowRight size={14}/></Link>})}</nav>
 <section className="intranet-home-primary"><article className={`intranet-home-birthdays${birthdaysToday.length?" has-celebrations":""}`} key={celebrationReplay}>{birthdaysToday.length>0&&<div aria-hidden="true" className="intranet-home-confetti">{Array.from({length:18},(_,index)=><i key={index}/>)}</div>}<span className="intranet-home-celebration-icon">{birthdaysToday.length?<PartyPopper size={22}/>:<Cake size={20}/>}</span><div className="intranet-home-birthday-copy"><header><span><small>Celebraciones</small><h2>{birthdaysToday.length?"Hoy celebramos personas que hacen parte de Gaia":"Cada persona merece ser celebrada"}</h2></span><span className="intranet-home-birthday-actions">{birthdaysToday.length>0&&<button aria-label="Repetir celebración" onClick={()=>setCelebrationReplay(value=>value+1)} type="button"><RotateCcw size={12}/> Repetir</button>}<Link href="/intranet/calendario">Ver próximos</Link></span></header>{birthdaysToday.length?<><p className="intranet-home-birthday-message">¡Feliz cumpleaños! Gracias por compartir su talento, energía y camino con nuestro equipo. Que este nuevo año llegue lleno de bienestar y motivos para celebrar.</p><div className="intranet-home-birthday-names">{birthdaysToday.map(item=><span key={item.id}>{properName(item.fullName)}<small>Hoy es su día</small></span>)}</div></>:upcomingBirthdays.length?<p>Muy pronto tendremos un nuevo motivo para celebrar: el {birthdayLabel(upcomingBirthdays[0])}.</p>:<p>Hoy no tenemos cumpleaños registrados, pero este espacio estará listo para celebrar a cada persona cuando llegue su día.</p>}</div>{birthdaysToday.length>0&&<div aria-label="Retratos temporales de celebración" className="intranet-home-birthday-portraits">{birthdaysToday.map((item,index)=><Image alt="Retrato temporal" height={180} key={item.id} src={portraits[index%portraits.length]} width={160}/>)}</div>}</article>
 <aside className="intranet-agenda"><header className="intranet-section-title"><span><p>Agenda</p><h2>Próximamente</h2></span><Link href="/intranet/calendario">Calendario <ArrowRight size={14}/></Link></header><div className="intranet-agenda-list">{data.upcomingEvents.slice(0,3).map(item=><article key={item.id}><time><strong>{new Date(item.startsAt).getDate()}</strong><small>{new Intl.DateTimeFormat("es-CO",{month:"short"}).format(new Date(item.startsAt))}</small></time><span><small style={{color:item.color}}>{item.type}</small><strong>{item.name}</strong><em>{item.allDay?"Todo el día":new Intl.DateTimeFormat("es-CO",{hour:"numeric",minute:"2-digit"}).format(new Date(item.startsAt))}</em></span></article>)}{additionalEvents>0&&<Link className="intranet-agenda-more" href="/intranet/calendario">Hay {additionalEvents} evento{additionalEvents===1?"":"s"} más <ArrowRight size={13}/></Link>}{!loading&&!data.upcomingEvents.length&&<p className="intranet-agenda-empty">No hay eventos próximos publicados.</p>}</div></aside></section>
 <section className="intranet-home-support"><article className="intranet-home-week"><header><span><small>Cumpleaños próximos</small><h2>Personas que celebraremos</h2></span><Link href="/intranet/calendario">Ver agenda <ArrowRight size={14}/></Link></header>{visibleBirthdays.length?<div>{visibleBirthdays.map((item,index)=><span key={`${item.id}-${item.month}-${item.day}`}><Image alt="Retrato temporal" height={54} src={portraits[(birthdayPage*5+index)%portraits.length]} width={54}/><strong>{shortName(item.fullName)}</strong><small>{birthdayLabel(item)}</small></span>)}{upcomingBirthdays.length>5&&<button aria-label="Ver los siguientes cumpleaños" onClick={()=>setBirthdayPage(value=>(value+1)%birthdayPages)} type="button"><b>+{Math.max(0,upcomingBirthdays.length-5)}</b><small>Más</small><ArrowRight size={14}/></button>}</div>:<p>No hay próximos cumpleaños registrados.</p>}</article>
 <article className="intranet-home-apps"><header><span><small>Aplicaciones destacadas</small><h2>Tus herramientas</h2></span><Link href="/intranet/aplicaciones">Ver todas <ArrowRight size={14}/></Link></header>{apps.length?<div>{apps.map(app=><a href={app.href} key={app.code} rel="noopener noreferrer" target="_blank">{app.logoUrl?<Image alt="" height={42} src={app.logoUrl} width={42}/>:<i>{app.initials}</i>}<span><strong>{app.name}</strong><small>{app.description}</small></span></a>)}</div>:<p>No tienes aplicaciones institucionales adicionales asignadas.</p>}</article>
 {can("INT.HELPDESK.VER")&&<article className="intranet-home-helpdesk"><LifeBuoy size={28}/><span><small>Helpdesk</small><h2>¿Necesitas ayuda?</h2><p>Crea una solicitud o consulta el estado de tus casos.</p><Link href="/intranet/helpdesk">Ir al Helpdesk <ArrowRight size={14}/></Link></span></article>}</section></div>;
}
function properName(value:string){return value.toLocaleLowerCase("es").replace(/(^|\s)\p{L}/gu,letter=>letter.toLocaleUpperCase("es"))}
function shortName(value:string){return properName(value).split(/\s+/).slice(0,2).join(" ")}
function nextBirthday(item:Birthday,today:Date){const date=new Date(today.getFullYear(),item.month-1,item.day);if(date<new Date(today.getFullYear(),today.getMonth(),today.getDate()))date.setFullYear(date.getFullYear()+1);return date}
function birthdayLabel(item:Birthday){return new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"short"}).format(new Date(2024,item.month-1,item.day))}
async function loadHomeFallback(today:Date):Promise<Home>{const from=new Date(today);from.setHours(0,0,0,0);const until=new Date(from);until.setMonth(until.getMonth()+6);const month=today.getMonth()+1,nextMonth=month===12?1:month+1;const[banners,events,currentBirthdays,nextBirthdays]=await Promise.allSettled([apiRequest<Banner[]>("/api/intranet/banners",{cache:"no-store"}),apiRequest<Event[]>(`/api/intranet/events?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(until.toISOString())}`),apiRequest<Birthday[]>(`/api/intranet/birthdays?month=${month}`),apiRequest<Birthday[]>(`/api/intranet/birthdays?month=${nextMonth}`)]);return{banners:banners.status==="fulfilled"?banners.value:[],upcomingEvents:events.status==="fulfilled"?events.value.slice(0,12):[],birthdays:[...(currentBirthdays.status==="fulfilled"?currentBirthdays.value:[]),...(nextBirthdays.status==="fulfilled"?nextBirthdays.value:[])]}}
