"use client";

import { type FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowDownUp, ArrowLeft, ArrowRight, CheckCircle2, Eye, FileDown, Inbox, Laptop, LoaderCircle, MessageSquareText, MoreHorizontal, Plus, Search, ShieldCheck, SlidersHorizontal, X } from "lucide-react";
import styles from "./intranet-solicitudes.module.css";
import { apiRequest } from "@/lib/api-client";
import { downloadClosurePdf } from "@/features/solicitudes/solicitudes-closure-pdf";

type Area={id:string;name:string;shortName:string;order:number};
type Service={id:string;areaId:string;code:string;name:string;description:string|null;instructions:string|null;allowsAttachments:boolean;maximumAttachments:number;maximumFileMb:number;order:number};
type Request={id:string;number:string;subject:string;service:string;status:string;statusColor:string|null;isFinal:boolean;submittedAt:string|null;dueDate:string|null};
type Portal={open:number;inProgress:number;resolvedRecently:number;areas:Area[];services:Service[];requests:Request[]};
type Catalog={areas:Area[];services:Service[]};
type Comment={id:string;content:string;publishedAt:string;isInternal:boolean;isMine:boolean;authorRole:string};
type Detail={id:string;number:string;subject:string;description:string;service:string;status:string;statusColor:string|null;submittedAt:string|null;dueDate:string|null;comments:Comment[]};
type Attachment={id:string;file:{originalName:string|null;storedName:string;length:number};uploadedAt:string};
type WorkflowItem={id:string;stepCode:string;execution:number;status:number;result:number|null;observation:string|null;unitName:string|null;responsibleName:string|null;formTitle:string|null;completedAt:string|null};type Workflow={version:number;status:number;managements:WorkflowItem[]};
type FormOption={id:string;code:string;label:string;isDefault:boolean;order:number};type FormField={id:string;code:string;label:string;dataType:number;controlType:number;helpText:string|null;placeholder:string|null;required:boolean;order:number;width:number;minimumLength:number|null;maximumLength:number|null;allowsMultiple:boolean;options:FormOption[]};type ServiceForm={id:string;version:number;title:string;instructions:string|null;fields:FormField[]};
type RequestFilter="all"|"open"|"tracking"|"resolved"|"closed";
const REQUEST_PAGE_SIZE=10;
function requestFilter(item:Request):Exclude<RequestFilter,"all">{const status=item.status.toLocaleLowerCase("es");if(/cerrad|cancelad/.test(status))return "closed";if(item.isFinal||/resuelt|solucionad/.test(status))return "resolved";if(/seguimiento|progreso|espera|asignad|gestión/.test(status))return "tracking";return "open";}
function formatRequestDate(value:string|null){return value?new Intl.DateTimeFormat("es-CO",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"Sin fecha";}
function DynamicField({field,value,change}:{field:FormField;value:string|string[]|undefined;change:(value:string|string[])=>void}){return <label>{field.label}{field.options.length?(field.allowsMultiple?<select aria-label={`Selecciona ${field.label}`} multiple onChange={event=>change(Array.from(event.target.selectedOptions).map(option=>option.value))} required={field.required} value={Array.isArray(value)?value:[]} >{field.options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select>:<select aria-label={`Selecciona ${field.label}`} onChange={event=>change(event.target.value)} required={field.required} value={typeof value==="string"?value:""}><option value="">Selecciona {field.label.toLocaleLowerCase("es")}…</option>{field.options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select>):field.dataType===299540045?<input checked={value==="true"} onChange={event=>change(String(event.target.checked))} type="checkbox"/>:field.controlType===299540051?<textarea maxLength={field.maximumLength??undefined} minLength={field.minimumLength??undefined} onChange={event=>change(event.target.value)} placeholder={field.placeholder??undefined} required={field.required} rows={4} value={typeof value==="string"?value:""}/>:<input maxLength={field.maximumLength??undefined} minLength={field.minimumLength??undefined} onChange={event=>change(event.target.value)} placeholder={field.placeholder??undefined} required={field.required} type={field.controlType===299540052?"number":field.controlType===299540053?"email":field.controlType===299540056?"date":field.controlType===299540057?"datetime-local":"text"} value={typeof value==="string"?value:""}/>} {field.helpText&&<small>{field.helpText}</small>}</label>}
export function IntranetSolicitudes(){
 const requestPanel=useRef<HTMLDetailsElement>(null);
 function startRequest(id?:string){if(requestOpening)return;if(portalError&&!portalLoading)void load();const panel=requestPanel.current;if(panel)panel.open=true;setRequestOpening(true);window.requestAnimationFrame(()=>{window.requestAnimationFrame(()=>{setRequestOpening(false);panel?.querySelector<HTMLSelectElement>("select")?.focus({preventScroll:true});});});if(id){const service=portal?.services.find(item=>item.id===id);if(service)setAreaId(service.areaId);void chooseService(id);}}
 const[portal,setPortal]=useState<Portal|null>(null),[portalLoading,setPortalLoading]=useState(true),[portalError,setPortalError]=useState(""),[error,setError]=useState(""),[search,setSearch]=useState("");
 const[requestOpening,setRequestOpening]=useState(false),[requestState,setRequestState]=useState<RequestFilter>("all"),[requestService,setRequestService]=useState(""),[requestSort,setRequestSort]=useState<"recent"|"oldest">("recent"),[requestPage,setRequestPage]=useState(1);
 const[areaId,setAreaId]=useState(""),[serviceId,setServiceId]=useState(""),[loadingForm,setLoadingForm]=useState(false),[files,setFiles]=useState<File[]>([]),[saving,setSaving]=useState(false),[result,setResult]=useState(""),[confirming,setConfirming]=useState(false);
 const[detail,setDetail]=useState<Detail|null>(null),[workflow,setWorkflow]=useState<Workflow|null>(null),[attachments,setAttachments]=useState<Attachment[]>([]),[comment,setComment]=useState(""),[responseFiles,setResponseFiles]=useState<File[]>([]),[posting,setPosting]=useState(false),[confirmingResponse,setConfirmingResponse]=useState(false),[responseError,setResponseError]=useState(""),[responseSuccess,setResponseSuccess]=useState("");
 const[serviceForm,setServiceForm]=useState<ServiceForm|null>(null),[answers,setAnswers]=useState<Record<string,string|string[]>>({});
 async function load(){
  setPortalLoading(true);setPortalError("");
  let catalog:Catalog;
  try{
   catalog=await apiRequest<Catalog>("/api/solicitudes/portal/catalog",{cache:"no-store"});
   setPortal(current=>({...current??{open:0,inProgress:0,resolvedRecently:0,requests:[]},areas:catalog.areas,services:catalog.services}));
  }catch(reason){
   setPortal(current=>({...current??{open:0,inProgress:0,resolvedRecently:0,requests:[]},areas:[],services:[]}));
   setPortalError(reason instanceof Error?reason.message:"No fue posible cargar las áreas y servicios.");
   setPortalLoading(false);return;
  }
  setPortalLoading(false);
  try{
   const snapshot=await apiRequest<Portal>("/api/solicitudes/portal",{cache:"no-store"});
   setPortal({...snapshot,areas:catalog.areas,services:catalog.services});
  }catch(reason){setError(reason instanceof Error?`Las áreas y servicios están disponibles, pero no fue posible consultar tus solicitudes: ${reason.message}`:"No fue posible consultar tus solicitudes.")}
 }
 useEffect(()=>{void load()},[]);
 function chooseArea(id:string){setAreaId(id);setServiceId("");setServiceForm(null);setAnswers({});setFiles([]);setResult("");setError("");}
 async function chooseService(id:string){setServiceId(id);setServiceForm(null);setAnswers({});setError("");if(!id){setFiles([]);setResult("");setLoadingForm(false);return;}setLoadingForm(true);try{setServiceForm(await apiRequest<ServiceForm|undefined>(`/api/solicitudes/services/${id}/form`,{cache:"no-store"})??null)}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible cargar el formulario.")}finally{setLoadingForm(false)}}
 function submit(event:FormEvent){event.preventDefault();setConfirming(true);}
async function confirmRequest(){setSaving(true);setError("");setResult("");try{const selectedService=portal?.services.find(item=>item.id===serviceId),subjectField=serviceForm?.fields.find(item=>item.code.toLocaleUpperCase("es")==="ASUNTO"),descriptionField=serviceForm?.fields.find(item=>item.code.toLocaleUpperCase("es")==="DESCRIPCION"),submittedSubject=subjectField&&typeof answers[subjectField.id]==="string"?String(answers[subjectField.id]):selectedService?.name??"Solicitud",description=descriptionField&&typeof answers[descriptionField.id]==="string"?String(answers[descriptionField.id]):submittedSubject,submittedFiles=[...files],dynamicAnswers=Object.entries(answers).map(([fieldId,value])=>({fieldId,value:Array.isArray(value)?null:value,optionIds:Array.isArray(value)?value:[]}));const created=await apiRequest<{id:string;number:string}>("/api/solicitudes/requests",{method:"POST",body:JSON.stringify({serviceId,subject:submittedSubject,description,answers:dynamicAnswers})});const optimistic:Request={id:created.id,number:created.number,subject:submittedSubject,service:selectedService?.name??"Servicio",status:"Radicada",statusColor:null,isFinal:false,submittedAt:new Date().toISOString(),dueDate:null};setPortal(current=>current?{...current,open:current.open+1,requests:[optimistic,...current.requests.filter(item=>item.id!==created.id)]}:current);setAreaId("");setServiceId("");setFiles([]);setServiceForm(null);setAnswers({});setConfirming(false);if(requestPanel.current)requestPanel.current.open=false;const uploadResults:PromiseSettledResult<unknown>[]=[];for(const file of submittedFiles){const body=new FormData();body.append("file",file);body.append("visibility","requester");try{uploadResults.push({status:"fulfilled",value:await apiRequest(`/api/solicitudes/requests/${created.id}/attachments`,{method:"POST",body})})}catch(reason){uploadResults.push({status:"rejected",reason})}}const failedUploads=uploadResults.filter((item):item is PromiseRejectedResult=>item.status==="rejected");if(failedUploads.length){const details=[...new Set(failedUploads.map(item=>item.reason instanceof Error?item.reason.message:"No fue posible almacenar el archivo."))].join(" ");setResult("");setError(`La solicitud ${created.number} quedó radicada, pero no se cargaron todos los adjuntos. ${details}`)}else setResult(`Solicitud ${created.number} radicada correctamente${submittedFiles.length?" con sus adjuntos":""}.`);try{const refreshed=await apiRequest<Portal>("/api/solicitudes/portal",{cache:"no-store"});setPortal({...refreshed,requests:refreshed.requests.some(item=>item.id===created.id)?refreshed.requests:[optimistic,...refreshed.requests]})}catch{/* La fila optimista permanece visible si Dataverse tarda en reflejarla. */}}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible radicar la solicitud.")}finally{setSaving(false)}}
 async function openRequest(id:string){setError("");try{const[data,fileRows]=await Promise.all([apiRequest<Detail>(`/api/solicitudes/requests/${id}`,{cache:"no-store"}),apiRequest<Attachment[]>(`/api/solicitudes/requests/${id}/attachments`,{cache:"no-store"})]);setDetail(data);setAttachments(fileRows);try{setWorkflow(await apiRequest<Workflow>(`/api/solicitudes/requests/${id}/workflow`,{cache:"no-store"}))}catch{setWorkflow(null)}setComment("");setResponseFiles([]);setResponseError("");setResponseSuccess("");setConfirmingResponse(false)}catch(reason){setError(reason instanceof Error?reason.message:"No fue posible abrir la solicitud.")}}
  function postComment(event:FormEvent){event.preventDefault();if(!detail||!comment.trim())return;if(responseFiles.length>1){setResponseError("Puedes adjuntar máximo un documento.");return}setResponseError("");setConfirmingResponse(true)} async function attendObservation(){if(!detail)return;const waiting=workflow?.managements.find(item=>item.status===299540193);setPosting(true);setError("");try{if(!waiting)throw new Error("La gestión ya no está esperando tu respuesta. Actualiza la solicitud para consultar su estado actual.");let attachment:Attachment|null=null;if(responseFiles[0]){const body=new FormData();body.append("file",responseFiles[0]);body.append("visibility","requester");body.append("managementId",waiting.id);attachment=await apiRequest<Attachment>(`/api/solicitudes/requests/${detail.id}/attachments`,{method:"POST",body})}await apiRequest(`/api/solicitudes/workflows/${waiting.id}/requester-response`,{method:"POST",body:JSON.stringify({comment:comment.trim(),hasFile:Boolean(attachment)})});setComment("");setResponseFiles([]);setConfirmingResponse(false);await Promise.all([openRequest(detail.id),load()]);setWorkflow(current=>current?{...current,managements:current.managements.map(item=>item.id===waiting.id?{...item,status:299540191}:item)}:current);setResponseSuccess(`Tu respuesta fue enviada correctamente${attachment?" con su archivo":""}. La gestión volvió a quedar disponible para el equipo.`)}catch(reason){setResponseError(reason instanceof Error?reason.message:"No fue posible atender la observación.")}finally{setPosting(false)}}
 const requestCounts=useMemo(()=>{const items=portal?.requests??[];return{all:items.length,open:items.filter(item=>requestFilter(item)==="open").length,tracking:items.filter(item=>requestFilter(item)==="tracking").length,resolved:items.filter(item=>requestFilter(item)==="resolved").length,closed:items.filter(item=>requestFilter(item)==="closed").length}},[portal]);
 const filteredRequests=useMemo(()=>{const term=search.trim().toLocaleLowerCase("es");return [...(portal?.requests??[])].filter(item=>(requestState==="all"||requestFilter(item)===requestState)&&(!requestService||item.service===requestService)&&(!term||`${item.number} ${item.subject} ${item.service} ${item.status}`.toLocaleLowerCase("es").includes(term))).sort((left,right)=>(new Date(right.submittedAt??0).getTime()-new Date(left.submittedAt??0).getTime())*(requestSort==="recent"?1:-1))},[portal,requestService,requestSort,requestState,search]);
 const requestPages=Math.max(1,Math.ceil(filteredRequests.length/REQUEST_PAGE_SIZE)),visibleRequests=filteredRequests.slice((requestPage-1)*REQUEST_PAGE_SIZE,requestPage*REQUEST_PAGE_SIZE);
 function resetRequests(){setRequestPage(1);}
 return <section className={`intranet-solicitudes ${styles.page}`}>
  <header className={styles.header}>
   <div className={styles.heroCopy}><p className={styles.eyebrow}>Solicitudes Gaia</p><h1>Soporte cuando lo necesitas</h1><p>Crea una solicitud, haz seguimiento y recibe respuestas del equipo de servicios.</p><label className={styles.heroSearch}><Search size={19}/><input aria-label="Buscar en mis solicitudes" onChange={event=>{setSearch(event.target.value);resetRequests();}} placeholder="Buscar por número, asunto, servicio o estado…" type="search" value={search}/></label></div>
   <blockquote>“Soluciones hoy<br/>para un mejor mañana”<small>Gaia Amazonas</small></blockquote>
  </header>
  <div className={styles.newRequest}>
   <details ref={requestPanel} id="solicitudes-new-request"><summary>Nueva solicitud</summary><form className="solicitudes-temporary-form" onSubmit={submit}>
    <header className="solicitudes-form-header"><span><ShieldCheck size={16}/> Radicación segura en Gaia</span><button aria-label="Cerrar nueva solicitud" disabled={saving} onClick={()=>{if(requestPanel.current)requestPanel.current.open=false}} type="button"><X size={18}/></button></header>
    {portalLoading&&<p className="solicitudes-form-loading" role="status"><LoaderCircle className="animate-spin" size={18}/> Estamos cargando las áreas y servicios…</p>}
    {portalError&&!portalLoading&&<div className="solicitudes-form-loading" role="alert"><span>{portalError}</span><button onClick={()=>void load()} type="button">Reintentar</button></div>}
    <label>Área<select disabled={portalLoading} onChange={event=>chooseArea(event.target.value)} required value={areaId}><option value="">{portalError?"No se pudieron cargar las áreas":"Selecciona un área"}</option>{(portal?.areas??[]).map(item=><option key={item.id} value={item.id}>{item.shortName}</option>)}</select></label>
    {areaId&&<label>Servicio<select onChange={event=>void chooseService(event.target.value)} required value={serviceId}><option value="">Selecciona un servicio</option>{(portal?.services??[]).filter(item=>item.areaId===areaId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
    {serviceId&&<>{loadingForm&&<p className="solicitudes-form-loading" role="status"><LoaderCircle className="animate-spin" size={18}/> Estamos cargando el formulario del servicio…</p>}{serviceForm?<fieldset className="solicitudes-dynamic-fields"><legend>{serviceForm.title}</legend>{serviceForm.instructions&&<p>{serviceForm.instructions}</p>}{serviceForm.fields.filter(field=>field.dataType!==299540047).map(field=><DynamicField change={value=>setAnswers(current=>({...current,[field.id]:value}))} field={field} key={field.id} value={answers[field.id]}/>)}</fieldset>:!loadingForm&&<p className="solicitudes-form-loading" role="alert">Este servicio todavía no tiene un formulario publicado.</p>}{serviceForm&&<><label>Adjuntos opcionales<input accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx" key={serviceId} multiple onChange={event=>setFiles(Array.from(event.target.files??[]))} type="file"/></label><button disabled={saving} type="submit">Radicar solicitud</button></>}</>}
   </form></details>
  </div>
  {error&&<p className="solicitudes-load-message" role="alert">{error}</p>}{result&&<p className="solicitudes-success-message" role="status">{result}</p>}
  <section className={styles.requestsPanel} id="solicitudes-my-requests" tabIndex={-1}>
   <header className={styles.panelHeader}><div><p className={styles.eyebrow}>Seguimiento personal</p><h2>Mis solicitudes</h2><p>Consulta, da seguimiento y gestiona tus solicitudes en un solo lugar.</p></div><button aria-busy={requestOpening} className={styles.primary} disabled={requestOpening} onClick={()=>startRequest()} type="button">{requestOpening?<LoaderCircle className="animate-spin" size={17}/>:<Plus size={17}/>} {requestOpening?"Abriendo…":"Nueva solicitud"}</button></header>
   <nav aria-label="Filtrar solicitudes por estado" className={styles.tabs}>{([{key:"all",label:"Todas"},{key:"open",label:"Abiertas"},{key:"tracking",label:"En seguimiento"},{key:"resolved",label:"Resueltas"},{key:"closed",label:"Cerradas"}] as const).map(tab=><button aria-pressed={requestState===tab.key} className={requestState===tab.key?styles.activeTab:""} key={tab.key} onClick={()=>{setRequestState(tab.key);resetRequests();}} type="button">{tab.label}<span>{requestCounts[tab.key]}</span></button>)}</nav>
   <div className={styles.filters}><span><SlidersHorizontal size={16}/>Filtrar resultados</span><select aria-label="Filtrar por servicio" onChange={event=>{setRequestService(event.target.value);resetRequests();}} value={requestService}><option value="">Todos los servicios</option>{[...new Set((portal?.requests??[]).map(item=>item.service))].sort().map(service=><option key={service}>{service}</option>)}</select><label><ArrowDownUp size={15}/><select aria-label="Ordenar solicitudes" onChange={event=>{setRequestSort(event.target.value as "recent"|"oldest");resetRequests();}} value={requestSort}><option value="recent">Más recientes</option><option value="oldest">Más antiguas</option></select></label></div>
   {visibleRequests.length?<><div className={styles.tableWrap}><table><thead><tr><th>Solicitud</th><th>Asunto</th><th>Servicio</th><th>Estado</th><th>Radicada</th><th>Acciones</th></tr></thead><tbody>{visibleRequests.map(item=><tr key={item.id}><td><strong>{item.number}</strong></td><td>{item.subject}</td><td><span className={styles.serviceCell}><Laptop size={16}/>{item.service}</span></td><td><span className={`${styles.status} ${styles[requestFilter(item)]}`}><i/>{item.status}</span></td><td>{formatRequestDate(item.submittedAt)}</td><td><button aria-label={`Ver ${item.number}`} onClick={()=>void openRequest(item.id)} type="button"><Eye size={15}/>Ver</button><button aria-label={`Más opciones para ${item.number}`} className={styles.more} onClick={()=>void openRequest(item.id)} type="button"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div><footer className={styles.pagination}><span>Mostrando {(requestPage-1)*REQUEST_PAGE_SIZE+1}–{Math.min(requestPage*REQUEST_PAGE_SIZE,filteredRequests.length)} de {filteredRequests.length}</span><nav aria-label="Páginas de solicitudes"><button aria-label="Página anterior" disabled={requestPage===1} onClick={()=>setRequestPage(page=>page-1)} type="button"><ArrowLeft size={16}/></button><strong aria-current="page">{requestPage}</strong><button aria-label="Página siguiente" disabled={requestPage===requestPages} onClick={()=>setRequestPage(page=>page+1)} type="button"><ArrowRight size={16}/></button></nav></footer></>:<div className={styles.empty}><Inbox size={27}/><strong>{portal?"No hay solicitudes para estos filtros":error?"No pudimos consultar tus solicitudes":"Consultando tus solicitudes…"}</strong><p>{portal?requestCounts.all?"Prueba con otro estado, servicio o término de búsqueda.":"Aquí aparecerán tus solicitudes con su estado y las respuestas del equipo.":error?"Intenta cargar la página nuevamente.":"En un momento podrás revisar tu actividad."}</p>{portal&&!requestCounts.all&&<button onClick={()=>startRequest()} type="button"><Plus size={16}/>Crear mi primera solicitud</button>}</div>}
  </section>
        {detail&&<div className="solicitudes-detail-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setDetail(null)}}><section className="solicitudes-detail solicitudes-observation-detail" role="dialog" aria-modal="true" aria-label={`Solicitud ${detail.number}`}><header><span><small>{detail.number} · {detail.service}</small><h2>{detail.subject}</h2></span><button aria-label="Cerrar detalle" onClick={()=>setDetail(null)} type="button">×</button></header><p>{detail.description}</p><div className="solicitudes-detail-meta"><span>Estado <strong>{detail.status}</strong></span><span>Fecha límite <strong>{detail.dueDate||"Por definir"}</strong></span></div>{workflow?.status===299540182&&<button className="solicitudes-closure-download" onClick={()=>downloadClosurePdf({...detail,managements:workflow.managements})} type="button"><FileDown size={17}/>Descargar constancia de atención PDF</button>}<h3>Conversación</h3><div className="solicitudes-comments">{detail.comments.length?detail.comments.map(item=><article className={item.isMine||item.authorRole?.trim().toLocaleLowerCase("es")==="solicitante"?"requester":"team"} key={item.id}><small>{item.authorRole}{item.isInternal?" · Nota interna":""} · {new Date(item.publishedAt).toLocaleString("es-CO")}</small><p>{item.content}</p></article>):<p>Aún no hay comentarios.</p>}</div>{workflow?.managements.some(item=>item.status===299540193)&&<form onSubmit={postComment}><textarea maxLength={4000} minLength={2} onChange={event=>setComment(event.target.value)} placeholder="Escribe la información solicitada" required rows={3} value={comment}/><label className="solicitudes-response-files">Adjuntar documento <small>(opcional)</small><input accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx" onChange={event=>setResponseFiles(Array.from(event.target.files??[]))} type="file"/>{responseFiles.length>0?<small>{responseFiles.length} archivo seleccionado</small>:<small>Haz clic aquí si necesitas anexar un soporte.</small>}</label>{responseError&&!confirmingResponse&&<p className="solicitudes-response-error" role="alert">{responseError}</p>}<button disabled={posting} type="submit">{posting?"Atendiendo observación…":"Enviar respuesta"}</button></form>}<h3>Adjuntos</h3><div className="solicitudes-attachments">{attachments.length?attachments.map(item=><a href={`${process.env.NEXT_PUBLIC_GAIA_API_URL??"https://localhost:7168"}/api/solicitudes/attachments/${item.id}/content`} key={item.id}>{item.file.originalName||item.file.storedName} <small>{Math.ceil(item.file.length/1024)} KB</small></a>):<p>Esta solicitud no tiene adjuntos.</p>}</div></section></div>}
  {responseSuccess&&<div className="solicitudes-confirm-overlay"><section className="solicitudes-confirm-dialog solicitudes-success-dialog" role="dialog" aria-modal="true" aria-labelledby="solicitudes-response-success-title"><CheckCircle2 size={38}/><h2 id="solicitudes-response-success-title">Respuesta enviada</h2><p>{responseSuccess}</p><div><button onClick={()=>{setResponseSuccess("");setDetail(null)}} type="button">Entendido</button></div></section></div>}{confirmingResponse&&<div className="solicitudes-confirm-overlay"><section className="solicitudes-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="solicitudes-response-confirm-title"><MessageSquareText size={30}/><h2 id="solicitudes-response-confirm-title">¿Atender esta observación?</h2><p>Tu respuesta{responseFiles.length?` y ${responseFiles.length} archivo${responseFiles.length===1?"":"s"}`:""} se enviará al equipo gestor y la solicitud regresará al estado anterior para que el equipo pueda continuar gestionándola.</p>{posting&&<div className="solicitudes-saving"><LoaderCircle className="animate-spin" size={18}/>Estamos enviando tu respuesta…</div>}{responseError&&<p className="solicitudes-response-error" role="alert">{responseError}</p>}<div><button disabled={posting} onClick={()=>setConfirmingResponse(false)} type="button">Volver y revisar</button><button disabled={posting} onClick={()=>void attendObservation()} type="button">{posting?"Enviando…":"Sí, atender observación"}</button></div></section></div>}{confirming&&<div className="solicitudes-confirm-overlay"><section className="solicitudes-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="solicitudes-confirm-title"><ShieldCheck size={30}/><h2 id="solicitudes-confirm-title">¿Radicar esta solicitud?</h2><p>Verifica que el servicio, el asunto y todas las respuestas sean correctos. Al confirmar, la solicitud quedará radicada y será enviada al equipo responsable.</p>{saving&&<div className="solicitudes-saving"><LoaderCircle className="animate-spin" size={18}/>Estamos guardando y radicando tu solicitud…</div>}<div><button disabled={saving} onClick={()=>setConfirming(false)} type="button">Volver y revisar</button><button disabled={saving} onClick={()=>void confirmRequest()} type="button">{saving?"Radicando…":"Sí, radicar solicitud"}</button></div></section></div>}
 </section>;
}
