"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {CalendarDays,Cake,ChevronLeft,ChevronRight,Clock3,ExternalLink,MapPin,X} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {apiRequest} from "@/lib/api-client";

type Birthday={id:string;fullName:string;day:number;month:number;photoUrl:string|null};
type EventItem={id:string;name:string;type:string;color:string;summary?:string;description?:string;startsAt:string;endsAt?:string;allDay:boolean;modality?:number;location?:string;eventUrl?:string};
type CalendarView="day"|"week"|"month";
const weekdays=["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"];

export function IntranetCalendar(){
 const today=new Date(),[focusDate,setFocusDate]=useState(()=>startOfDay(today)),[view,setView]=useState<CalendarView>("week"),[birthdays,setBirthdays]=useState<Birthday[]>([]),[events,setEvents]=useState<EventItem[]>([]),[detail,setDetail]=useState<EventItem|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const year=focusDate.getFullYear(),month=focusDate.getMonth(),monthStart=useMemo(()=>new Date(year,month,1),[year,month]),monthKey=`${year}-${month+1}`;
 useEffect(()=>{let active=true;setLoading(true);const from=new Date(year,month-1,1).toISOString(),to=new Date(year,month+2,1).toISOString(),months=[...new Set([new Date(year,month-1,1).getMonth()+1,month+1,new Date(year,month+1,1).getMonth()+1])];Promise.allSettled([apiRequest<EventItem[]>(`/api/intranet/events?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`,{cache:"no-store"}),...months.map(value=>apiRequest<Birthday[]>(`/api/intranet/birthdays?month=${value}`,{cache:"no-store"}))]).then(results=>{if(!active)return;const[eventResult,...birthdayResults]=results;const loadedBirthdays=birthdayResults.flatMap(result=>result.status==="fulfilled"?result.value:[]);setEvents(eventResult.status==="fulfilled"?eventResult.value:[]);setBirthdays([...new Map(loadedBirthdays.map(item=>[`${item.id}-${item.month}-${item.day}`,item])).values()]);const failures=results.filter(result=>result.status==="rejected");setError(failures.length===results.length?(failures[0] as PromiseRejectedResult).reason instanceof Error?(failures[0] as PromiseRejectedResult).reason.message:"No fue posible cargar el calendario.":failures.length?"Parte de la información del calendario no pudo actualizarse. Vuelve a intentarlo.":"");}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[month,year]);
 const days=useMemo(()=>calendarDays(monthStart),[monthStart]),selectedDay=focusDate.getDate(),dayEvents=eventsForDate(events,focusDate),dayBirthdays=birthdays.filter(item=>item.day===selectedDay&&item.month===focusDate.getMonth()+1),weekDays=weekOf(focusDate),todayStart=startOfDay(today),upcoming=events.filter(item=>new Date(item.startsAt)>=todayStart).sort(byStart).slice(0,4),monthEvents=events.filter(item=>{const date=new Date(item.startsAt);return date.getFullYear()===year&&date.getMonth()===month}),monthName=new Intl.DateTimeFormat("es-CO",{month:"long",year:"numeric"}).format(monthStart);
 function move(direction:number){setFocusDate(view==="month"?new Date(year,month+direction,1):addDays(focusDate,direction*(view==="week"?7:1)));}
 return <section className="intranet-calendar-page">
  <header className="intranet-section-hero intranet-section-hero-calendar"><div><p>Agenda institucional</p><h1>Eventos</h1><span>Encuentros, celebraciones y momentos que conectan a nuestro equipo.</span></div><button onClick={()=>setFocusDate(startOfDay(today))} type="button">Ir a hoy</button></header>
  {error&&<div className="intranet-data-state is-error"><strong>No fue posible cargar el calendario</strong><p>{error}</p></div>}
  <div className="intranet-calendar-toolbar"><div aria-label="Vista del calendario" className="intranet-calendar-view-switch" role="group">{(["day","week","month"] as CalendarView[]).map(option=><button aria-pressed={view===option} key={option} onClick={()=>setView(option)} type="button">{{day:"Día",week:"Semana",month:"Mes"}[option]}</button>)}</div><div className="intranet-calendar-period"><button aria-label="Periodo anterior" onClick={()=>move(-1)} type="button"><ChevronLeft size={17}/></button><strong>{periodLabel(view,focusDate)}</strong><button aria-label="Periodo siguiente" onClick={()=>move(1)} type="button"><ChevronRight size={17}/></button></div></div>
  <div className="intranet-calendar-layout">
   {view==="month"&&<MonthView birthdays={birthdays} days={days} events={events} focusDate={focusDate} monthKey={monthKey} monthName={monthName} onSelect={setFocusDate}/>}
   {view==="week"&&<WeekView birthdays={birthdays} days={weekDays} events={events} focusDate={focusDate} onOpen={setDetail} onSelect={setFocusDate}/>}
   {view==="day"&&<DayView birthdays={dayBirthdays} date={focusDate} events={dayEvents} loading={loading} onOpen={setDetail}/>}
   <DayDetail birthdays={dayBirthdays} events={dayEvents} loading={loading} monthName={monthName} onOpen={setDetail} selectedDay={selectedDay} upcoming={upcoming}/>
  </div>
  <section className="intranet-events-list"><header><p>Vista mensual</p><h2>Eventos de {monthName}</h2></header>{monthEvents.length?<div>{monthEvents.map(item=><button key={item.id} onClick={()=>setDetail(item)}><time style={{borderColor:item.color}}><strong>{new Date(item.startsAt).getDate()}</strong><small>{new Intl.DateTimeFormat("es-CO",{month:"short"}).format(new Date(item.startsAt))}</small></time><span><small style={{color:item.color}}>{item.type}</small><strong>{item.name}</strong><em>{item.summary||item.location||"Evento institucional"}</em></span></button>)}</div>:<p>No hay eventos publicados para este mes.</p>}</section>
  {detail&&<EventModal event={detail} onClose={()=>setDetail(null)}/>}
 </section>;
}

function MonthView({birthdays,days,events,focusDate,monthKey,monthName,onSelect}:{birthdays:Birthday[];days:(number|null)[];events:EventItem[];focusDate:Date;monthKey:string;monthName:string;onSelect:(date:Date)=>void}){return <div className="intranet-month"><header><span/><h2>{monthName}</h2><span/></header><div className="intranet-weekdays">{weekdays.map(item=><span key={item}>{item}</span>)}</div><div className="intranet-days">{days.map((day,index)=>{if(day===null)return <span key={`empty-${monthKey}-${index}`}/>;const date=new Date(focusDate.getFullYear(),focusDate.getMonth(),day),dayEvents=eventsForDate(events,date),dayBirthdays=birthdays.filter(item=>item.day===day&&item.month===date.getMonth()+1);return <button aria-label={dayAriaLabel(day,dayEvents,dayBirthdays)} aria-pressed={focusDate.getDate()===day} className={focusDate.getDate()===day?"is-selected":undefined} key={`day-${monthKey}-${day}`} onClick={()=>onSelect(date)}><strong>{day}</strong><CalendarDayEntries birthdays={dayBirthdays} events={dayEvents}/></button>})}</div></div>}
function WeekView({birthdays,days,events,focusDate,onOpen,onSelect}:{birthdays:Birthday[];days:Date[];events:EventItem[];focusDate:Date;onOpen:(event:EventItem)=>void;onSelect:(date:Date)=>void}){return <div className="intranet-week-view">{days.map(date=>{const rows=eventsForDate(events,date),celebrations=birthdays.filter(item=>item.day===date.getDate()&&item.month===date.getMonth()+1),selected=sameDate(date,focusDate),hasContent=rows.length>0||celebrations.length>0;return <section className={selected?"is-selected":undefined} key={date.toISOString()}><button className="intranet-week-day" onClick={()=>onSelect(date)} type="button"><small>{new Intl.DateTimeFormat("es-CO",{weekday:"short"}).format(date)}</small><strong>{date.getDate()}</strong></button>{hasContent&&<div>{rows.map(item=><button className="intranet-week-event" key={item.id} onClick={()=>onOpen(item)} style={{"--event-color":item.color} as React.CSSProperties}><small>{item.allDay?"Todo el día":time(item.startsAt)}</small><strong>{item.name}</strong><span>{item.type}</span></button>)}{celebrations.length>0&&<BirthdayGroup birthdays={celebrations} compact/>}</div>}</section>;})}</div>}
function DayView({birthdays,date,events,loading,onOpen}:{birthdays:Birthday[];date:Date;events:EventItem[];loading:boolean;onOpen:(event:EventItem)=>void}){return <div className="intranet-day-view"><header><CalendarDays size={22}/><span><small>Agenda del día</small><h2>{new Intl.DateTimeFormat("es-CO",{weekday:"long",day:"numeric",month:"long"}).format(date)}</h2></span></header>{loading?<div className="intranet-day-empty">Cargando agenda…</div>:events.length||birthdays.length?<div className="intranet-day-view-list">{events.map(item=><button key={item.id} onClick={()=>onOpen(item)} style={{"--event-color":item.color} as React.CSSProperties}><time>{item.allDay?"Todo el día":time(item.startsAt)}</time><i/><span><small>{item.type}</small><strong>{item.name}</strong><em>{item.location||item.summary||"Evento institucional"}</em></span></button>)}{birthdays.length>0&&<BirthdayGroup birthdays={birthdays}/>}</div>:<div className="intranet-day-empty"><CalendarDays/><strong>Un día disponible</strong><span>No hay eventos visibles para esta fecha.</span></div>}</div>}
function DayDetail({birthdays,events,loading,monthName,onOpen,selectedDay,upcoming}:{birthdays:Birthday[];events:EventItem[];loading:boolean;monthName:string;onOpen:(event:EventItem)=>void;selectedDay:number;upcoming:EventItem[]}){return <aside className="intranet-day-detail"><p>Agenda del día</p><h2>{selectedDay} de {monthName.split(" ")[0]}</h2>{loading?<div className="intranet-day-empty">Cargando agenda…</div>:events.length||birthdays.length?<div className="intranet-event-day-list">{events.map(item=><button key={item.id} onClick={()=>onOpen(item)} style={{borderLeftColor:item.color}}><small>{item.type}</small><strong>{item.name}</strong><span>{item.allDay?"Todo el día":time(item.startsAt)}{item.location?` · ${item.location}`:""}</span></button>)}{birthdays.length>0&&<BirthdayGroup birthdays={birthdays}/>}</div>:<div className="intranet-day-empty"><CalendarDays/><strong>Un día disponible</strong><span>No hay eventos visibles para esta fecha.</span></div>}<section className="intranet-upcoming-events"><header><span>Próximamente</span><strong>Lo que sigue en Gaia</strong></header>{upcoming.length?<div>{upcoming.map(item=><button key={item.id} onClick={()=>onOpen(item)}><time style={{borderColor:item.color}}><strong>{new Date(item.startsAt).getDate()}</strong><small>{new Intl.DateTimeFormat("es-CO",{month:"short"}).format(new Date(item.startsAt))}</small></time><span><small style={{color:item.color}}>{item.type}</small><strong>{item.name}</strong><em>{item.allDay?"Todo el día":time(item.startsAt)}</em></span></button>)}</div>:<p>No hay próximos eventos publicados.</p>}</section></aside>}
function BirthdayGroup({birthdays,compact=false}:{birthdays:Birthday[];compact?:boolean}){return <article className={`intranet-birthday-group${compact?" is-compact":""}`}><Cake size={compact?13:18}/><div><small>{birthdays.length===1?"Cumpleaños":"Cumpleaños del día"}</small><ul>{birthdays.map(item=><li key={item.id}>{proper(item.fullName)}</li>)}</ul></div></article>}
function CalendarDayEntries({events,birthdays}:{events:EventItem[];birthdays:Birthday[]}){const visible=events.slice(0,2),remaining=events.length-visible.length;return <span className="intranet-calendar-entries">{visible.map(event=><span className="intranet-calendar-event-chip" data-tooltip={eventTooltip(event)} key={event.id} style={{"--event-color":event.color} as React.CSSProperties}><i/><b>{event.name}</b></span>)}{remaining>0&&<span className="intranet-calendar-more">+{remaining} más</span>}{birthdays.length>0&&<span className="intranet-calendar-birthday" data-tooltip={`Cumpleaños: ${birthdays.map(item=>proper(item.fullName)).join(", ")}`}><Cake size={10}/><b>{birthdays.length===1?proper(birthdays[0].fullName):`${birthdays.length} cumpleaños`}</b></span>}</span>}
function EventModal({event,onClose}:{event:EventItem;onClose:()=>void}){return <div className="intranet-event-modal" onMouseDown={onClose}><article onMouseDown={mouseEvent=>mouseEvent.stopPropagation()}><button aria-label="Cerrar" onClick={onClose}><X/></button><i style={{background:event.color}}/><small>{event.type}</small><h2>{event.name}</h2>{event.summary&&<strong>{event.summary}</strong>}<div><span><Clock3/> {event.allDay?"Todo el día":new Intl.DateTimeFormat("es-CO",{dateStyle:"full",timeStyle:"short"}).format(new Date(event.startsAt))}</span>{event.location&&<span><MapPin/> {event.location}</span>}</div>{event.description&&<p>{event.description}</p>}{event.eventUrl&&<a href={event.eventUrl} rel="noopener noreferrer" target="_blank">Abrir enlace del evento <ExternalLink/></a>}</article></div>}

function calendarDays(date:Date){const count=new Date(date.getFullYear(),date.getMonth()+1,0).getDate(),offset=(new Date(date.getFullYear(),date.getMonth(),1).getDay()+6)%7;return[...Array<null>(offset).fill(null),...Array.from({length:count},(_,index)=>index+1)];}
function weekOf(date:Date){const offset=(date.getDay()+6)%7,start=addDays(date,-offset);return Array.from({length:7},(_,index)=>addDays(start,index));}
function eventsForDate(events:EventItem[],date:Date){return events.filter(item=>sameDate(new Date(item.startsAt),date)).sort(byStart);}
function sameDate(left:Date,right:Date){return left.getFullYear()===right.getFullYear()&&left.getMonth()===right.getMonth()&&left.getDate()===right.getDate();}
function startOfDay(date:Date){return new Date(date.getFullYear(),date.getMonth(),date.getDate());}
function addDays(date:Date,days:number){return new Date(date.getFullYear(),date.getMonth(),date.getDate()+days);}
function byStart(left:EventItem,right:EventItem){return new Date(left.startsAt).getTime()-new Date(right.startsAt).getTime();}
function periodLabel(view:CalendarView,date:Date){if(view==="day")return new Intl.DateTimeFormat("es-CO",{weekday:"long",day:"numeric",month:"long"}).format(date);if(view==="week"){const days=weekOf(date);return `${new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"short"}).format(days[0])} – ${new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"short",year:"numeric"}).format(days[6])}`;}return new Intl.DateTimeFormat("es-CO",{month:"long",year:"numeric"}).format(date);}
function eventTooltip(event:EventItem){return `${event.type} · ${event.name} · ${event.allDay?"Todo el día":time(event.startsAt)}${event.location?` · ${event.location}`:""}`;}
function dayAriaLabel(day:number,events:EventItem[],birthdays:Birthday[]){const dayEvents=events.filter(item=>new Date(item.startsAt).getDate()===day),dayBirthdays=birthdays.filter(item=>item.day===day);return `${day}. ${dayEvents.length} evento${dayEvents.length===1?"":"s"}${dayBirthdays.length?` y ${dayBirthdays.length} cumpleaños`:""}`;}
function time(value:string){return new Intl.DateTimeFormat("es-CO",{hour:"numeric",minute:"2-digit"}).format(new Date(value));}
function proper(value:string){return value.toLocaleLowerCase("es").replace(/(^|\s)\p{L}/gu,letter=>letter.toLocaleUpperCase("es"));}
