"use client";

import { Button, Badge } from "@/components/ui";
import { apiRequest } from "@/lib/api-client";
import { ArrowLeft, BookOpen, CalendarClock, CheckCircle2, ChevronDown, FileText, LoaderCircle, Search, List, LayoutGrid, Sparkles, ArrowRight, PlayCircle } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { youtubeEmbed } from "../training/training-content-rules";
import { activeTrainingStatuses, trainingDueLabel, trainingStatus, type TrainingAssignment } from "./training-assignment";
import { ParticipantEvaluations } from "./training-participant-evaluations";
import { TrainingVideo } from "./training-video";
import "./training-participant.css";

type Block = { id:string; name:string; type:number; order:number; required:boolean; html:string|null; externalUrl:string|null; actionText:string|null; resourceId:string|null; minimumViewPercentage:number|null; requiresConfirmation:boolean; active:boolean };
type Section = { id:string; name:string; description:string|null; order:number; active:boolean; blocks:Block[] };
type Detail = { assignment:TrainingAssignment; objective:string|null; sequentialOrder:boolean; completionMessage:string|null; sections:Section[]; completedBlockIds:string[];canContinue:boolean;availabilityMessage:string|null };
const apiUrl = process.env.NEXT_PUBLIC_GAIA_API_URL ?? "https://localhost:7168";
const message = (reason:unknown) => reason instanceof Error ? reason.message : "No fue posible completar la acción. Inténtalo nuevamente.";
const plain = (value:string) => value.replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">");
function safeUrl(value:string|null) { try { const url=new URL(value??""); return ["https:","http:"].includes(url.protocol)?url.toString():null; } catch { return null; } }

export function IntranetTraining() {
  const [items,setItems]=useState<TrainingAssignment[]>([]),[detail,setDetail]=useState<Detail|null>(null);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
  const [filter,setFilter]=useState<"active"|"pending"|"completed">("active"),[query,setQuery]=useState(""),[page,setPage]=useState(1),[collapsed,setCollapsed]=useState<Set<string>>(new Set()),[view,setView]=useState<"list"|"cards">("list");
  const requested=useRef(false);
  const [observed,setObserved]=useState<Record<string,{viewedPercentage:number;viewedSeconds:number}>>({});
  useEffect(()=>{let live=true;apiRequest<TrainingAssignment[]>("/api/training/my/assignments").then(x=>{if(live)setItems(x)}).catch(e=>{if(live)setError(message(e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
  useEffect(()=>{
    if(loading||requested.current)return;requested.current=true;
    const id=new URLSearchParams(window.location.search).get("asignacion");
    if(id&&items.some(x=>x.assignmentId===id))void open(id);
  },[loading,items]);
  async function reload() { setError("");setBusy("reload");try{setItems(await apiRequest<TrainingAssignment[]>("/api/training/my/assignments"))}catch(e){setError(message(e))}finally{setBusy("")} }
  async function open(id:string) { setBusy(id);setError("");try{setDetail(await apiRequest<Detail>(`/api/training/my/assignments/${id}`));setCollapsed(new Set())}catch(e){setError(message(e))}finally{setBusy("")} }
  async function refreshDetail() { if(!detail)return;const updated=await apiRequest<Detail>(`/api/training/my/assignments/${detail.assignment.assignmentId}`);setDetail(updated);setItems(current=>current.map(x=>x.assignmentId===updated.assignment.assignmentId?updated.assignment:x)); }
  async function complete(id:string) { if(!detail)return;setBusy(id);setError("");try{await apiRequest(`/api/training/my/assignments/${detail.assignment.assignmentId}/blocks/${id}/complete`,{method:"POST",body:JSON.stringify(observed[id]??{})});await refreshDetail()}catch(e){setError(message(e))}finally{setBusy("")} }
  const rows=useMemo(()=>items.filter(x=>(filter==="active"?activeTrainingStatuses.has(x.status)&&x.status!==299541090:filter==="pending"?x.status===299541090:!activeTrainingStatuses.has(x.status))&&`${x.training} ${x.summary??""}`.toLocaleLowerCase("es").includes(query.trim().toLocaleLowerCase("es"))),[items,filter,query]);
  const pages=Math.max(1,Math.ceil(rows.length/9)),currentPage=Math.min(page,pages);
  if(detail) {
    const sections=detail.sections.filter(x=>x.active).sort((a,b)=>a.order-b.order);
    const blocks=sections.flatMap(s=>s.blocks.filter(x=>x.active).sort((a,b)=>a.order-b.order));
    const allContent=blocks.filter(x=>x.required).every(x=>detail.completedBlockIds.includes(x.id));
    return <section className="intranet-page-shell training-participant training-learning-experience">
      <Button className="mb-5" variant="secondary" onClick={()=>{setDetail(null);void reload()}}><ArrowLeft size={17}/>Volver a mis capacitaciones</Button>
      <header className="training-participant-hero training-learning-hero"><div className="training-learning-copy"><span className="training-learning-eyebrow"><Sparkles size={16}/>Aprendizaje Gaia</span><div className="training-learning-meta"><Badge tone={detail.assignment.status===299541093?"success":"neutral"}>{trainingStatus(detail.assignment.status)}</Badge><small>Versión {detail.assignment.version}</small></div><h1>{detail.assignment.training}</h1><p>{detail.objective||detail.assignment.summary||"Recorre el material y responde las evaluaciones indicadas."}</p><div className="training-learning-path"><a href="#training-content"><BookOpen size={16}/>Explorar contenido</a><a href="#training-evaluations"><ArrowRight size={16}/>Ir a evaluaciones</a></div></div><aside className="training-learning-progress"><span className="training-learning-progress-icon"><PlayCircle size={26}/></span><small>Tu recorrido</small><strong>{detail.assignment.progress}<span>%</span></strong><span>del contenido completado</span><progress aria-label="Avance del contenido" max={100} value={detail.assignment.progress}/><p>{blocks.filter(x=>x.required&&detail.completedBlockIds.includes(x.id)).length} de {blocks.filter(x=>x.required).length} materiales obligatorios</p><div><CalendarClock size={17}/><span>Fecha límite<strong>{trainingDueLabel(detail.assignment.dueAt)}</strong></span></div></aside></header>
      <nav className="training-learning-map" aria-label="Secciones de la capacitación">{sections.map((section,index)=>{const required=section.blocks.filter(x=>x.active&&x.required);const finished=required.length>0&&required.every(x=>detail.completedBlockIds.includes(x.id));return <a href={`#training-section-${section.id}`} key={section.id} onClick={()=>setCollapsed(current=>{const next=new Set(current);next.delete(section.id);return next})}><span>{finished?<CheckCircle2 size={18}/>:index+1}</span><strong>{section.name}</strong></a>})}</nav>
      {detail.assignment.status===299541093&&<aside className="training-notice training-notice-success" role="status"><CheckCircle2 size={22}/><div><strong>Capacitación completada</strong><p>{detail.completionMessage||"Gracias por completar esta experiencia de aprendizaje."}</p>{detail.assignment.result!==null&&<span>Resultado general: {detail.assignment.result}%</span>}</div></aside>}
      {detail.availabilityMessage&&<div className="training-notice" role="status">{detail.availabilityMessage}</div>}{error&&<div className="training-notice training-notice-error" role="alert">{error}</div>}
      <div id="training-content" className="training-section-toolbar"><div><small className="training-learning-eyebrow">01 · Explora y aprende</small><h2>Contenido de la capacitación</h2><p>{detail.sequentialOrder?"Completa el material obligatorio en el orden indicado.":"Puedes recorrer el material en el orden que prefieras."}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setCollapsed(new Set())}>Expandir todo</Button><Button variant="secondary" onClick={()=>setCollapsed(new Set(sections.map(s=>s.id)))}>Contraer todo</Button></div></div>
      <div className="space-y-4">{sections.map((section,index)=><article id={`training-section-${section.id}`} className="training-participant-section" key={section.id}><button className="training-collapse-header" type="button" aria-expanded={!collapsed.has(section.id)} onClick={()=>setCollapsed(previous=>{const next=new Set(previous);if(next.has(section.id))next.delete(section.id);else next.add(section.id);return next})}><span><small>Sección {String(index+1).padStart(2,"0")} · {section.blocks.filter(x=>x.active).length} materiales</small><strong>{section.name}</strong>{section.description&&<p>{section.description}</p>}</span><ChevronDown className={collapsed.has(section.id)?"":"rotate-180"} size={20}/></button>{!collapsed.has(section.id)&&<div className="training-section-body space-y-4">{section.blocks.filter(x=>x.active).sort((a,b)=>a.order-b.order).map(block=>{
        const done=detail.completedBlockIds.includes(block.id);const locked=detail.sequentialOrder&&blocks.slice(0,blocks.findIndex(x=>x.id===block.id)).some(x=>x.required&&!detail.completedBlockIds.includes(x.id));
        return <article className="training-participant-block" key={block.id}><div className="flex flex-wrap items-center justify-between gap-2"><h3>{block.name}{block.required&&<span aria-label="obligatorio"> *</span>}</h3>{done&&<Badge tone="success">Completado</Badge>}</div>{locked&&!done?<p className="mt-3">Completa primero el material obligatorio anterior para abrir este contenido.</p>:<><TrainingMaterial assignmentId={detail.assignment.assignmentId} block={block} onProgress={(viewedPercentage,viewedSeconds)=>setObserved(x=>({...x,[block.id]:{viewedPercentage,viewedSeconds}}))}/>{block.type===299541074&&block.minimumViewPercentage&&<small className="mt-3 block">Visualizado: {Math.floor(observed[block.id]?.viewedPercentage??0)}% · Mínimo: {block.minimumViewPercentage}%</small>}{!done&&<Button className="mt-4" disabled={Boolean(busy)||!detail.canContinue||detail.assignment.status===299541093||(block.type===299541074&&(observed[block.id]?.viewedPercentage??0)<(block.minimumViewPercentage??0))} onClick={()=>void complete(block.id)}>{busy===block.id?<LoaderCircle className="animate-spin" size={16}/>:<CheckCircle2 size={16}/>}Confirmar contenido completado</Button>}</>}</article>;
      })}</div>}</article>)}</div>
      {!sections.length&&<div className="training-notice">No hay contenido disponible. Comunícate con el responsable de la capacitación.</div>}
      <ParticipantEvaluations assignmentId={detail.assignment.assignmentId} contentComplete={allContent} canContinue={detail.canContinue&&detail.assignment.status!==299541093} onUpdated={refreshDetail}/>
    </section>;
  }
  return <section className="intranet-page-shell training-participant"><header className="intranet-page-heading"><p>Aprendizaje Gaia</p><h1>Mis capacitaciones</h1><span>Todo tu aprendizaje en un lugar: contenidos, evaluaciones, fechas y resultados.</span><Link className="mt-4 inline-flex items-center gap-2" href="/intranet/calendario"><CalendarClock size={17}/>Consultar calendario</Link></header>
    <div className="training-section-toolbar"><div className="flex flex-wrap gap-2"><Button variant={filter==="active"?"primary":"secondary"} onClick={()=>{setFilter("active");setPage(1)}}>En curso ({items.filter(x=>activeTrainingStatuses.has(x.status)&&x.status!==299541090).length})</Button><Button variant={filter==="pending"?"primary":"secondary"} onClick={()=>{setFilter("pending");setPage(1)}}>Por comenzar ({items.filter(x=>x.status===299541090).length})</Button><Button variant={filter==="completed"?"primary":"secondary"} onClick={()=>{setFilter("completed");setPage(1)}}>Finalizadas e historial ({items.filter(x=>!activeTrainingStatuses.has(x.status)).length})</Button></div><div className="flex flex-wrap gap-2"><label className="training-search"><Search size={16}/><input aria-label="Buscar capacitación" placeholder="Buscar capacitación" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><Button variant="secondary" disabled={Boolean(busy)} onClick={()=>void reload()}>Actualizar</Button><Button variant={view==="list"?"primary":"secondary"} aria-pressed={view==="list"} onClick={()=>setView("list")}><List size={16}/>Listado</Button><Button variant={view==="cards"?"primary":"secondary"} aria-pressed={view==="cards"} onClick={()=>setView("cards")}><LayoutGrid size={16}/>Bloques</Button></div></div>
    {error&&<div role="alert" className="training-notice training-notice-error">{error}</div>}
    {loading?<div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin"/></div>:<><div className={view==="list"?"training-assignment-list":"grid gap-4 md:grid-cols-2 xl:grid-cols-3"}>{view==="list"&&<div className="training-list-heading"><span>Capacitación</span><span>Avance del contenido</span><span>Fecha límite</span><span>Estado</span><span>Acción</span></div>}{rows.slice((currentPage-1)*9,currentPage*9).map(item=><article className="training-assignment-card" key={item.assignmentId}><div className="training-list-title"><span className="training-course-icon"><BookOpen size={22}/></span><div><small>Aprendizaje institucional · v{item.version}</small><h2>{item.training}</h2><p>{item.summary||"Experiencia de aprendizaje asignada por Gaia."}</p></div></div><div className="training-list-progress"><progress aria-label="Avance del contenido" value={item.progress} max={100}/><small>{item.progress}% del contenido {item.result!==null?`· Resultado: ${item.result}%`:""}</small></div><small className="training-list-due"><CalendarClock size={17}/>{trainingDueLabel(item.dueAt)}</small><Badge tone={item.status===299541093?"success":item.status===299541092?"warning":"neutral"}>{trainingStatus(item.status)}</Badge><Button variant={item.status===299541093?"secondary":"primary"} disabled={Boolean(busy)} onClick={()=>void open(item.assignmentId)}>{busy===item.assignmentId?<LoaderCircle className="animate-spin" size={16}/>:<BookOpen size={16}/>} {item.status===299541093?"Ver capacitación":item.progress||item.status!==299541090?"Continuar":"Comenzar"}</Button></article>)}</div>{!rows.length&&<div className="training-empty"><BookOpen size={30}/><strong>No hay capacitaciones para mostrar</strong><p>{query?"Prueba otra búsqueda.":"Aquí aparecerán las capacitaciones publicadas que te hayan asignado."}</p></div>}<footer className="training-section-toolbar"><span>{rows.length?`${(currentPage-1)*9+1}–${Math.min(currentPage*9,rows.length)} de ${rows.length}`:"0 resultados"}</span><div className="flex gap-2"><Button variant="secondary" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}>Anterior</Button><span className="self-center">{currentPage} / {pages}</span><Button variant="secondary" disabled={currentPage>=pages} onClick={()=>setPage(currentPage+1)}>Siguiente</Button></div></footer></>}
  </section>;
}

function TrainingMaterial({assignmentId,block,onProgress}:{assignmentId:string;block:Block;onProgress:(percentage:number,seconds:number)=>void}) {
  const url=safeUrl(block.externalUrl);const embed=url?youtubeEmbed(url):null;
  const resource=block.resourceId?`${apiUrl}/api/training/my/assignments/${assignmentId}/resources/${block.resourceId}`:null;
  return <div className="training-material">{block.html&&<p className={block.type===299541072?"training-notice":"whitespace-pre-wrap"}>{plain(block.html)}</p>}
    {block.type===299541074&&<TrainingVideo source={resource||url} embed={embed} title={block.name} onProgress={onProgress}/>}
    {resource&&block.type!==299541074&&<a className="gaia-button gaia-button-secondary" href={`${resource}?download=true`} target="_blank" rel="noopener noreferrer"><FileText size={17}/>Abrir / descargar documento</a>}
    {url&&block.type!==299541074&&<a className="gaia-button gaia-button-secondary" href={url} target="_blank" rel="noopener noreferrer">{block.actionText||"Abrir enlace"}</a>}
    {block.requiresConfirmation&&<small>Al confirmar declaras que revisaste y comprendiste este material.</small>}
  </div>;
}
