using System.Text.Json;
using Gaia.Modules.Helpdesk;

namespace Gaia.Api.Infrastructure.Dataverse.Helpdesk;

internal sealed class DataverseHelpdeskFormReader(IDataverseDelegatedClientFactory clients):IHelpdeskFormReader
{
 public async Task<HelpdeskServiceForm?> ReadForServiceAsync(Guid serviceId,CancellationToken token)
 {
  var client=await clients.CreateAsync();var service=await DataverseMetadataResolver.TableAsync(client,"gaia_servicio",token);var form=await DataverseMetadataResolver.TableAsync(client,"gaia_formularioservicio",token);var field=await DataverseMetadataResolver.TableAsync(client,"gaia_campoformulario",token);var option=await DataverseMetadataResolver.TableAsync(client,"gaia_opcioncampoformulario",token);
  var formLookup=service.Attribute("gaia_FormularioVigente");var visible=service.Attribute("gaia_VisibleAlSolicitante");var serviceRow=await DataverseMetadataResolver.ReadOneAsync(client,$"{service.EntitySetName}({serviceId:D})?$select=statecode,{visible},_{formLookup}_value",token);if(serviceRow is null||Int(serviceRow.Value,"statecode")!=0||!Bool(serviceRow.Value,visible))return null;var formId=GuidValue(serviceRow.Value,formLookup);if(formId==Guid.Empty)return null;
  var version=form.Attribute("gaia_Version");var status=form.Attribute("gaia_EstadoFormulario");var title=form.Attribute("gaia_Titulo");var instructions=form.Attribute("gaia_Instrucciones");var formRow=await DataverseMetadataResolver.ReadOneAsync(client,$"{form.EntitySetName}({formId:D})?$select=statecode,{version},{status},{title},{instructions}",token);if(formRow is null||Int(formRow.Value,"statecode")!=0||Int(formRow.Value,status)!=299540031)return null;
  var ff=FieldNames.From(field);var fieldRows=await DataverseJson.ReadAllAsync(client,$"{field.EntitySetName}?$select={field.PrimaryNameAttribute},{ff.Select}&$filter=statecode eq 0 and _{ff.Form}_value eq {formId:D} and {ff.Visible} eq true&$orderby={ff.Order} asc",token);var fieldIds=fieldRows.Select(x=>GuidDirect(x,field.PrimaryIdAttribute)).ToArray();var options=new Dictionary<Guid,List<HelpdeskFormOption>>();if(fieldIds.Length>0){var of=OptionNames.From(option);var clauses=string.Join(" or ",fieldIds.Select(id=>$"_{of.Field}_value eq {id:D}"));var optionRows=await DataverseJson.ReadAllAsync(client,$"{option.EntitySetName}?$select={of.Select}&$filter=statecode eq 0 and ({clauses})&$orderby={of.Order} asc",token);foreach(var row in optionRows){var owner=GuidValue(row,of.Field);if(!options.TryGetValue(owner,out var list))options[owner]=list=[];list.Add(new(GuidDirect(row,of.Id),Text(row,of.Code)??"",Text(row,of.Name)??"Opción",Bool(row,of.Default),Int(row,of.Order)));}}
  var fields=fieldRows.Select(row=>new HelpdeskFormField(GuidDirect(row,field.PrimaryIdAttribute),Text(row,ff.Code)??"",Text(row,field.PrimaryNameAttribute)??"Campo",Int(row,ff.DataType),Int(row,ff.ControlType),Text(row,ff.Help),Text(row,ff.Placeholder),Bool(row,ff.Required),Int(row,ff.Order),Int(row,ff.Width),NullableInt(row,ff.MinLength),NullableInt(row,ff.MaxLength),Decimal(row,ff.MinValue),Decimal(row,ff.MaxValue),Bool(row,ff.Multiple),NullableInt(row,ff.MaxFiles),Text(row,ff.FileTypes),true,options.GetValueOrDefault(GuidDirect(row,field.PrimaryIdAttribute),[]))).ToArray();return new(formId,Int(formRow.Value,version),Text(formRow.Value,title)??"Información de la solicitud",Text(formRow.Value,instructions),fields);
 }
 static string? Text(JsonElement x,string p)=>x.TryGetProperty(p,out var v)&&v.ValueKind==JsonValueKind.String?v.GetString():null;static int Int(JsonElement x,string p)=>DataverseJson.OptionalEncodedInt32(x,p)??0;static int? NullableInt(JsonElement x,string p)=>DataverseJson.OptionalEncodedInt32(x,p);static bool Bool(JsonElement x,string p)=>x.TryGetProperty(p,out var v)&&v.ValueKind==JsonValueKind.True;static decimal? Decimal(JsonElement x,string p)=>x.TryGetProperty(p,out var v)&&v.ValueKind==JsonValueKind.Number&&v.TryGetDecimal(out var d)?d:null;static Guid GuidValue(JsonElement x,string p)=>Guid.TryParse(Text(x,$"_{p}_value"),out var id)?id:Guid.Empty;static Guid GuidDirect(JsonElement x,string p)=>Guid.TryParse(Text(x,p),out var id)?id:Guid.Empty;
 sealed record FieldNames(string Id,string Code,string DataType,string ControlType,string Help,string Placeholder,string Required,string Order,string Width,string MinLength,string MaxLength,string MinValue,string MaxValue,string Multiple,string MaxFiles,string FileTypes,string Visible,string Form){public string Select=>string.Join(',',Id,Code,DataType,ControlType,Help,Placeholder,Required,Order,Width,MinLength,MaxLength,MinValue,MaxValue,Multiple,MaxFiles,FileTypes,Visible,$"_{Form}_value");public static FieldNames From(DataverseTableMetadata m)=>new(m.PrimaryIdAttribute,m.Attribute("gaia_Codigo"),m.Attribute("gaia_TipoDato"),m.Attribute("gaia_TipoControl"),m.Attribute("gaia_TextoAyuda"),m.Attribute("gaia_Placeholder"),m.Attribute("gaia_Requerido"),m.Attribute("gaia_Orden"),m.Attribute("gaia_AnchoColumnas"),m.Attribute("gaia_LongitudMinima"),m.Attribute("gaia_LongitudMaxima"),m.Attribute("gaia_ValorMinimo"),m.Attribute("gaia_ValorMaximo"),m.Attribute("gaia_PermiteVarios"),m.Attribute("gaia_MaximoArchivos"),m.Attribute("gaia_TiposArchivoPermitidos"),m.Attribute("gaia_Visible"),m.Attribute("gaia_Formulario"));}
 sealed record OptionNames(string Id,string Name,string Code,string Order,string Default,string Field){public string Select=>string.Join(',',Id,Name,Code,Order,Default,$"_{Field}_value");public static OptionNames From(DataverseTableMetadata m)=>new(m.PrimaryIdAttribute,m.PrimaryNameAttribute,m.Attribute("gaia_Codigo"),m.Attribute("gaia_Orden"),m.Attribute("gaia_EsPredeterminada"),m.Attribute("gaia_CampoFormulario"));}
}
