using System.Net.Http.Json;
using System.Net;
using System.Text.Json;
using System.Text.RegularExpressions;
using Gaia.Modules.Helpdesk;
using Gaia.Modules.Organization;
using Gaia.Modules.ThirdParties;

namespace Gaia.Api.Infrastructure.Dataverse.Helpdesk;

internal sealed partial class DataverseHelpdeskManagementStore(IDataverseDelegatedClientFactory clients,
    IOrganizationUnitReader unitReader,IOrganizationalAssignmentStore assignmentStore,
    Microsoft.AspNetCore.DataProtection.IDataProtectionProvider protection):IHelpdeskManagementStore
{
    public async Task<HelpdeskManagementCatalog> ReadCatalogAsync(CancellationToken token)
    {
        var client=await clients.CreateAsync();var service=await DataverseMetadataResolver.TableAsync(client,"gaia_servicio",token);var state=await DataverseMetadataResolver.TableAsync(client,"gaia_estadosolicitud",token);var third=await DataverseMetadataResolver.TableAsync(client,"gaia_terceros",token);var unit=await DataverseMetadataResolver.TableAsync(client,"gaia_organizacion",token);
        return new((await Options(client,service,"gaia_Codigo",token)).Values.OrderBy(x=>x.Name).ToArray(),(await Options(client,state,"gaia_Codigo",token)).Values.OrderBy(x=>x.Name).ToArray(),(await Options(client,third,null,token)).Values.OrderBy(x=>x.Name).ToArray(),(await Options(client,unit,null,token)).Values.OrderBy(x=>x.Name).ToArray());
    }

    public async Task ReassignAsync(Guid requestId,Guid actorId,ReassignHelpdeskRequest change,DateTimeOffset now,CancellationToken token)
    {
        var client=await clients.CreateAsync();var request=await DataverseMetadataResolver.TableAsync(client,"gaia_solicitud",token);var third=await DataverseMetadataResolver.TableAsync(client,"gaia_terceros",token);var unit=await DataverseMetadataResolver.TableAsync(client,"gaia_organizacion",token);var responsibleField=request.Attribute("gaia_ResponsableInterno");var unitField=request.Attribute("gaia_UnidadResponsable");var current=await DataverseMetadataResolver.ReadOneAsync(client,$"{request.EntitySetName}({requestId:D})?$select={request.PrimaryIdAttribute},statecode,_{responsibleField}_value,_{unitField}_value",token)??throw new KeyNotFoundException("La solicitud no existe.");if(Int(current,"statecode")!=0)throw new InvalidOperationException("La solicitud no está activa.");await RequireActive(client,third,change.ResponsibleId,"El responsable no existe o está inactivo.",token);if(change.UnitId.HasValue)await RequireActive(client,unit,change.UnitId.Value,"La unidad no existe o está inactiva.",token);
        var responsible=request.Relationship("gaia_ResponsableInterno","gaia_terceros");var organization=request.Relationship("gaia_UnidadResponsable","gaia_organizacion");var payload=new Dictionary<string,object?>{{responsible.NavigationProperty+"@odata.bind",$"/{third.EntitySetName}({change.ResponsibleId:D})"},{organization.NavigationProperty+"@odata.bind",change.UnitId.HasValue?$"/{unit.EntitySetName}({change.UnitId:D})":null}};using var patch=new HttpRequestMessage(HttpMethod.Patch,$"{request.EntitySetName}({requestId:D})"){Content=JsonContent.Create(payload)};patch.Headers.TryAddWithoutValidation("If-Match","*");using var response=await client.SendAsync(patch,token);await Ensure(response,token);
        try{await History(client,requestId,actorId,now,change.Reason,OptionalGuid(current,$"_{responsibleField}_value"),change.ResponsibleId,token);}catch{var rollback=new Dictionary<string,object?>{{responsible.NavigationProperty+"@odata.bind",Bind(third,OptionalGuid(current,$"_{responsibleField}_value"))},{organization.NavigationProperty+"@odata.bind",Bind(unit,OptionalGuid(current,$"_{unitField}_value"))}};using var undo=new HttpRequestMessage(HttpMethod.Patch,$"{request.EntitySetName}({requestId:D})"){Content=JsonContent.Create(rollback)};undo.Headers.TryAddWithoutValidation("If-Match","*");using var ignored=await client.SendAsync(undo,CancellationToken.None);throw;}
    }

    public async Task<HelpdeskAdminSnapshot> ReadAdministrationAsync(CancellationToken token)
    {
        var client=await clients.CreateAsync();var service=await DataverseMetadataResolver.TableAsync(client,"gaia_servicio",token);var form=await DataverseMetadataResolver.TableAsync(client,"gaia_formularioservicio",token);var field=await DataverseMetadataResolver.TableAsync(client,"gaia_campoformulario",token);var third=await DataverseMetadataResolver.TableAsync(client,"gaia_terceros",token);var people=await Options(client,third,null,token);
        var code=service.Attribute("gaia_Codigo");var description=service.Attribute("gaia_Descripcion");var instructions=service.Attribute("gaia_Instrucciones");var days=service.Attribute("gaia_DiasGestionHabiles");var allows=service.Attribute("gaia_PermiteAdjuntos");var max=service.Attribute("gaia_MaximoAdjuntos");var maxMb=service.Attribute("gaia_TamanoMaximoMB");var visible=service.Attribute("gaia_VisibleAlSolicitante");var order=service.Attribute("gaia_Orden");var responsible=service.Attribute("gaia_ResponsablePredeterminado");var organization=service.Attribute("gaia_UnidadResponsable");var currentForm=service.Attribute("gaia_FormularioVigente");
        var serviceRows=await DataverseJson.ReadAllAsync(client,$"{service.EntitySetName}?$select={service.PrimaryIdAttribute},{service.PrimaryNameAttribute},{code},{description},{instructions},{days},{allows},{max},{maxMb},{visible},{order},_{responsible}_value,_{organization}_value,_{currentForm}_value,statecode",token);var services=serviceRows.Select(x=>new HelpdeskAdminService(RequiredGuid(x,service.PrimaryIdAttribute),Text(x,code)??"",Text(x,service.PrimaryNameAttribute)??"",Text(x,description),Text(x,instructions),Int(x,days),Bool(x,allows),Int(x,max),Int(x,maxMb),Bool(x,visible),Int(x,order),OptionalGuid(x,$"_{responsible}_value")??Guid.Empty,OptionalGuid(x,$"_{organization}_value")??Guid.Empty,OptionalGuid(x,$"_{currentForm}_value"),Int(x,"statecode")==0)).OrderBy(x=>x.Order).ThenBy(x=>x.Name).ToArray();
        var version=form.Attribute("gaia_Version");var status=form.Attribute("gaia_EstadoFormulario");var title=form.Attribute("gaia_Titulo");var formInstructions=form.Attribute("gaia_Instrucciones");var published=form.Attribute("gaia_FechaPublicacion");var formService=form.Attribute("gaia_Servicio");var formRows=await DataverseJson.ReadAllAsync(client,$"{form.EntitySetName}?$select={form.PrimaryIdAttribute},{version},{status},{title},{formInstructions},{published},_{formService}_value,statecode",token);var fieldForm=field.Attribute("gaia_Formulario");var fieldRows=await DataverseJson.ReadAllAsync(client,$"{field.EntitySetName}?$select={field.PrimaryIdAttribute},_{fieldForm}_value&$filter=statecode eq 0",token);var counts=fieldRows.Select(x=>OptionalGuid(x,$"_{fieldForm}_value")).Where(x=>x.HasValue).GroupBy(x=>x!.Value).ToDictionary(x=>x.Key,x=>x.Count());var forms=formRows.Select(x=>new HelpdeskAdminForm(RequiredGuid(x,form.PrimaryIdAttribute),OptionalGuid(x,$"_{formService}_value")??Guid.Empty,Int(x,version),Int(x,status),Text(x,title)??"",Text(x,formInstructions),DateTimeValue(x,published),counts.GetValueOrDefault(RequiredGuid(x,form.PrimaryIdAttribute)),Int(x,"statecode")==0)).OrderByDescending(x=>x.Version).ToArray();
        var organizationUnits=(await unitReader.ListAsync(new(null,true,null),token)).Select(x=>new HelpdeskAdminUnit(x.Id,x.Code,x.Name,x.ParentId,x.Level)).ToArray();
        var currentDate=DateOnly.FromDateTime(DateTime.UtcNow);var assignments=(await assignmentStore.ListAsync(token)).Where(x=>x.IsActive&&(!x.StartDate.HasValue||x.StartDate<=currentDate)&&(!x.EndDate.HasValue||x.EndDate>=currentDate)).ToArray();
        var responsibles=people.Values.Select(person=>new HelpdeskAdminResponsible(person.Id,person.Name,assignments.Where(x=>x.ThirdPartyId==person.Id).Select(x=>x.OrganizationalUnitId).Distinct().ToArray())).OrderBy(x=>x.Name).ToArray();
        return new(services,forms,responsibles,organizationUnits);
    }

    public async Task<Guid> SaveServiceAsync(Guid? id,SaveHelpdeskService value,CancellationToken token)
    {
        var client=await clients.CreateAsync();var service=await DataverseMetadataResolver.TableAsync(client,"gaia_servicio",token);var third=await DataverseMetadataResolver.TableAsync(client,"gaia_terceros",token);var unit=await DataverseMetadataResolver.TableAsync(client,"gaia_organizacion",token);await RequireActive(client,third,value.ResponsibleId,"El responsable no existe o está inactivo.",token);await RequireActive(client,unit,value.UnitId,"La unidad no existe o está inactiva.",token);var payload=new Dictionary<string,object?>{{service.PrimaryNameAttribute,value.Name},{service.Attribute("gaia_Codigo"),value.Code},{service.Attribute("gaia_Descripcion"),value.Description},{service.Attribute("gaia_Instrucciones"),value.Instructions},{service.Attribute("gaia_DiasGestionHabiles"),value.BusinessDays},{service.Attribute("gaia_PermiteAdjuntos"),value.AllowsAttachments},{service.Attribute("gaia_MaximoAdjuntos"),value.MaximumAttachments},{service.Attribute("gaia_TamanoMaximoMB"),value.MaximumFileMb},{service.Attribute("gaia_VisibleAlSolicitante"),value.Visible},{service.Attribute("gaia_Orden"),value.Order},{service.Relationship("gaia_ResponsablePredeterminado","gaia_terceros").NavigationProperty+"@odata.bind",$"/{third.EntitySetName}({value.ResponsibleId:D})"},{service.Relationship("gaia_UnidadResponsable","gaia_organizacion").NavigationProperty+"@odata.bind",$"/{unit.EntitySetName}({value.UnitId:D})"},{"statecode",value.IsActive?0:1}};return await Write(client,service,id,payload,token);
    }

    public async Task<Guid> CreateFormDraftAsync(CreateHelpdeskFormDraft value,CancellationToken token)
    {
        var client=await clients.CreateAsync();var service=await DataverseMetadataResolver.TableAsync(client,"gaia_servicio",token);var form=await DataverseMetadataResolver.TableAsync(client,"gaia_formularioservicio",token);await RequireActive(client,service,value.ServiceId,"El servicio no existe o está inactivo.",token);var serviceField=form.Attribute("gaia_Servicio");var versionField=form.Attribute("gaia_Version");var statusField=form.Attribute("gaia_EstadoFormulario");var rows=await DataverseJson.ReadAllAsync(client,$"{form.EntitySetName}?$select={form.PrimaryIdAttribute},{versionField},{statusField}&$filter=_{serviceField}_value eq {value.ServiceId:D}",token);if(rows.Any(x=>Int(x,statusField)==299540030&&Int(x,"statecode")==0))throw new InvalidOperationException("Ya existe una versión borrador para este servicio.");var next=rows.Select(x=>Int(x,versionField)).DefaultIfEmpty(0).Max()+1;var payload=new Dictionary<string,object?>{{form.PrimaryNameAttribute,$"{value.Title} v{next}"},{versionField,next},{statusField,form.EncodedIntegerValue("gaia_EstadoFormulario",299540030)},{form.Attribute("gaia_Titulo"),value.Title},{form.Attribute("gaia_Instrucciones"),value.Instructions},{form.Relationship("gaia_Servicio","gaia_servicio").NavigationProperty+"@odata.bind",$"/{service.EntitySetName}({value.ServiceId:D})"},{"statecode",0}};var createdId=await Write(client,form,null,payload,token);var source=rows.Where(x=>Int(x,statusField)==299540031).OrderByDescending(x=>Int(x,versionField)).FirstOrDefault();if(source.ValueKind!=JsonValueKind.Undefined){var definition=await ReadFormAsync(RequiredGuid(source,form.PrimaryIdAttribute),token);foreach(var sourceField in definition.Fields.OrderBy(x=>x.Order)){await SaveFormFieldAsync(createdId,null,new(sourceField.Code,sourceField.Label,sourceField.DataType,sourceField.ControlType,sourceField.HelpText,sourceField.Placeholder,sourceField.Required,sourceField.Order,sourceField.Width,sourceField.MinimumLength,sourceField.MaximumLength,sourceField.MinimumValue,sourceField.MaximumValue,sourceField.AllowsMultiple,sourceField.MaximumFiles,sourceField.AllowedFileTypes,true,sourceField.Options.Select(option=>new SaveHelpdeskFormOption(null,option.Code,option.Label,option.Order,option.IsDefault)).ToArray()),token);}}return createdId;
    }

    public async Task PublishFormAsync(Guid formId,Guid actorId,DateTimeOffset now,CancellationToken token)
    {
        var client=await clients.CreateAsync();var form=await DataverseMetadataResolver.TableAsync(client,"gaia_formularioservicio",token);var field=await DataverseMetadataResolver.TableAsync(client,"gaia_campoformulario",token);var service=await DataverseMetadataResolver.TableAsync(client,"gaia_servicio",token);var third=await DataverseMetadataResolver.TableAsync(client,"gaia_terceros",token);await RequireActive(client,third,actorId,"El administrador no está asociado con un tercero activo.",token);var status=form.Attribute("gaia_EstadoFormulario");var serviceField=form.Attribute("gaia_Servicio");var row=await DataverseMetadataResolver.ReadOneAsync(client,$"{form.EntitySetName}({formId:D})?$select={form.PrimaryIdAttribute},{status},_{serviceField}_value,statecode",token)??throw new KeyNotFoundException("El formulario no existe.");if(Int(row,status)!=299540030||Int(row,"statecode")!=0)throw new InvalidOperationException("Solo puede publicarse un formulario borrador activo.");var serviceId=OptionalGuid(row,$"_{serviceField}_value")??throw new InvalidOperationException("El formulario no tiene servicio.");var fieldForm=field.Attribute("gaia_Formulario");var fields=await DataverseJson.ReadAllAsync(client,$"{field.EntitySetName}?$select={field.PrimaryIdAttribute}&$filter=statecode eq 0 and _{fieldForm}_value eq {formId:D}",token);if(fields.Count==0)throw new InvalidOperationException("Agrega al menos un campo antes de publicar el formulario.");
        var published=await DataverseJson.ReadAllAsync(client,$"{form.EntitySetName}?$select={form.PrimaryIdAttribute},{status}&$filter=statecode eq 0 and _{serviceField}_value eq {serviceId:D} and {status} eq {form.EncodedIntegerLiteral("gaia_EstadoFormulario",299540031)}",token);foreach(var old in published){await Write(client,form,RequiredGuid(old,form.PrimaryIdAttribute),new Dictionary<string,object?>{{status,form.EncodedIntegerValue("gaia_EstadoFormulario",299540032)}},token);}await Write(client,form,formId,new Dictionary<string,object?>{{status,form.EncodedIntegerValue("gaia_EstadoFormulario",299540031)},{form.Attribute("gaia_FechaPublicacion"),now},{form.Relationship("gaia_PublicadoPor","gaia_terceros").NavigationProperty+"@odata.bind",$"/{third.EntitySetName}({actorId:D})"}},token);await Write(client,service,serviceId,new Dictionary<string,object?>{{service.Relationship("gaia_FormularioVigente","gaia_formularioservicio").NavigationProperty+"@odata.bind",$"/{form.EntitySetName}({formId:D})"}},token);
    }

    private static async Task History(HttpClient client,Guid requestId,Guid actorId,DateTimeOffset now,string reason,Guid? before,Guid after,CancellationToken token){var history=await DataverseMetadataResolver.TableAsync(client,"gaia_historialsolicitud",token);var request=await DataverseMetadataResolver.TableAsync(client,"gaia_solicitud",token);var actor=await DataverseMetadataResolver.TableAsync(client,"gaia_terceros",token);var payload=new Dictionary<string,object?>{{history.PrimaryNameAttribute,"Responsable reasignado"},{history.Attribute("gaia_OperacionId"),Guid.NewGuid().ToString("D")},{history.Attribute("gaia_TipoMovimiento"),history.EncodedIntegerValue("gaia_TipoMovimiento",299540104)},{history.Attribute("gaia_Origen"),history.EncodedIntegerValue("gaia_Origen",299540121)},{history.Attribute("gaia_CampoModificado"),"ResponsableInterno"},{history.Attribute("gaia_ValorAnterior"),before?.ToString("D")},{history.Attribute("gaia_ValorNuevo"),after.ToString("D")},{history.Attribute("gaia_Detalle"),reason},{history.Attribute("gaia_VisibleAlSolicitante"),false},{history.Attribute("gaia_FechaEvento"),now},{history.Relationship("gaia_Solicitud","gaia_solicitud").NavigationProperty+"@odata.bind",$"/{request.EntitySetName}({requestId:D})"},{history.Relationship("gaia_Actor","gaia_terceros").NavigationProperty+"@odata.bind",$"/{actor.EntitySetName}({actorId:D})"},{"statecode",0}};using var response=await client.PostAsJsonAsync(history.EntitySetName,payload,token);await Ensure(response,token);}
    private static async Task RequireActive(HttpClient client,DataverseTableMetadata table,Guid id,string message,CancellationToken token){var row=await DataverseMetadataResolver.ReadOneAsync(client,$"{table.EntitySetName}({id:D})?$select={table.PrimaryIdAttribute},statecode",token);if(row is null||Int(row.Value,"statecode")!=0)throw new ArgumentException(message);}
    private static async Task<Dictionary<Guid,HelpdeskManagementOption>> Options(HttpClient client,DataverseTableMetadata table,string? codeSchema,CancellationToken token){var code=codeSchema is null?null:table.Attribute(codeSchema);var select=code is null?$"{table.PrimaryIdAttribute},{table.PrimaryNameAttribute}":$"{table.PrimaryIdAttribute},{table.PrimaryNameAttribute},{code}";var rows=await DataverseJson.ReadAllAsync(client,$"{table.EntitySetName}?$select={select}&$filter=statecode eq 0",token);return rows.ToDictionary(x=>RequiredGuid(x,table.PrimaryIdAttribute),x=>new HelpdeskManagementOption(RequiredGuid(x,table.PrimaryIdAttribute),Text(x,table.PrimaryNameAttribute)??"Sin nombre",code is null?null:Text(x,code)));}
    private static async Task<Dictionary<Guid,State>> States(HttpClient client,DataverseTableMetadata table,CancellationToken token){var color=table.Attribute("gaia_Color");var final=table.Attribute("gaia_EsFinal");var rows=await DataverseJson.ReadAllAsync(client,$"{table.EntitySetName}?$select={table.PrimaryIdAttribute},{table.PrimaryNameAttribute},{color},{final}&$filter=statecode eq 0",token);return rows.ToDictionary(x=>RequiredGuid(x,table.PrimaryIdAttribute),x=>new State(Text(x,table.PrimaryNameAttribute)??"Sin estado",Text(x,color),Bool(x,final)));}
    private static async Task Ensure(HttpResponseMessage response,CancellationToken token){if(response.IsSuccessStatusCode)return;var detail=await response.Content.ReadAsStringAsync(token);throw new InvalidOperationException($"Dataverse rechazó la operación ({(int)response.StatusCode}): {detail[..Math.Min(detail.Length,300)]}");}
    private static async Task<Guid> Write(HttpClient client,DataverseTableMetadata table,Guid? id,Dictionary<string,object?> payload,CancellationToken token){if(!id.HasValue){using var created=await client.PostAsJsonAsync(table.EntitySetName,payload,token);await Ensure(created,token);var uri=created.Headers.TryGetValues("OData-EntityId",out var values)?values.SingleOrDefault():null;var match=Regex.Match(uri??"",@"\(([0-9a-f-]{36})\)$");return match.Success?System.Guid.Parse(match.Groups[1].Value):throw new InvalidOperationException("Dataverse no devolvió el identificador creado.");}using var patch=new HttpRequestMessage(HttpMethod.Patch,$"{table.EntitySetName}({id:D})"){Content=JsonContent.Create(payload)};patch.Headers.TryAddWithoutValidation("If-Match","*");using var response=await client.SendAsync(patch,token);if(response.StatusCode==HttpStatusCode.NotFound)throw new KeyNotFoundException("El registro no existe.");await Ensure(response,token);return id.Value;}
    private static string? Bind(DataverseTableMetadata table,Guid? id)=>id.HasValue?$"/{table.EntitySetName}({id:D})":null;private static string Name(Dictionary<Guid,HelpdeskManagementOption> values,Guid? id,string fallback)=>id.HasValue&&values.TryGetValue(id.Value,out var value)?value.Name:fallback;private static string? NameOrNull(Dictionary<Guid,HelpdeskManagementOption> values,Guid? id)=>id.HasValue&&values.TryGetValue(id.Value,out var value)?value.Name:null;private static string? Text(JsonElement row,string name)=>row.TryGetProperty(name,out var value)&&value.ValueKind==JsonValueKind.String?value.GetString():null;private static Guid? OptionalGuid(JsonElement row,string name)=>System.Guid.TryParse(Text(row,name),out var id)?id:null;private static Guid RequiredGuid(JsonElement row,string name)=>OptionalGuid(row,name)??throw new InvalidOperationException($"Dataverse no devolvió {name}.");private static int Int(JsonElement row,string name)=>DataverseJson.OptionalInt32(row,name)??0;private static bool Bool(JsonElement row,string name)=>row.TryGetProperty(name,out var value)&&value.ValueKind==JsonValueKind.True;private static DateOnly? Date(JsonElement row,string name)=>DateOnly.TryParse(Text(row,name),out var value)?value:null;private static DateTimeOffset? DateTimeValue(JsonElement row,string name)=>DateTimeOffset.TryParse(Text(row,name),out var value)?value:null;private sealed record State(string Name,string? Color,bool Final);
}
