using System.Net.Http.Json;
using System.Text.Json;
using Gaia.Modules.Helpdesk;

namespace Gaia.Api.Infrastructure.Dataverse.Helpdesk;

internal sealed partial class DataverseHelpdeskManagementStore
{
    public async Task<HelpdeskAdminFormDefinition> ReadFormAsync(Guid formId,CancellationToken token)
    {
        var client=await clients.CreateAsync();var form=await DataverseMetadataResolver.TableAsync(client,"gaia_formularioservicio",token);var field=await DataverseMetadataResolver.TableAsync(client,"gaia_campoformulario",token);var option=await DataverseMetadataResolver.TableAsync(client,"gaia_opcioncampoformulario",token);var status=form.Attribute("gaia_EstadoFormulario");var service=form.Attribute("gaia_Servicio");var row=await DataverseMetadataResolver.ReadOneAsync(client,$"{form.EntitySetName}({formId:D})?$select={form.PrimaryIdAttribute},{form.Attribute("gaia_Version")},{status},{form.Attribute("gaia_Titulo")},{form.Attribute("gaia_Instrucciones")},{form.Attribute("gaia_FechaPublicacion")},_{service}_value,statecode",token)??throw new KeyNotFoundException("El formulario no existe.");
        var fieldForm=field.Attribute("gaia_Formulario");var fields=await DataverseJson.ReadAllAsync(client,$"{field.EntitySetName}?$select={field.PrimaryIdAttribute},{field.PrimaryNameAttribute},{field.Attribute("gaia_Codigo")},{field.Attribute("gaia_TipoDato")},{field.Attribute("gaia_TipoControl")},{field.Attribute("gaia_TextoAyuda")},{field.Attribute("gaia_Placeholder")},{field.Attribute("gaia_Requerido")},{field.Attribute("gaia_Orden")},{field.Attribute("gaia_AnchoColumnas")},{field.Attribute("gaia_LongitudMinima")},{field.Attribute("gaia_LongitudMaxima")},{field.Attribute("gaia_ValorMinimo")},{field.Attribute("gaia_ValorMaximo")},{field.Attribute("gaia_PermiteVarios")},{field.Attribute("gaia_MaximoArchivos")},{field.Attribute("gaia_TiposArchivoPermitidos")},statecode&$filter=_{fieldForm}_value eq {formId:D}",token);var ids=fields.Select(x=>RequiredGuid(x,field.PrimaryIdAttribute)).ToHashSet();var optionField=option.Attribute("gaia_CampoFormulario");var options=await DataverseJson.ReadAllAsync(client,$"{option.EntitySetName}?$select={option.PrimaryIdAttribute},{option.PrimaryNameAttribute},{option.Attribute("gaia_Codigo")},{option.Attribute("gaia_Orden")},{option.Attribute("gaia_EsPredeterminada")},_{optionField}_value,statecode",token);var grouped=options.Where(x=>OptionalGuid(x,$"_{optionField}_value") is {} id&&ids.Contains(id)&&Int(x,"statecode")==0).GroupBy(x=>OptionalGuid(x,$"_{optionField}_value")!.Value).ToDictionary(x=>x.Key,x=>(IReadOnlyList<HelpdeskFormOption>)x.Select(o=>new HelpdeskFormOption(RequiredGuid(o,option.PrimaryIdAttribute),Text(o,option.Attribute("gaia_Codigo"))??"",Text(o,option.PrimaryNameAttribute)??"",Bool(o,option.Attribute("gaia_EsPredeterminada")),Int(o,option.Attribute("gaia_Orden")))).OrderBy(o=>o.Order).ToArray());
        var definitions=fields.Where(x=>Int(x,"statecode")==0).Select(x=>new HelpdeskFormField(RequiredGuid(x,field.PrimaryIdAttribute),Text(x,field.Attribute("gaia_Codigo"))??"",Text(x,field.PrimaryNameAttribute)??"",Int(x,field.Attribute("gaia_TipoDato")),Int(x,field.Attribute("gaia_TipoControl")),Text(x,field.Attribute("gaia_TextoAyuda")),Text(x,field.Attribute("gaia_Placeholder")),Bool(x,field.Attribute("gaia_Requerido")),Int(x,field.Attribute("gaia_Orden")),Int(x,field.Attribute("gaia_AnchoColumnas")),NullableInt(x,field.Attribute("gaia_LongitudMinima")),NullableInt(x,field.Attribute("gaia_LongitudMaxima")),NullableDecimal(x,field.Attribute("gaia_ValorMinimo")),NullableDecimal(x,field.Attribute("gaia_ValorMaximo")),Bool(x,field.Attribute("gaia_PermiteVarios")),NullableInt(x,field.Attribute("gaia_MaximoArchivos")),Text(x,field.Attribute("gaia_TiposArchivoPermitidos")),grouped.GetValueOrDefault(RequiredGuid(x,field.PrimaryIdAttribute),[]))).OrderBy(x=>x.Order).ToArray();var summary=new HelpdeskAdminForm(formId,OptionalGuid(row,$"_{service}_value")??Guid.Empty,Int(row,form.Attribute("gaia_Version")),Int(row,status),Text(row,form.Attribute("gaia_Titulo"))??"",Text(row,form.Attribute("gaia_Instrucciones")),DateTimeValue(row,form.Attribute("gaia_FechaPublicacion")),definitions.Length,Int(row,"statecode")==0);return new(summary,definitions);
    }

    public async Task<Guid> SaveFormFieldAsync(Guid formId,Guid? fieldId,SaveHelpdeskFormField value,CancellationToken token)
    {
        var client=await clients.CreateAsync();var form=await DataverseMetadataResolver.TableAsync(client,"gaia_formularioservicio",token);var field=await DataverseMetadataResolver.TableAsync(client,"gaia_campoformulario",token);var option=await DataverseMetadataResolver.TableAsync(client,"gaia_opcioncampoformulario",token);var status=form.Attribute("gaia_EstadoFormulario");var formRow=await DataverseMetadataResolver.ReadOneAsync(client,$"{form.EntitySetName}({formId:D})?$select={form.PrimaryIdAttribute},{status},statecode",token)??throw new KeyNotFoundException("El formulario no existe.");if(Int(formRow,status)!=299540030||Int(formRow,"statecode")!=0)throw new InvalidOperationException("Solo pueden modificarse formularios borrador activos.");
        var payload=new Dictionary<string,object?>{{field.PrimaryNameAttribute,value.Label},{field.Attribute("gaia_Codigo"),value.Code},{field.Attribute("gaia_TipoDato"),field.EncodedIntegerValue("gaia_TipoDato",value.DataType)},{field.Attribute("gaia_TipoControl"),field.EncodedIntegerValue("gaia_TipoControl",value.ControlType)},{field.Attribute("gaia_TextoAyuda"),value.HelpText},{field.Attribute("gaia_Placeholder"),value.Placeholder},{field.Attribute("gaia_Requerido"),value.Required},{field.Attribute("gaia_Orden"),value.Order},{field.Attribute("gaia_AnchoColumnas"),value.Width},{field.Attribute("gaia_LongitudMinima"),value.MinimumLength},{field.Attribute("gaia_LongitudMaxima"),value.MaximumLength},{field.Attribute("gaia_ValorMinimo"),value.MinimumValue},{field.Attribute("gaia_ValorMaximo"),value.MaximumValue},{field.Attribute("gaia_PermiteVarios"),value.AllowsMultiple},{field.Attribute("gaia_MaximoArchivos"),value.MaximumFiles},{field.Attribute("gaia_TiposArchivoPermitidos"),value.AllowedFileTypes},{field.Attribute("gaia_Visible"),value.Visible},{field.Relationship("gaia_Formulario","gaia_formularioservicio").NavigationProperty+"@odata.bind",$"/{form.EntitySetName}({formId:D})"},{"statecode",0}};var id=await Write(client,field,fieldId,payload,token);var optionField=option.Attribute("gaia_CampoFormulario");var existing=await DataverseJson.ReadAllAsync(client,$"{option.EntitySetName}?$select={option.PrimaryIdAttribute},{option.Attribute("gaia_Codigo")},_{optionField}_value,statecode&$filter=_{optionField}_value eq {id:D}",token);var retained=new HashSet<Guid>();foreach(var item in value.Options){var match=item.Id.HasValue?existing.SingleOrDefault(x=>RequiredGuid(x,option.PrimaryIdAttribute)==item.Id):existing.SingleOrDefault(x=>string.Equals(Text(x,option.Attribute("gaia_Codigo")),item.Code,StringComparison.OrdinalIgnoreCase));var optionId=match.ValueKind==JsonValueKind.Undefined?(Guid?)null:RequiredGuid(match,option.PrimaryIdAttribute);var optionPayload=new Dictionary<string,object?>{{option.PrimaryNameAttribute,item.Label},{option.Attribute("gaia_Codigo"),item.Code},{option.Attribute("gaia_Orden"),item.Order},{option.Attribute("gaia_EsPredeterminada"),item.IsDefault},{option.Relationship("gaia_CampoFormulario","gaia_campoformulario").NavigationProperty+"@odata.bind",$"/{field.EntitySetName}({id:D})"},{"statecode",item.IsActive?0:1}};retained.Add(await Write(client,option,optionId,optionPayload,token));}foreach(var old in existing.Where(x=>Int(x,"statecode")==0&&!retained.Contains(RequiredGuid(x,option.PrimaryIdAttribute))))await Write(client,option,RequiredGuid(old,option.PrimaryIdAttribute),new Dictionary<string,object?>{{"statecode",1}},token);return id;
    }

    private static int? NullableInt(JsonElement row,string name)=>DataverseJson.OptionalInt32(row,name);
    private static decimal? NullableDecimal(JsonElement row,string name)=>row.TryGetProperty(name,out var value)&&value.ValueKind==JsonValueKind.Number&&value.TryGetDecimal(out var result)?result:null;
}
