using System.Globalization;
using System.Text.Json;
using Gaia.Modules.Helpdesk;

namespace Gaia.Api.Infrastructure.Dataverse.Helpdesk;

internal sealed partial class DataverseHelpdeskWorkflowExecutionWriter
{
    public async Task<HelpdeskManagementForm> ReadManagementFormAsync(Guid managementId,Guid actorId,CancellationToken token)
    {
        var client=await clients.CreateAsync();var context=await ManagementFormContext(client,managementId,actorId,token);var form=await ReadStageFormAsync(context.StepId,token);if(form is null)return new(managementId,context.RequestId,null,[]);
        var values=await ReadManagementAnswers(client,managementId,form,token);return new(managementId,context.RequestId,form,values);
    }

    public async Task<IReadOnlyList<SavedHelpdeskManagementAnswer>> SaveManagementAnswersAsync(Guid managementId,Guid actorId,SaveHelpdeskManagementAnswers command,CancellationToken token)
    {
        var client=await clients.CreateAsync();var context=await ManagementFormContext(client,managementId,actorId,token);var form=await ReadStageFormAsync(context.StepId,token)??throw new InvalidOperationException("Esta etapa no tiene un formulario configurado.");var fields=form.Fields.ToDictionary(x=>x.Id);var saved=new List<SavedHelpdeskManagementAnswer>();
        foreach(var answer in command.Answers)
        {
            if(!fields.TryGetValue(answer.FieldId,out var field)||!field.Visible)throw new ArgumentException("La respuesta contiene un campo que no pertenece al formulario activo de la etapa.");
            var normalized=ValidateAndNormalize(field,answer);var responseId=await UpsertManagementAnswer(client,managementId,field,normalized,token);await ReplaceManagementOptions(client,responseId,field,normalized.OptionIds??[],token);saved.Add(new(field.Id,responseId));
        }
        return saved;
    }

    private async Task ValidateManagementStageFormAsync(Guid managementId,HttpClient client,CancellationToken token)
    {
        var management=await DataverseMetadataResolver.TableAsync(client,"gaia_gestionsolicitud",token);var stepRelation=management.Relationship("gaia_PasoFlujo","gaia_pasoflujo");var row=await DataverseMetadataResolver.ReadOneAsync(client,$"{management.EntitySetName}({managementId:D})?$select=_{stepRelation.ReferencingAttribute}_value",token)??throw new KeyNotFoundException("La gestión no existe.");var form=await ReadStageFormAsync(RequiredGuid(row,$"_{stepRelation.ReferencingAttribute}_value"),token);if(form is null)return;var answers=await ReadManagementAnswers(client,managementId,form,token);var byField=answers.ToDictionary(x=>x.FieldId);
        var attachment=await DataverseMetadataResolver.TableAsync(client,"gaia_adjuntosolicitud",token);var responseRelation=attachment.Relationship("gaia_RespuestaCampoGestion","gaia_respuestacampogestion");var files=await DataverseJson.ReadAllAsync(client,$"{attachment.EntitySetName}?$select={attachment.PrimaryIdAttribute},_{responseRelation.ReferencingAttribute}_value&$filter=statecode eq 0",token);var responsesWithFiles=files.Select(x=>OptionalGuid(x,$"_{responseRelation.ReferencingAttribute}_value")).Where(x=>x.HasValue).Select(x=>x!.Value).ToHashSet();
        foreach(var field in form.Fields.Where(x=>x.Visible&&x.Required))
        {
            if(!byField.TryGetValue(field.Id,out var answer))throw new InvalidOperationException($"Completa el campo obligatorio {field.Label} antes de finalizar la gestión.");
            if(field.DataType==299540046&&answer.OptionIds.Count==0)throw new InvalidOperationException($"Selecciona una opción para {field.Label}.");
            if(field.DataType==299540047&&!responsesWithFiles.Contains(answer.ResponseId))throw new InvalidOperationException($"Adjunta al menos un archivo en {field.Label}.");
            if(field.DataType is not (299540045 or 299540046 or 299540047)&&string.IsNullOrWhiteSpace(answer.Value))throw new InvalidOperationException($"Completa el campo obligatorio {field.Label}.");
        }
    }

    private static async Task<(Guid StepId,Guid RequestId)> ManagementFormContext(HttpClient client,Guid managementId,Guid actorId,CancellationToken token)
    {
        var management=await DataverseMetadataResolver.TableAsync(client,"gaia_gestionsolicitud",token);var step=management.Relationship("gaia_PasoFlujo","gaia_pasoflujo");var request=management.Relationship("gaia_Solicitud","gaia_solicitud");var responsible=management.Relationship("gaia_Responsable","gaia_terceros");var unit=management.Relationship("gaia_UnidadResponsable","gaia_organizacion");var status=management.Attribute("gaia_Estado");var row=await DataverseMetadataResolver.ReadOneAsync(client,$"{management.EntitySetName}({managementId:D})?$select={status},_{step.ReferencingAttribute}_value,_{request.ReferencingAttribute}_value,_{responsible.ReferencingAttribute}_value,_{unit.ReferencingAttribute}_value,statecode",token)??throw new KeyNotFoundException("La gestión no existe.");if(Int(row,"statecode")!=0||Int(row,status) is HelpdeskWorkflowValues.ManagementCompleted or HelpdeskWorkflowValues.ManagementCancelled)throw new InvalidOperationException("La gestión ya no admite captura de información.");HelpdeskWorkflowAuthorization.Demand(actorId,OptionalGuid(row,$"_{responsible.ReferencingAttribute}_value"),OptionalGuid(row,$"_{unit.ReferencingAttribute}_value"),await ActorUnits(client,actorId,token),false);return(RequiredGuid(row,$"_{step.ReferencingAttribute}_value"),RequiredGuid(row,$"_{request.ReferencingAttribute}_value"));
    }

    private static HelpdeskFieldAnswer ValidateAndNormalize(HelpdeskFormField field,HelpdeskFieldAnswer answer)
    {
        var value=answer.Value?.Trim();var options=answer.OptionIds?.Distinct().ToArray()??[];
        if(field.Required&&field.DataType is not (299540045 or 299540046 or 299540047)&&string.IsNullOrWhiteSpace(value))throw new ArgumentException($"El campo {field.Label} es obligatorio.");
        if(field.MinimumLength.HasValue&&value?.Length<field.MinimumLength)throw new ArgumentException($"{field.Label} requiere al menos {field.MinimumLength} caracteres.");if(field.MaximumLength.HasValue&&value?.Length>field.MaximumLength)throw new ArgumentException($"{field.Label} admite máximo {field.MaximumLength} caracteres.");
        switch(field.DataType){case 299540041:if(!int.TryParse(value,NumberStyles.Integer,CultureInfo.InvariantCulture,out _))throw new ArgumentException($"{field.Label} requiere un número entero.");break;case 299540042:if(!decimal.TryParse(value,NumberStyles.Number,CultureInfo.InvariantCulture,out var number))throw new ArgumentException($"{field.Label} requiere un número decimal.");if(field.MinimumValue.HasValue&&number<field.MinimumValue||field.MaximumValue.HasValue&&number>field.MaximumValue)throw new ArgumentException($"{field.Label} está fuera del rango permitido.");break;case 299540043:if(!DateOnly.TryParse(value,CultureInfo.InvariantCulture,DateTimeStyles.None,out _))throw new ArgumentException($"{field.Label} requiere una fecha válida.");break;case 299540044:if(!DateTimeOffset.TryParse(value,CultureInfo.InvariantCulture,DateTimeStyles.RoundtripKind,out _))throw new ArgumentException($"{field.Label} requiere fecha y hora válidas.");break;case 299540045:if(!bool.TryParse(value,out _))throw new ArgumentException($"{field.Label} requiere verdadero o falso.");break;case 299540046:if(field.Required&&options.Length==0)throw new ArgumentException($"Selecciona una opción para {field.Label}.");if(!field.AllowsMultiple&&options.Length>1)throw new ArgumentException($"{field.Label} admite una sola opción.");break;}
        return answer with{Value=value,OptionIds=options};
    }

    private static async Task<Guid> UpsertManagementAnswer(HttpClient client,Guid managementId,HelpdeskFormField field,HelpdeskFieldAnswer answer,CancellationToken token)
    {
        var response=await DataverseMetadataResolver.TableAsync(client,"gaia_respuestacampogestion",token);var management=await DataverseMetadataResolver.TableAsync(client,"gaia_gestionsolicitud",token);var fieldTable=await DataverseMetadataResolver.TableAsync(client,"gaia_campoformulariopaso",token);var managementRelation=response.Relationship("gaia_GestionSolicitud","gaia_gestionsolicitud");var fieldRelation=response.Relationship("gaia_CampoFormularioPaso","gaia_campoformulariopaso");var rows=await DataverseJson.ReadAllAsync(client,$"{response.EntitySetName}?$select={response.PrimaryIdAttribute}&$filter=statecode eq 0 and _{managementRelation.ReferencingAttribute}_value eq {managementId:D} and _{fieldRelation.ReferencingAttribute}_value eq {field.Id:D}&$top=2",token);if(rows.Count>1)throw new InvalidOperationException("La gestión tiene respuestas duplicadas para un campo.");
        var payload=new Dictionary<string,object?>{{response.PrimaryNameAttribute,$"{field.Code} · {managementId:D}"},{response.Attribute("gaia_ValorTexto"),null},{response.Attribute("gaia_ValorEntero"),null},{response.Attribute("gaia_ValorDecimal"),null},{response.Attribute("gaia_ValorFecha"),null},{response.Attribute("gaia_ValorFechaHora"),null},{response.Attribute("gaia_ValorBooleano"),null},{managementRelation.NavigationProperty+"@odata.bind",$"/{management.EntitySetName}({managementId:D})"},{fieldRelation.NavigationProperty+"@odata.bind",$"/{fieldTable.EntitySetName}({field.Id:D})"},{"statecode",0}};
        switch(field.DataType){case 299540040:payload[response.Attribute("gaia_ValorTexto")]=answer.Value;break;case 299540041:payload[response.Attribute("gaia_ValorEntero")]=int.Parse(answer.Value!,CultureInfo.InvariantCulture);break;case 299540042:payload[response.Attribute("gaia_ValorDecimal")]=decimal.Parse(answer.Value!,CultureInfo.InvariantCulture);break;case 299540043:payload[response.Attribute("gaia_ValorFecha")]=DateOnly.Parse(answer.Value!,CultureInfo.InvariantCulture).ToString("yyyy-MM-dd",CultureInfo.InvariantCulture);break;case 299540044:payload[response.Attribute("gaia_ValorFechaHora")]=DateTimeOffset.Parse(answer.Value!,CultureInfo.InvariantCulture,DateTimeStyles.RoundtripKind);break;case 299540045:payload[response.Attribute("gaia_ValorBooleano")]=bool.Parse(answer.Value!);break;}
        if(rows.Count==0)return await Create(client,response.EntitySetName,payload,token);var id=RequiredGuid(rows[0],response.PrimaryIdAttribute);await Patch(client,response.EntitySetName,id,payload,token);return id;
    }

    private static async Task ReplaceManagementOptions(HttpClient client,Guid responseId,HelpdeskFormField field,IReadOnlyList<Guid> optionIds,CancellationToken token)
    {
        var junction=await DataverseMetadataResolver.TableAsync(client,"gaia_respuestaopciongestion",token);var response=await DataverseMetadataResolver.TableAsync(client,"gaia_respuestacampogestion",token);var option=await DataverseMetadataResolver.TableAsync(client,"gaia_opcioncampoformulariopaso",token);var responseRelation=junction.Relationship("gaia_RespuestaCampoGestion","gaia_respuestacampogestion");var optionRelation=junction.Relationship("gaia_OpcionCampoFormularioPaso","gaia_opcioncampoformulariopaso");var optionField=option.Relationship("gaia_CampoFormularioPaso","gaia_campoformulariopaso");var existing=await DataverseJson.ReadAllAsync(client,$"{junction.EntitySetName}?$select={junction.PrimaryIdAttribute},_{optionRelation.ReferencingAttribute}_value,statecode&$filter=_{responseRelation.ReferencingAttribute}_value eq {responseId:D}",token);var selected=optionIds.ToHashSet();
        foreach(var optionId in selected){var optionRow=await DataverseMetadataResolver.ReadOneAsync(client,$"{option.EntitySetName}({optionId:D})?$select=_{optionField.ReferencingAttribute}_value,statecode",token);if(optionRow is null||Int(optionRow.Value,"statecode")!=0||OptionalGuid(optionRow.Value,$"_{optionField.ReferencingAttribute}_value")!=field.Id)throw new ArgumentException("Una opción no pertenece al campo indicado.");var old=existing.SingleOrDefault(x=>OptionalGuid(x,$"_{optionRelation.ReferencingAttribute}_value")==optionId);if(old.ValueKind!=JsonValueKind.Undefined){if(Int(old,"statecode")!=0)await Patch(client,junction.EntitySetName,RequiredGuid(old,junction.PrimaryIdAttribute),new Dictionary<string,object?>{{"statecode",0}},token);continue;}await Create(client,junction.EntitySetName,new Dictionary<string,object?>{{junction.PrimaryNameAttribute,$"{responseId:D} · {optionId:D}"},{responseRelation.NavigationProperty+"@odata.bind",$"/{response.EntitySetName}({responseId:D})"},{optionRelation.NavigationProperty+"@odata.bind",$"/{option.EntitySetName}({optionId:D})"},{"statecode",0}},token);}
        foreach(var old in existing.Where(x=>Int(x,"statecode")==0&&OptionalGuid(x,$"_{optionRelation.ReferencingAttribute}_value") is {} id&&!selected.Contains(id)))await Patch(client,junction.EntitySetName,RequiredGuid(old,junction.PrimaryIdAttribute),new Dictionary<string,object?>{{"statecode",1}},token);
    }

    private static async Task<IReadOnlyList<HelpdeskManagementFieldValue>> ReadManagementAnswers(HttpClient client,Guid managementId,HelpdeskStageForm form,CancellationToken token)
    {
        var response=await DataverseMetadataResolver.TableAsync(client,"gaia_respuestacampogestion",token);var managementRelation=response.Relationship("gaia_GestionSolicitud","gaia_gestionsolicitud");var fieldRelation=response.Relationship("gaia_CampoFormularioPaso","gaia_campoformulariopaso");var rows=await DataverseJson.ReadAllAsync(client,$"{response.EntitySetName}?$select={response.PrimaryIdAttribute},{response.Attribute("gaia_ValorTexto")},{response.Attribute("gaia_ValorEntero")},{response.Attribute("gaia_ValorDecimal")},{response.Attribute("gaia_ValorFecha")},{response.Attribute("gaia_ValorFechaHora")},{response.Attribute("gaia_ValorBooleano")},_{fieldRelation.ReferencingAttribute}_value&$filter=statecode eq 0 and _{managementRelation.ReferencingAttribute}_value eq {managementId:D}",token);var ids=rows.Select(x=>RequiredGuid(x,response.PrimaryIdAttribute)).ToHashSet();var junction=await DataverseMetadataResolver.TableAsync(client,"gaia_respuestaopciongestion",token);var responseRelation=junction.Relationship("gaia_RespuestaCampoGestion","gaia_respuestacampogestion");var optionRelation=junction.Relationship("gaia_OpcionCampoFormularioPaso","gaia_opcioncampoformulariopaso");var options=ids.Count==0?[]:await DataverseJson.ReadAllAsync(client,$"{junction.EntitySetName}?$select=_{responseRelation.ReferencingAttribute}_value,_{optionRelation.ReferencingAttribute}_value,statecode&$filter=statecode eq 0",token);var grouped=options.Where(x=>OptionalGuid(x,$"_{responseRelation.ReferencingAttribute}_value") is {} id&&ids.Contains(id)).GroupBy(x=>OptionalGuid(x,$"_{responseRelation.ReferencingAttribute}_value")!.Value).ToDictionary(x=>x.Key,x=>(IReadOnlyList<Guid>)x.Select(o=>RequiredGuid(o,$"_{optionRelation.ReferencingAttribute}_value")).ToArray());var fields=form.Fields.ToDictionary(x=>x.Id);
        return rows.Select(row=>{var id=RequiredGuid(row,response.PrimaryIdAttribute);var fieldId=RequiredGuid(row,$"_{fieldRelation.ReferencingAttribute}_value");if(!fields.TryGetValue(fieldId,out var field))return null;var value=field.DataType switch{299540040=>Text(row,response.Attribute("gaia_ValorTexto")),299540041=>NullableInt(row,response.Attribute("gaia_ValorEntero"))?.ToString(CultureInfo.InvariantCulture),299540042=>Decimal(row,response.Attribute("gaia_ValorDecimal"))?.ToString(CultureInfo.InvariantCulture),299540043=>Text(row,response.Attribute("gaia_ValorFecha")),299540044=>Text(row,response.Attribute("gaia_ValorFechaHora")),299540045=>row.TryGetProperty(response.Attribute("gaia_ValorBooleano"),out var boolean)?boolean.GetBoolean().ToString().ToLowerInvariant():null,_=>null};return new HelpdeskManagementFieldValue(id,fieldId,value,grouped.GetValueOrDefault(id,[]));}).Where(x=>x is not null).Cast<HelpdeskManagementFieldValue>().ToArray();
    }
}
